### ISSUE TITLE
C++ 17 support

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/nano-node#1044]
C++17 is well supported by all major compilers and I think we should move soon-ish as it has a lot of useful features and improvements (std::optional/any/variant, nested namespaces syntax, filesystem, structured bindings, etc) 

This issue tracks what needs to be done.

- [x] Replace `std::random_shuffle`. This was deprecated in C++14 and removed in C++17. I'm making a PR that moves to random_pool#Shuffle *
- [x] Upgrade `cryptopp` which uses std:: features that's been deprecated since C++11 and removed in C++17. cryptopp has been C++17 compliant since January  **
- [ ] Compile and run testes on clang, gcc and msvc 2015+ ***
- [ ] Verify that C++17 is supported by commonly used LTS versions

*) https://github.com/nanocurrency/raiblocks/pull/1045
**) https://github.com/nanocurrency/raiblocks/pull/1068 / https://github.com/weidai11/cryptopp/pull/559
***) node and wallet works on macOS/clang

**Comment by guilhermelawless** [comment]
`noexcept` qualifier gives ~1% free performance as well, but has to be used with care.

**Comment by clemahieu** [comment]
What Linux distro versions have gcc/clang versions that support c++17 installed or supported?

I’d like to make sure we don’t require too new of a distro version, especially if it gets us off of commonly used LTS versions.

**Comment by cryptocode** [comment]
Added that point to the list of things to do. No rush moving to C++17, but if it's supported everywhere, it looks like a good move.

**Comment by argakiig** [comment]
have you looked at MSVC support? I have moved auto builds to MSVC15 in appveyor

**Comment by cryptocode** [comment]
argakiig yeah, it's a bit too soon still for msvc - see C++17 section at https://en.cppreference.com/w/cpp/compiler_support

We should probably wait with the move until we can rely on VS 17.

**Comment by rkeene** [comment]
If #1439 is merged, update locks used by `rpc_stats_objects_generated` to use `std::scoped_lock`

**Comment by SergiySW** [comment]
@cryptocode It seems MSVC17 now has full support of C++17

**Comment by cryptocode** [comment]
@SergiySW Excellent! The question now is if commonly used LTS distros support it, as Colin noted above.

**Comment by SergiySW** [comment]
Debian 9 Stretch - GCC 6.3 (no)
Debian 10 Buster (release estimated mid-2019) - GCC 8.2 (yes)
Ubuntu 16.04 LTS - GCC 5.3 (no)
Ubuntu 18.04 LTS - GCC 7.4 (yes, except Elementary string conversions & std::filesystem)
RHEL 7 / CentOS 7 - GCC 4.8 (no)
RHEL 8 beta / CentOS 8 (mid-2019 ?) - GCC 8.2 (yes)

**Comment by cryptocode** [comment]
Nice overview @SergiySW. So I guess it's still too early, not sure we can always ask to upgrade GCC in the (no) cases.

**Comment by SergiySW** [comment]
Some Linux distribution C++17 support:
* Debian 10 Buster - GCC 8.2 (yes; except Polymorphic memory resources, Standardization of Parallelism TS)
* Ubuntu 18.04 LTS - GCC 7.4 (yes; except Elementary string conversions,  std::filesystem, Polymorphic memory resources, Standardization of Parallelism TS)
* Ubuntu 20.04 LTS (April 2020) - GCC 9.2 (yes)
* RHEL 8 / CentOS 8 - GCC 8.2 (yes; except Polymorphic memory resources, Standardization of Parallelism TS)

https://en.cppreference.com/w/cpp/compiler_support

**Comment by zhyatt** [comment]
@clemahieu Can we close this out now?
