### ISSUE TITLE
[Proposal] Option to track block timestamp for local wallet/node without including in blockchain

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/nano-node#105]
Perhaps similar way as Byteball
_A: There are no timestamps in Byteball protocol, they are just not needed. That's why there are no reliable timestamps.
The ones you see in History tab are the times and dates when your wallet first learnt about the transaction (or, if you are on light wallet, when the light vendor first learnt about the tx)._
https://www.cryptocompare.com/coins/gbyte/post/p_19565

Also it would be useful for services that confirm incoming RaiBlocks transactions based on time (such as 1-2-3 minutes from receiving)

**Comment by rkeene** [comment]
We track a few different timestamps in the database -- does that resolve this issue ?

**Comment by SergiySW** [comment]
No, we track only last account change
Partially solved with https://github.com/nanocurrency/raiblocks/pull/994

**Comment by zhyatt** [comment]
After sideband updates this issue resolved with #994
