### ISSUE TITLE
Plan for replacing the real-time network underlying architecture

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1095]
The real-time network, where blocks, votes, and request for votes are first broadcast to all peers is currently implemented on top of UDP.

This has the advantage of being connection-less, so no setup is required, in principle, to send a block and light-weight since UDP has very little overhead.  However, this has the disadvantage of putting a lot of work ensuring some properties of the real-time network that we care about are maintained within our application itself.

We are going to evaluate potential replacements to UDP and compare them to UDP and each other.

With this information in hand, we can then decide what architecture we want to change to or if we are already using the best available one.

There have been several suggestions and these are the ones we will discuss:

- UDP (incumbent)
- TCP, as part of the bootstrap network
- QUIC
- Protocol Buffers

**Comment by zhyatt** [comment]
TCP covered in #1962

**Comment by qwahzi** [comment]
Closing:
- Due to age
- [UDP has been deprecated](https://docs.nano.org/releases/release-v21-0/#udp-disabled-by-default)
- TCP has been implemented
- QUIC is not actively being implemented

CC: @dsiganos
