### ISSUE TITLE
Easy way to switch between beta/live network

### ISSUE THREAD

**Issue by Inkeliz** [nanocurrency/nano-node#1099]
In Bitcoin allow the user to switch between live/testnet change the configuration of `bitcoin.conf`, setting `testnet=1`. It's easier and simple. This behavior are present in many others cryptocurrencies.

Why not create a new field in [`config.json`](https://github.com/nanocurrency/raiblocks/wiki/config.json):

```
{
   "node": {
          ....
          "network_mode": "C", // Switch between network modes. A = Test, B = Beta, C = Live
          ....
   }
}
```

It's possible?

**Comment by rkeene** [comment]
It is possible, and we have been wanting to make this change for a while but have not implemented to-date.  We will make this change in the future.  Thank you for the contribution !

**Comment by cryptocode** [comment]
A CLI option might be best here, allowing config files for the chosen network to be created on startup.

* live/beta repweights must be handled, these are currently compiled in
* the nano lib gets the build flag passed in. This must probably become a runtime parameter.

**Comment by wezrule** [comment]
Bitcoin has `-testnet` and Ethereum has `--testnet` which can be used as CLI options. Would be good to be consistent, although we use the term beta for this purpose, so could be some confusion between our test network.. `--betanet` & `--testnet`?

**Comment by cryptocode** [comment]
We should probably keep the flag names consistent with terms used within the Nano community, regardless of what other projects do. So simply livenet, betanet and testnet IMO.

**Comment by wezrule** [comment]
Yes agreed, but we should also try and maintain some form of consistency with naming if there are acceptable standards adopted by projects already, just to make multi node service's lives easier. I don't think livenet is necessary as it should be the default

**Comment by cryptocode** [comment]
Yeah I think multiple nets should be an error.
