### ISSUE TITLE
Slow refresh rate of block number

### ISSUE THREAD

**Issue by Sovxx** [nanocurrency/nano-node#1102]
nano_wallet v15.2
Ubuntu 64 18.04

GUI improvement

The block count is updated every 10s to 3min (very roughly).
Not sure how the tech actually works backstage, but if possible it would look more "satisfying" to have the block count update every 1s (like a transfer in emule or bittorrent).

**Comment by Nanoraii** [comment]
I noticed that too. Since v15 the block count shown in the wallet is always lagging behind. I have to do a block count via RPC to get the correct number. As soon as you do the block_count command also the GUI updates to the correct number. Was there a change in the refresh rate?

**Comment by Sovxx** [comment]
From my personal experience, I have not noticed big differences in refresh rate since v10 or maybe before.

**Comment by i3bitcoin** [comment]
This is true, since I upgraded to Release V15.2, I'm 6000 bloks behind and can't catch the latest block, 
Maybe it's somehow connected to the increase of blocks generated last days.

**Comment by i3bitcoin** [comment]
Finally, after the downgrade back to 14.2 I got synced with the latest blocks immediately, be sure it's a bug/technical trait of the Release 15.2.

**Comment by cryptocode** [comment]
Possibly solved by https://github.com/nanocurrency/nano-node/pull/1482

**Comment by cryptocode** [comment]
This appears to be fixed. Feel free to reopen if you think there's still an issue.
