### ISSUE TITLE
Tool to build local beta-style network

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1133]
Tool to build local beta-style network with full ledger and a few nodes

**Comment by rkeene** [comment]
I did not get to this, trying again in the next release.

**Comment by zhyatt** [comment]
Related to #918

**Comment by dsiganos** [comment]
This issue does not have a good enough description and is possibly done by @gr0vity-dev's work. Closing.

**Comment by qwahzi** [comment]
For future readers, two of the related local-network projects by gr0vity are:

- [Nano-Local](https://github.com/gr0vity-dev/nano-local)
- [Nano-Bench](https://github.com/gr0vity-dev/nano-bench)
