### ISSUE TITLE
Enhancement Request: Update Ledger RPC action to show unopened accounts with pending balance

### ISSUE THREAD

**Issue by Srayman** [nanocurrency/nano-node#1166]
**Description of bug:**
When using the RPC action "ledger" it appears to not show unopened accounts.  Is it possible to enhance the action to return all accounts including those that do not have frontier blocks?  Or create another action to return all accounts with a pending balance that are not opened yet?

**Steps to reproduce the issue:**
1. Parsing through all 560k+ accounts from the ledger action results in a total about 2 million NANO less than the available supply.  Best guess is these are made up of unopened accounts since I was able to verify that an unopened account without a frontier block does not show up from the ledger action.  
2. Running the action "account_balance" on an unopened account returns the correct pending balance.

**Describe the results you received:**
Expected to see the total balance+pending from accounts returned by the "ledger" action to match the available supply.  Results of all accounts from "ledger" is  131262162524572716751492490483419331982.

**Describe the results you expected:**
Expected to see the total of balance+pending from the "ledger" action to match the available supply of 133248289196499221154116917710445381553

If it doesn't make sense to update the "ledger" action to show unopened accounts then could another action be added that shows all accounts that are unopened with a pending balance?

**Comment by bghrn** [comment]
I have the same problem, my coins are pending in unopened account, can you help me to take back my coins? I will share my coins whoever help me, thank you in advance.

**Comment by SergiySW** [comment]
Closed with https://github.com/nanocurrency/nano-node/pull/1727 (v19)
