### ISSUE TITLE
I/O Streams are not Thread-Safe in general

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1236]
Lots of logging is done using I/O streams (`BOOST_LOG` is just a macro around an ostream), in a thread-unsafe way.  With lots of logging enabled, deadlock can occur during I/O.

**Comment by rkeene** [comment]
It appears our BOOST_LOG is backed by a mutex-protected stream.  This can (and sometimes does) still cause a deadlock if objects piped into it are creating mutexes, so it must be considered.

Options for this are to create a lock-free version to back BOOST_LOG or ensure we only log values.

**Comment by rkeene** [comment]
I'm moving this out of V16.1 since it is not as common as initially suspected, especially if you don't have a bunch of logging enabled.

**Comment by rkeene** [comment]
Pushing this further out as we are generally careful about what we do log.

**Comment by cryptocode** [comment]
I've inspected every BOOST_LOG line on master and it appears we no longer pipe in anything that takes a mutex or calls boost log.
