### ISSUE TITLE
Create GDB Functions for Nano Node

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1267]
To aid in debugging, we need to create some gdb user defined functions (probably in Python -- I created some in the GDB scripting language and it wasn't sophisticated enough).

Some things we want to know while debugging:
     1. List of locked mutexes, which thread owns it and which threads are trying to acquire it (only for mutexes that are currently trying to be acquired?)
     2. More things we think of...

**Comment by rkeene** [comment]
We will want this to help with investigating memory usage to start with.

**Comment by zhyatt** [comment]
Other preferred tools are being used instead of this.
