### ISSUE TITLE
Rename repository "nano-node"

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1305]
During the V18 development cycle let's rename the "raiblocks" repository to "nano-node".  We'll include all the milestones, issues, pull requests, code, wiki, etc in the rename.

The old raiblocks repository's code should be kept up-to-date by syncing it for a few more releases.  We'll disable issues and pull requests and milestones.  The wiki can either be updated to include references to the new page or synchronized from the new repository for a period of time like the code.

**Comment by argakiig** [comment]
It should just be a matter of renaming the repo, or are you proposing we have two repos? and then phase one out?

**Comment by cenkalti** [comment]
Please do not make 2 separate repos 🙏

**Comment by argakiig** [comment]
when 18 is released updates to the wiki will be pushed again closing out the ticket
