### ISSUE TITLE
Consider update config.json file in wiki

### ISSUE THREAD

**Issue by gabrielmendanha** [nanocurrency/nano-node#1367]
I was setting up a private nano network for educational purposes, while browsing the wiki to learn how to proprely configure nanode I noticed the key `preconfigured_peers` receive an IPv4 address. But turns out nanode can't connect to peers described in this format. It only connected after I prefixed my IP with `::ffff:`.
Should the example be updated to: `::ffff:138.201.94.249`?

**Comment by zhyatt** [comment]
Wiki updated
