### ISSUE TITLE
Cache peers

### ISSUE THREAD

**Issue by rotilho** [nanocurrency/nano-node#1374]
It would be nice to the node cache all peers when certain threshold is reached.

This would speed up peer discovery in case of restart and would remove the dependence to the DNS after first execution.

More details:
- When the threshold is reached all peers are cached in the database
- Every X seconds the cache is replaced with current peer list
- If the number of peer is below threshold cache is not updated anymore
- After start up node sends handshake to all cached peers

**Comment by wezrule** [comment]
This has been solved by #1608
