### ISSUE TITLE
Update Bulk Pull Account to allow specifying a block hash

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1435]
Update Bulk Pull Account (added in #988) to allow specifying a block hash instead of an account, similar to how `bulk_pull` works.  It should function by getting the account that the block specified belongs to, and operating on that.

This can be used to fetch the account for a block hash.

Also update issue #988 with this information, for completeness.

**Comment by zhyatt** [comment]
Closing as this capability already exists to call bulk_pull with block hash to get all account blocks before the hash.
