### ISSUE TITLE
Confirm dependent elections

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1441]
After merging #1303 we can improve `confirm_back()` as noted in #1438

**Comment by cryptocode** [comment]
Depends on the confirmation height rewrite. It may make sense to bake this into that PR. Will coordinate with Wesley.

**Comment by cryptocode** [comment]
https://github.com/nanocurrency/nano-node/pull/1801 replaces confirm_back with adding confirmation height.
