### ISSUE TITLE
verify_state_blocks() with a max is O(n)

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1475]
`verify_state_blocks()` with a max parameter (added in #1450) is O(n)

with 1000000 items in the `state_blocks` deque it takes much more time to do the swap than with 10000 items, given the same "max" parameter

**Comment by rkeene** [comment]
Relevant section: https://github.com/nanocurrency/raiblocks/blob/49b047d0c78c440cdd283cbdfb3f97bd09731446/rai/node/node.cpp#L1311

**Comment by cryptocode** [comment]
Here are my notes:

`auto position = std::distance(state_blocks.begin(), state_blocks.end () - keep_size);` => 2048
so `swap_ranges` gets to iterate the whole shebang minus max_count
that said, resize is taking even more time in my measurements depending on deque size

**Comment by SergiySW** [comment]
Closing with https://github.com/nanocurrency/nano-node/pull/1571
