### ISSUE TITLE
Large delay in resuming block checking on tags/V17.0 for partially sync'd node

### ISSUE THREAD

**Issue by VenKamikaze** [nanocurrency/nano-node#1487]
OS: ArchLinux kernel 4.20-rc6
System: ARMv8 (rockchip RK3399 firefly)
RAM: 2GB

I was testing sync from scratch on the beta nano network with the tags/V17.0 release.
During the middle of sync, I accidentally took down the node (cleanly, no crash).

On restart of the node, it checked blocks very slowly approx 1 every 5 minutes.

On checking bootstrap_status during this period of slowdown, it showed an increasing 'total_blocks' count, in fact it increased by over a million blocks while checked/unchecked showed barely any change.

I created a pastebin showing local block_count RPC data from this sync versus a checked block count from a remote node:
https://pastebin.com/CXuDy9yD

Also included are two runs of bootstrap_status before the node started to check blocks quickly again.

After approximately an hour (almost exactly where the data from this pastebin ends), block checking resumed at a high rate.

**Comment by argakiig** [comment]
changes to unchecked table being cleared on startup in v18 should address this, will close on v18 release but please monitor and reopen if issue persists

**Comment by VenKamikaze** [comment]
I did notice in one of the v18 RCs that on stopping and starting the node during sync, that the unchecked blocks were reset to '0' - now that I've read your comment, that makes sense. 

I will keep tabs on how long it takes to then resume pulling down blocks after that situation when I have time to check next.

**Comment by argakiig** [comment]
seems to be resolved in my testing, will close the ticket if the issue persists please reopen
