### ISSUE TITLE
V17 RPC returns no pending blocks until I restart the node.

### ISSUE THREAD

**Issue by danhitchcock** [nanocurrency/nano-node#1488]
My V17 (**edit: V16.3 now seems to have this behavior) node will give me my unpocketed balance, but when I request unpocketed transaction hashes (via pending), I get an empty field. If I restart the node, it then functions properly for a while before failing. Other node functions seem to still work (send, check_balance). I'm not sure what triggers it, but it seems to only a few minutes for the node to stop functioning properly. I wrote python bindings to retrieve them:

```
def perform_curl(data=None, URL=None):
    if URL is None:
        URL = '192.168.3.106:7076'

    c = pycurl.Curl()
    c.setopt(c.URL, URL)
    buf = BytesIO()
    if data:
        data = json.dumps(data)
        c.setopt(pycurl.POSTFIELDS, data)

    c.setopt(c.WRITEFUNCTION, buf.write)
    c.perform()
    results = buf.getvalue()
    results = results.decode("utf-8")
    results = json.loads(results)
    buf.close()
    return results

def get_pending(account, count=-1):
    data = {
        "action": "pending",
        "account": account,
        "count": str(count) # usualy -1
    }
    results = perform_curl(data)
    #print(results)
    return results
```

get_pending should return a list of unpocketed hashes. So far, it's fairly reproducible.

I am running Windows 10 Pro on a Corei5 3570k with 16GB RAM
In the two logs below, I attempted to retrieve pending amounts for the account xrb_3iso3r9dr1yi5zi67p4ca9hfd11giucnh68dzc5f3hybw5a7pwcny8hfsuih. The earlier log has successful retrievals in the beginning, but they fail at the end. It would show the correct pending account balance, but not return pending transaction hashes. I closed the node and reponened it, and attempted another 'pending' request, which was successful.

***EARLIER LOG***

[log_2018-12-19_01-20-03.115.log](https://github.com/nanocurrency/raiblocks/files/2693523/log_2018-12-19_01-20-03.115.log)

***AFTER RESTART***

[log_2018-12-19_01-25-16.116.log](https://github.com/nanocurrency/raiblocks/files/2693525/log_2018-12-19_01-25-16.116.log)

**Comment by icarusglider** [comment]
Evaluated this request method (using provided code) against a V18 node with pending transactions. Over a period of 1 hour all requests returned the pending block hashes. At no time did the returned values go null.  It appears this issue has been resolved at the current node release.
