### ISSUE TITLE
RPC: Wallet not found

### ISSUE THREAD

**Issue by sharifzadesina** [nanocurrency/nano-node#1543]
I just created several wallets but when I try to control them using RPC requests it just says "Wallet not found".
My `rai_node --wallet_list` output:
```
Wallet ID: BC430A7615F467BE6517C763BC13D76839C464FF54D8B8BB9992BAA7907EA43C
xrb_3p8eoun3q8wjysodqr96t5m6mygtk6f4hioagf8f5758n3q4d3ax5947bw3a
Wallet ID: 84FB4FF5D25EC378043A06E185CE5239938D4F6F3DC21C43BCF75B75DDF7698C
Wallet ID: 55973F1556A7DC581F6FBCF4FF38DDF1DB213BFD97CB5A1541C2AC77A8642086
```
My `rai_node --version` output:
```
Version 17.0
```
My RPC request body:
```json
{ "action": "account_create", "wallet": "BC430A7615F467BE6517C763BC13D76839C464FF54D8B8BB9992BAA7907EA43C" }
```
Expected result:
```json
{ "account": "<account>" }
```
Actual result:
```json
{ "error": "Wallet not found" }
```
Just to mention I can create new accounts using cli commands, only RPC fails.

**Comment by sharifzadesina** [comment]
Weird, I just restarted docker-container and it started working.

**Comment by renesq** [comment]
CLI-created wallets requite a restart of the daemon in order to take effect. 

I generally tend to avoid wallet-altering CLI commands as we experienced strange behaviors with it.
