### ISSUE TITLE
How to get block content by height

### ISSUE THREAD

**Issue by Robwpy** [nanocurrency/nano-node#1544]
I could't understand nano blockchain very clear. How could i get block content by block height? I did't find rpc interface about this. So how could i get all block info?

**Comment by renesq** [comment]
Each account has its own chain that links from and to other chains. Each block contains a single action (a settled *trans*action consists of 2 blocks), and the collective of all blocks generally does not have a classic linear order like they do in BTC, hence there is no block number and no block height in NANO. You can however sequentially number each account's blocks, and also obtain block contents by knowing the block hash (or by following the traces).

**Comment by Robwpy** [comment]
In that case, I could only check my account to determine if someone has transferred me. Or could I get the latest block information to judge?

**Comment by Robwpy** [comment]
> Each account has its own chain that links from and to other chains. Each block contains a single action (a settled _trans_action consists of 2 blocks), and the collective of all blocks generally does not have a classic linear order like they do in BTC, hence there is no block number and no block height in NANO. You can however sequentially number each account's blocks, and also obtain block contents by knowing the block hash (or by following the traces).

block contents by knowing the block hash ,I also could find rpc method
traces is node settings？

**Comment by renesq** [comment]
You can for example monitor your own account, yes. Or monitor other peoples' accounts. What use-case exactly do you want to achieve? If you want to programmatically detect incoming payments for a real-time service, you may want to carefully plan the process, and it's a bit too much to cover right now. 

If you just want to check for everything that happened on an account at some time in the past, simply use 
` "action": "account_history",  ...` for example. It will show incoming and outgoing transactions that were successfully processed ("pending" incoming transactions will not appear there). 

You can also get an alphabetical list of other active accounts with the  `"action": "frontiers", ...` command and track metadata around this. But the protocol itself will not let you search for specific dates if that's what you want.

**Comment by Robwpy** [comment]
thanks a lot. 

I am using testnet. After the process block, the balance is always in pending.

Any advice？

**Comment by Robwpy** [comment]
I set the callback parameter. When I sent a block in the test network, I didn't receive a callback. This is my configuration file.


`"callback_address": "http://127.0.0.1"`,
        `"callback_port": "55555"`
        `"callback_target": "/nano"`

The number of blocks in the account information obtained from rpc has indeed increased.
I could access my server using the curl command.

**Comment by renesq** [comment]
@Robwpy I think you used the wrong URL format. Try "localhost". No http.

**Comment by Robwpy** [comment]
Nano  use ed25519 with blake2b to generate address and sign tx, is right?
or just use ed25519 with blake2b to sign , use ed25519 with sha512 to generate address

When use key to receive a block,node return signed block,account is not my privatekey generated

so , where I missed?

**Comment by zhyatt** [comment]
@Robwpy Many of the details you need will be in https://developers.nano.org/guides/external-management/ or https://github.com/nanocurrency/nano-node/wiki.
