### ISSUE TITLE
Question: account import

### ISSUE THREAD

**Issue by sharifzadesina** [nanocurrency/nano-node#1545]
I've created an account from a Nano node desktop client but the node was/is not fully synced, I've imported the wallet seed on nanovault.io but I can't use the account and its money, how can I import the wallet with all its accounts and use the money?
[here](https://www.nanode.co/account/xrb_16u6y3dwhzmk6icudgxsn89pho9e76sfq9r4ep8mdox9hwse7pfwu9m1k8eq) is the account on blockchain.

**Comment by renesq** [comment]
In nanovault, try adding more accounts in the account overview. If that still doesn't work, there are other solutions to the problem, for example by using the "sweep" mechanism of Natrium mobile wallet and starting over with a new seed. 

Or maybe you don't even have money on that seed. You can analyze that for example by looking up the public keys of the desktop client's backup file on a block explorer after translating them to base32 addresses.

**Comment by sharifzadesina** [comment]
@renesq Sorry my bad, I edited the first post.

**Comment by sharifzadesina** [comment]
@renesq Why we can't export/import account private keys like bitcoin? I think that would be easier.

**Comment by renesq** [comment]
Nanovault does not offer private key import at the moment. Only some wallets do. It's a rare use-case.

**Comment by sharifzadesina** [comment]
@renesq The problem of this way is it is almost use-less if we have for example 1000 accounts and we want to recover 1000th.

**Comment by renesq** [comment]
That's why you'd use a different approach for those cases, doing it programmatically. I for example wrote [a tool to retrieve private keys if you don't remember the index number](https://nanoo.tools/find-address), among other possibilities.
