### ISSUE TITLE
Add support for realtime network traffic over the bootstrap TCP port

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1548]
Add support for realtime network traffic over the bootstrap TCP port.

Current plan is to use the Keepalive message to indicate that the stream is a realtime stream, causing realtime updates to be sent over the socket.

**Comment by rkeene** [comment]
See also #1095

**Comment by SergiySW** [comment]
Support in https://github.com/nanocurrency/nano-node/pull/1962
