### ISSUE TITLE
Node synchronization is very slow

### ISSUE THREAD

**Issue by Little-Huang** [nanocurrency/nano-node#1582]
**Node synchronization is very slow**

**Desc**
1.Version: release v17.0   
2.The synchronization time has exceeded 24 hours. There is no pause in the middle.
3.Use nano_node --debug_block_count  
   result: Block count: 3394
 4.So sad

**logs**
[log_2019-01-13_04-48-14.12.txt](https://github.com/nanocurrency/nano-node/files/2752840/log_2019-01-13_04-48-14.12.txt)

**Comment by renesq** [comment]
Do you use a SSD for the database folder?

**Comment by Little-Huang** [comment]
@renesq   No, use HDD 

Dual   8G RAM  200G 
centos 7
AWS

**Comment by jadermcs** [comment]
As sync is IO intensive in a HDD it would took days or not even sync (there are developers researching on this), by now it should be done in a SSD, which it takes approximately 3hours.

**Comment by Little-Huang** [comment]
@jadermcs  
Thank you for your suggestion, the problem has been solved, and the synchronization is completed by loading offline data. 
[here](https://drive.google.com/drive/folders/1sP1z9S011f1W_0nK1KJ-UCJbjaNmk8GQ?usp=sharing)
