### ISSUE TITLE
Improve IO when reading known block types

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/nano-node#1583]
Same treatment for reading as for existence (https://github.com/nanocurrency/nano-node/pull/1484)
Basically give block_(raw_)get an overload with a block type parameter. This will read from the correct table directly instead of checking all block tables.

**Comment by cryptocode** [comment]
Testing so far indicates there doesn't seem to be much benefit from doing this, the block type is usually unknown. Moving to Research for Future Releases.

**Comment by zhyatt** [comment]
@cryptocode Is this worth keeping around still or should we close it out?

**Comment by cryptocode** [comment]
Yeah can be closed
