### ISSUE TITLE
How can I support the recharge and withdrawal of nano?

### ISSUE THREAD

**Issue by Little-Huang** [nanocurrency/nano-node#1588]
**I am now accessing the nano recharge and withdrawal service like the exchange, but I have not found the right information to support me to do this. Is there a good tutorial to support? 
The node is now deployed.
Thanks.**

**Comment by icarusglider** [comment]
Can you explain further what you have already set up and what you are trying to accomplish?

**Comment by Little-Huang** [comment]
@icarusglider  
Nodes have been deployed and synchronized.

Next, you need to access the charge and allocate the account to the user. Let them use nano to play games with us. This process is very similar to the exchange.

Right, I am using java.


Thanks.

**Comment by qwahzi** [comment]
Have you checked out the RPC documentation on the developer site? https://developers.nano.org/docs/rpc/

**Comment by zhyatt** [comment]
@Little-Huang As mentioned above you can find details on RPC calls needed here: https://developers.nano.org/docs/rpc/ and also additional integration details in the guides here: https://developers.nano.org/guides.
