### ISSUE TITLE
Error nano_node install

### ISSUE THREAD

**Issue by macielcr7** [nanocurrency/nano-node#1604]
When I run the make nano_node command the following error occurs.
I'm installing on aws.

```
[nano_build]$ make nano_node
[  1%] Built target blake2
[  4%] Built target xxhash
[ 39%] Built target cryptopp
[ 41%] Building CXX object nano/lib/CMakeFiles/nano_lib.dir/errors.cpp.o
In file included from /home/ec2-user/nano_build/nano/lib/errors.cpp:1:0:
/home/ec2-user/nano_build/nano/lib/errors.hpp:132:72: error: ‘remove_reference_t’ in namespace ‘std’ does not name a type
 auto either (T && value, std::error_code ec) -> expected<typename std::remove_reference_t<T>, std::error_code>
                                                                        ^
/home/ec2-user/nano_build/nano/lib/errors.hpp:132:90: error: expected template-argument before ‘<’ token
 auto either (T && value, std::error_code ec) -> expected<typename std::remove_reference_t<T>, std::error_code>
                                                                                          ^
/home/ec2-user/nano_build/nano/lib/errors.hpp:132:90: error: expected ‘>’ before ‘<’ token
/home/ec2-user/nano_build/nano/lib/errors.hpp:132:110: error: wrong number of template arguments (1, should be 2)
 auto either (T && value, std::error_code ec) -> expected<typename std::remove_reference_t<T>, std::error_code>
                                                                                                              ^
In file included from /home/ec2-user/nano_build/nano/lib/errors.hpp:6:0,
                 from /home/ec2-user/nano_build/nano/lib/errors.cpp:1:
/home/ec2-user/nano_build/nano/lib/expected.hpp:103:7: error: provided for ‘template<class T, class E> class tl::expected’
 class expected;
       ^
In file included from /home/ec2-user/nano_build/nano/lib/errors.cpp:1:0:
/home/ec2-user/nano_build/nano/lib/errors.hpp:133:1: error: expected ‘::’ before ‘{’ token
 {
 ^
/home/ec2-user/nano_build/nano/lib/errors.hpp:133:1: error: expected identifier before ‘{’ token
/home/ec2-user/nano_build/nano/lib/errors.hpp: In member function ‘nano::error& nano::error::accept(ErrorCode ...)’:
/home/ec2-user/nano_build/nano/lib/errors.hpp:369:72: error: parameter declared ‘auto’
   if (std::any_of (codes.begin (), codes.end (), [this, &codes](auto & code_a) { return code == code_a; }))
                                                                        ^
/home/ec2-user/nano_build/nano/lib/errors.hpp: In lambda function:
/home/ec2-user/nano_build/nano/lib/errors.hpp:369:97: error: ‘code_a’ was not declared in this scope
   if (std::any_of (codes.begin (), codes.end (), [this, &codes](auto & code_a) { return code == code_a; }))
                                                                                                 ^
make[3]: *** [nano/lib/CMakeFiles/nano_lib.dir/errors.cpp.o] Error 1
make[2]: *** [nano/lib/CMakeFiles/nano_lib.dir/all] Error 2
make[1]: *** [nano/nano_node/CMakeFiles/nano_node.dir/rule] Error 2
make: *** [nano_node] Error 2
```

[https://drive.google.com/open?id=10U8W1c7Lyo2_p773wfVCGM8Mc_23gDuB](url)

**Comment by SergiySW** [comment]
Check software versions
```
uname -a
cmake --version
gcc -v
```
(if you are using GCC compiler)

**Comment by cryptocode** [comment]
It complains about a type from C++14, which is the minimum C++ std version supported.

**Comment by rkeene** [comment]
Should we update CMake to abort if it can't arrange for a compilation environment that meets our needs ?

**Comment by cryptocode** [comment]
(closed by mistake instead of clicking comment...) 

We have
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
shouldn't that bark at < 14 envs?

**Comment by rkeene** [comment]
@macielcr7 Can you re-run CMake with the additional argument `-DCMAKE_VERBOSE_MAKEFILE=ON` as well as provide the invocation of CMake used ?

**Comment by macielcr7** [comment]
> gcc -v

**Comment by macielcr7** [comment]
> Check software versions
> 
> ```
> uname -a
> cmake --version
> gcc -v
> ```
> ( last one if you are using GCC compiler)

```
> uname -a
Linux ip-172-31-13-29 4.14.77-70.82.amzn1.x86_64 #1 SMP Mon Dec 3 20:01:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> cmake --version
cmake version 3.12.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).

cmake3 version 3.6.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).

> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-amazon-linux/7/lto-wrapper
Target: x86_64-amazon-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --disable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --without-isl --disable-libmpx --disable-libsanitizer --enable-gnu-indirect-function --disable-libcilkrts --disable-libatomic --disable-libquadmath --disable-libquadmath-suport --disable-libitm --disable-libgomp --with-tune=generic --with-arch_32=x86-64 --build=x86_64-amazon-linux
Thread model: posix
gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC)
```

**Comment by wezrule** [comment]
Can you try compiling this using gcc?

```
#include <type_traits>
int main() {
	std::remove_reference_t<int> i;
 }
```

**Comment by macielcr7** [comment]
> Can you try compiling this using gcc?

how do I do that? This error occurs when I run make nano_node

**Comment by wezrule** [comment]
save that to a file (e.g `test.cpp`)
Then run `gcc -std=c++14 test.cpp` on the terminal.

I just want to double check that this compiler is actually the problem or not.

**Comment by macielcr7** [comment]
> gcc -std=c++14 test.cpp

$ nano test.cpp
$ gcc -std=c++14 test.cpp
gcc: error trying to exec 'cc1plus': execvp: No such file or directory

**Comment by wezrule** [comment]
Looks like you don't have c++ support, can you run this and try again:
`sudo dnf install gcc-c++`

**Comment by macielcr7** [comment]
> Looks like you don't have c++ support, can you run this and try again:
> `sudo dnf install gcc-c++`


Thank you has now given this error.
```
[ 82%] Building CXX object nano/node/CMakeFiles/node.dir/bootstrap.cpp.o
virtual memory exhausted: Cannot allocate memory
make[3]: *** [nano/node/CMakeFiles/node.dir/bootstrap.cpp.o] Error 1
make[2]: *** [nano/node/CMakeFiles/node.dir/all] Error 2
make[1]: *** [nano/nano_node/CMakeFiles/nano_node.dir/rule] Error 2
make: *** [nano_node] Error 2

```

**Comment by wezrule** [comment]
It appears you are running out of your allocated resources.
What EC2 instance are you running?
what does `top` return?

**Comment by macielcr7** [comment]
EC2 instance
t2.micro

`Tasks:  74 total,   1 running,  49 sleeping,   0 stopped,   0 zombie
Cpu(s): 19.5%us,  0.0%sy,  0.0%ni,  0.0%id,  0.3%wa,  0.0%hi,  0.0%si, 80.1%st
Mem:   1009432k total,   189124k used,   820308k free,     2256k buffers
Swap:        0k total,        0k used,        0k free,    17988k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
16403 ec2-user  20   0  814m 114m 1584 S 99.4 11.6   7:23.60 litecoind
    1 root      20   0 19692  332    0 S  0.0  0.0   0:01.36 init
    2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd
    3 root      20   0     0    0    0 I  0.0  0.0   0:00.00 kworker/0:0
    4 root       0 -20     0    0    0 I  0.0  0.0   0:00.00 kworker/0:0H
    6 root       0 -20     0    0    0 I  0.0  0.0   0:00.00 mm_percpu_wq
    7 root      20   0     0    0    0 S  0.0  0.0   0:47.17 ksoftirqd/0
    8 root      20   0     0    0    0 I  0.0  0.0   0:13.94 rcu_sched
    9 root      20   0     0    0    0 I  0.0  0.0   0:00.00 rcu_bh
   10 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 migration/0
   11 root      RT   0     0    0    0 S  0.0  0.0   0:00.70 watchdog/0
`

**Comment by cryptocode** [comment]
@macielcr7 just wanted to mention we also have a development channel on the Nano Discord server, https://discord.gg/ryX9AS

**Comment by wezrule** [comment]
I don't know if 1GB is enough memory, can you try shutting down the litecoin node?
`kill 16403`

But yeh, try there you may get more help.

**Comment by macielcr7** [comment]
Last mistake that happened ...

```
[100%] Linking CXX executable ../../nano_node
../lib/libnano_lib.a(perms.cpp.o): In function `boost::system::error_category::std_category::~std_category()':
perms.cpp:(.text._ZN5boost6system14error_category12std_categoryD0Ev[_ZN5boost6system14error_category12std_categoryD0Ev]+0x13): undefined reference to `std::error_category::~error_category()'
collect2: error: ld returned 1 exit status
make[3]: *** [nano_node] Error 1
make[2]: *** [nano/nano_node/CMakeFiles/nano_node.dir/all] Error 2
make[1]: *** [nano/nano_node/CMakeFiles/nano_node.dir/rule] Error 2
make: *** [nano_node] Error 2

```

**Comment by wezrule** [comment]
looks like there is some inconsistency in how the boost library was built and how you are building the node. Can you run this from the nano-node folder:
`util/build_prep/bootstrap_boost.sh -m -B 1.66`

Then rerun your cmake command and use `-DBOOST_ROOT=/usr/local/boost`

**Comment by macielcr7** [comment]
> looks like there is some inconsistency in how the boost library was built and how you are building the node. Can you run this from the nano-node folder:
> `util/build_prep/bootstrap_boost.sh -m -B 1.66`
> 
> Then rerun your cmake command and use `-DBOOST_ROOT=/usr/local/boost` Pay attention to the output from cmake to make sure it looks correct.

Thanks for the help, it worked.
