### ISSUE TITLE
Generating new "test" network parameters

### ISSUE THREAD

**Issue by lonnieOST** [nanocurrency/nano-node#1605]
Hello,

I hope that your day is going well.

I am running on Ubuntu 18.04 (x64) and all compiles, and runs just fine with the default settings, but now for testing, I would like to generate new "test" network parameters:

test_private_key_data
test_public_key_data

"source",
"representative"
"account"
"work",
"signature"

Lately, I have been able to setup a single node"test" network with the default "test" network settings that are shown in:

https://github.com/nanocurrency/nano-node/blob/master/nano/secure/common.cpp

which are:
--------------------------------------
.
.
.
/ Genesis keys for network variants
namespace
{
char const * test_private_key_data = "34F0A37AAD20F4A260F0A5B3CB3D7FB50673212263E58A380BC10474BB039CE4";
char const * test_public_key_data = "B0311EA55708D6A53C75CDBF88300259C6D018522FE3D4D0A242E431F9E8B6D0"; // xrb_3e3j5tkog48pnny9dmfzj1r16pg8t1e76dz5tmac6iq689wyjfpiij4txtdo
.
.
.
char const * test_genesis_data = R"%%%({
	"type": "open",
	"source": "B0311EA55708D6A53C75CDBF88300259C6D018522FE3D4D0A242E431F9E8B6D0",
	"representative": "xrb_3e3j5tkog48pnny9dmfzj1r16pg8t1e76dz5tmac6iq689wyjfpiij4txtdo",
	"account": "xrb_3e3j5tkog48pnny9dmfzj1r16pg8t1e76dz5tmac6iq689wyjfpiij4txtdo",
	"work": "9680625b39d3363d",
	"signature": "ECDA914373A2F0CA1296475BAEE40500A7F0A7AD72A5A80C81D7FAB7F6C802B2CC7DB50F5DD0FB25B2EF11761FA7344A158DD5A700B21BD47DE5BD0F63153A02"
})%%%";

.
.
.
--------------------------------------

Is there any utility or other way to generate these parameters?

Thanks :)

**Comment by clemahieu** [comment]
There isn't, the test network parameter is designed for use in unit testing and is sufficient; we do not support additional network initialization parameters.
