### ISSUE TITLE
Docker Image - Redirect logs output to Docker logs

### ISSUE THREAD

**Issue by lephleg** [nanocurrency/nano-node#1612]
Currently the log files are rotated making it challenging to collect and parse them efficiently. 

It would be nice if we could redirect the log stream to container logs, while keeping the current log structure intact.

**Comment by ksemaev** [comment]
This is really annoying having logs inside docker container, instead of stdout, tried to do it on Dockerfile/entry.sh level, but seems like it's deeper in code :(

**Comment by ksemaev** [comment]
BTW as I see we're rotating "${nanodir}/nano-docker-output.log", while the real log goes to ""${nanodir}/log/log_date_time.log"

**Comment by ksemaev** [comment]
Currently I did an ugly hack of adding here:
`mkdir -p "${nanodir}/log/" && touch "${nanodir}/log/log_start.log" && tail -F ${nanodir}/log/log_*.log &`

But still the issue of rotating one file, while another one is used needs to be fixed

**Comment by argakiig** [comment]
@ksemaev you can change the config.json for node.logging.log_to_cerr to `true`

**Comment by ksemaev** [comment]
@argakiig this would send logs to STDERR? Would it stop filling the container's filesystem?

**Comment by argakiig** [comment]
part of #2160

**Comment by argakiig** [comment]
closed with #2160
