### ISSUE TITLE
Error when building nano_node

### ISSUE THREAD

**Issue by apasov** [nanocurrency/nano-node#1624]
**Description of bug:**
I'm trying to build nano_node v17.1 as described in wiki.

**Steps to reproduce the issue:**
`git clone --recursive https://github.com/nanocurrency/nano-node.git nano_build`
`cd nano_build`
`git reset --hard 95bdbe706e88d10a70d50404af983b14f154f5a7`
`cmake -DBOOST_ROOT=../[boost]/ -G "Unix Makefiles"`
`make nano_node`

**Describe the results you received:**
`make: *** No rule to make target 'nano_node'.  Stop.`

**Environment**:
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)

**Comment by cryptocode** [comment]
It's still called rai_node in v17.1
