### ISSUE TITLE
Not all versions of GCC support -fsanitize-blacklist

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1656]
TSAN blacklist support (added in #1637) is not available in all versions of GCC.

**Comment by rkeene** [comment]
Ideally the build system would detect whether or not the compiler supports this.

**Comment by wezrule** [comment]
gcc does not support this option, but you can use a suppressions file in the TSAN_OPTIONS environment variable:
https://github.com/nanocurrency/nano-node/pull/1941
Documentation: https://github.com/nanocurrency/nano-node/wiki/Testing
