### ISSUE TITLE
Provide optional automatic ledger/wallet backups before an upgrade 

### ISSUE THREAD

**Issue by guilhermelawless** [nanocurrency/nano-node#1690]
QOL enhancement.

If upgrading the ledger, do a backup (controlled on/off via config, default off, and maybe change location via a launch flag). If upgrading the wallet, do the same.

**Comment by guilhermelawless** [comment]
Config backup was done here: https://github.com/nanocurrency/nano-node/pull/1959

**Comment by zhyatt** [comment]
Closed by #1959

**Comment by guilhermelawless** [comment]
@zhyatt The issue was regarding ledger (data.ldb) and wallet (wallet.ldb) backups, before things like the cementing or sideband upgrade. But these should be less frequent over time I guess (maybe again for pruning?).

That said, an automatic config backup is a great feature.

**Comment by zhyatt** [comment]
Wow, did I ever read that wrong. :) Reopening

**Comment by guilhermelawless** [comment]
Closed by #2198
