### ISSUE TITLE
RPC wallet_change_seed should return the first account created

### ISSUE THREAD

**Issue by guilhermelawless** [nanocurrency/nano-node#1717]
It can get confusing to users when they don't see the account returned, and on the first `account_create` afterwards, the second account is returned.

This would also make it consistent with `wallet_create` with a given `seed`.

**Comment by SergiySW** [comment]
It's returning last restored account. Makes sense

**Comment by guilhermelawless** [comment]
Yes, but wallet_change_seed only returns "success": ""

**Comment by guilhermelawless** [comment]
Would it make more sense to return, in both methods, the list of accounts restored instead of only the last one?

**Comment by SergiySW** [comment]
Impropved in https://github.com/nanocurrency/nano-node/pull/1718
