### ISSUE TITLE
Add important network statistics periodic UDP messages

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/nano-node#172]
It would be useful to tool developers to get updates on basic info from other nodes, at least:
- Block count
- Account count
- Time

**Comment by SergiySW** [comment]
May be also node version? So desktop wallet can check if new updates availabe

**Comment by HostFat** [comment]
@SergiySW and then someone will fake the node version and make a sybil attack :D

**Comment by SergiySW** [comment]
Trust only version from preconfigured peers xD

**Comment by zhyatt** [comment]
#2225

**Comment by zhyatt** [comment]
This has been covered in #2446 and other related PRs
