### ISSUE TITLE
Deprecate `payments_` RPC calls

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#1723]
Deprecate the following RPC calls ahead of removal in a future version:

- payment_begin
- payment_init
- payment_end
- payment_wait

Removing because they are not commonly used and other RPC calls provide better options for managing.

**Comment by SergiySW** [comment]
Deprecated with https://github.com/nanocurrency/nano-node/pull/1773 & wiki updates. For v20 plan is to disable deprecated calls without config.json modification
