### ISSUE TITLE
unchecked blockcount increases forever

### ISSUE THREAD

**Issue by udikantz** [nanocurrency/nano-node#1726]
Hello I want to re open [#645](https://github.com/nanocurrency/nano-node/issues/645) 
I am using a self built version of 18.0 RC1 , 
I am using a centos 7 dedicated with ssd ( SAMSUNG 970 pro) ,
INTEL CORE I9 processor, 100MB upload/download connection

the node appears to do a lot of work CPU is constantly over 100%, network is also high over 1MB upload and download constantly, and the unchecked blocks is constantly increasing,
the node seems to be in synch though

**Comment by wezrule** [comment]
We are aware of increased unchecked blocks due to various spam attacks recently. We are addressing the issue in #1724 by more aggressively purging unchecked blocks.

**Comment by zhyatt** [comment]
Closing out as solved with #1724 in V18
