### ISSUE TITLE
Provide a way to stop wallet from automatically processing receive blocks

### ISSUE THREAD

**Issue by waitforthetrombone** [nanocurrency/nano-node#1746]
Currently there appears to be no way to stop blocks (incoming transactions) from being automatically processed by the wallet. 

My accounts have been spammed with transactions and I'm unable to even use my wallet to send transactions for hours.

I'd rather leave these spam transactions as pending - even better a way to choose which transactions to accept would be great. or even a feature to enable /disable automatic processing of incoming blocks

**Comment by argakiig** [comment]
The way already exists, you can set the `receive_minimum` in the config.json to set the minimum amount you want it to auto receive for, and then anything else you want to receive below that minimum will need a manual block generated.
https://github.com/nanocurrency/nano-node/wiki/config.json and https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#receive

**Comment by waitforthetrombone** [comment]
Thanks, a way to change this from within wallet would be great but I'm sure you have other priorities.

Thanks again!
