### ISSUE TITLE
How to get block hash by index

### ISSUE THREAD

**Issue by viettienbk** [nanocurrency/nano-node#1755]
Hi guys,

I found the get_block api: https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#retrieve-block, but I don't have block hash.
So, how can I get block hash by index(1,2,3,..) or get raw block by index?

**Comment by renesq** [comment]
You are aware that indexes only exist on a per-account basis, not globally? Then you can use account_history with some optional parameters to achieve this objective

**Comment by viettienbk** [comment]
@renesq : I understood. Thank you.

**Comment by renesq** [comment]
Keep in mind that the "offset" parameter is quite undocumented, but exists for both `account_history` and `chain`

**Comment by viettienbk** [comment]
@renesq : what is "offset" parameter and how to use it?

**Comment by renesq** [comment]
It's just an additional parameter like "count" and It does skip blocks lower than the offset you set (not sure if it starts with 0 or 1). So it essentially does what you said in your initial post: get block hash by index.
