### ISSUE TITLE
account_representative_set RPC returns block of zeros instead of an error

### ISSUE THREAD

**Issue by lephleg** [nanocurrency/nano-node#1778]
Using the RPC call for [setting an account representative](https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#account-representative-set) results in a block consisted by zeros and not effect to the account. An error message should be displayed instead.

Looking at the code this seems to happen when the `block` passed to `wallet->change_async()` ([L641](https://github.com/nanocurrency/nano-node/blob/master/nano/node/rpc.cpp#L641)) is set to `nullptr`.

**Steps to reproduce the issue:**
Make an RPC call to the node passing the correct wallet_id and addresses:

```
curl -d '{  "action": "account_representative_set", "wallet": "EEE8B2EDC1BC212D6976AC80D7660F391B8410ADCC073A581E97BAD731B6F4C3", "account": "xrb_1whu5mc1kga34bhr85q8tdc9jpx6bw9n6x6ktdmtmap1iyj6optb1a53q5j5", "representative" : "xrb_1whu5mc1kga34bhr85q8tdc9jpx6bw9n6x6ktdmtmap1iyj6optb1a53q5j5" }' [::1]:7076
```

**Describe the results you received:**
The result received was:

```
{
    "block": "0000000000000000000000000000000000000000000000000000000000000000"
}
```

**Describe the results you expected:**
The result should be an error explaining what caused this:
```
{
    "error": "Block ended up as null for some reason blah blah"
}
```

**Environment**:
Nano node version: v.18
Ubuntu Docker 18.09.02~3 on 18.04

**Comment by SergiySW** [comment]
Should be fixed with https://github.com/nanocurrency/nano-node/pull/1779 (v19)
