### ISSUE TITLE
Do not rewrite config.json on node boot

### ISSUE THREAD

**Issue by jcraigk** [nanocurrency/nano-node#1781]
Currently on successful boot, the server rewrites the `config.json` file.  I noticed this initially when slashes in the `callback_target` option appeared after boot.  Another issue I noticed is that it rewrites an empty JSON hash `[]` as `""` in `work_peers`.

This pattern of a daemon rewriting its user-provided configuration file on boot is foreign to me but I don't do a lot of systems programming.  Are there examples of this pattern that can be cited?  What is the reasoning behind this behavior?

In order to have sane debugging around node configuration, I've added a layer of templating to `config.json` in my Docker setup so I can see the changes that the server applies when it boots.  This is an extra layer of debugging that should not be necessary.  If there is not a strong justification for the current behavior, it should be changed such that the server only reads from `config.json` and never writes to it.

**Comment by zhyatt** [comment]
When a node is first started the config is read and parsed, any upgrades to the config are performed, and then the config is written back to disk. When new options are added they are initialized with default values, still relevant existing values will remain. When you see what looks like a rewrite, your example being work peers, that is most likely related to using boost ptree as a json library which we are looking into improving. Please see #499 for further tracking related efforts. Also related to #526.

**Comment by jcraigk** [comment]
@zhyatt thanks for the response.  Could my questions about why the rewriting is done at all be addressed?  Examples of other software that does this?  It is a confusing anti-pattern imo and represents a barrier for developers to run nodes.

**Comment by think4sec** [comment]
I made a comment about using "config.json" as an override file for the internal defaults in issue #1792. I agree, software shouldn't write changes to config file unless instructed to by admin.

**Comment by cryptocode** [comment]
https://github.com/nanocurrency/nano-node/issues/1871 will fix the JSON formatting issues

**Comment by zhyatt** [comment]
Related to #1878

**Comment by cryptocode** [comment]
Fixed by transition to TOML
