### ISSUE TITLE
Return consistent JSON payloads in RPC responses

### ISSUE THREAD

**Issue by jcraigk** [nanocurrency/nano-node#1783]
This is related to https://github.com/nanocurrency/nano-node/issues/1782

Currently, responses to RPC commands are not standardized.  For example, a successful call to `bootstrap_lazy` returns the JSON payload `"started": "1"` while the call to `bootstrap` responds with `"success": "" `.  This makes it difficult to build standardized parsing mechanisms around Nano RPC responses.  See the one-offs in these RPC wrapper helper methods as an example of the type of logic required to get the parts we care about from the responses in an ergonomic way: https://github.com/jcraigk/ruby_nano_rpc/blob/master/lib/nano_rpc/helpers/wallet_helper.rb

Each JSON response should have a predictable and standardized set of keys.  I don't think we need to adopt a full opinionated framework like `JSON-API` but I do think having standardized keys makes sense.

I propose that we should allow only `error` and `data`, both optional in the case of a successful (status 200) response.

For a successful response where no data needs to be returned, `HEAD 200` (no body) should be returned.

`error` should be blank or may be omitted from successful (status 200) responses.  For non-200 responses it should contain a human readable error message as descried in the Issue linked above.

`data` may be omitted from unsuccessful (non-`200` status) responses.  For successful responses, it should contain the data associated with the request, such as account addresses or balances, etc.  These can be nested inside their own keys in the `data` object.

Note that keys themselves should always be predictable and static per command; only values should be dynamic.

There may also be an argument for adding a success message as its own key, but probably lower priority.

If this is implemented and backwards compatibility is desired, then versioning should be applied to the RPC interface (a pattern that is probably desirable for the longterm anyway).  This should be "v2".  I suggest using paths to separate versions instead of adding a header or POST param; so all request paths would begin with "/v2/".

**Comment by zhyatt** [comment]
Related to #499

**Comment by cryptocode** [comment]
https://github.com/nanocurrency/nano-node/issues/1782 covers HTTP status codes
https://github.com/nanocurrency/nano-node/issues/1871 covers JSON formatting issues
