### ISSUE TITLE
Failed to import wallet

### ISSUE THREAD

**Issue by udikantz** [nanocurrency/nano-node#1799]
Hello,
I am using latest node release self built on centos 7,

When executing wallet_import command I am getting a strange error massage, 
how ever after getting the error massage I am executing the wallet_list command and I see the "failed imported wallet" listed under the wallet_list

here is the error massage: 
```

nano_node: /home/leetz0rd/latest_node/nano_build/nano/node/wallet.cpp:580: bool nano::wallet_store::import(const nano::transaction&, nano::wallet_store&): Assertion `valid_password (transaction_a)' failed.
Aborted
```

**Comment by SergiySW** [comment]
Wallet you import to shouldn't have password (you can change to empty password before import I guess, after import change again)

**Comment by udikantz** [comment]
I am using the command as described in the docs:

`./nano_node  --wallet_import --file=/home/crypto/nano/data/backup/<old wallet>.json  --wallet=<new wallet> --password=<old wallet password> --data_path=/home/crypto/nano/data18/`

**Comment by SergiySW** [comment]
If your new wallet has password, then you cannot import old wallet json

**Comment by udikantz** [comment]
I see, the new wallet indeed had password prior to import.
Strangely after getting the error, I am seeing the imported wallet as if it was imported correctly.

**Comment by SergiySW** [comment]
It seems during import temporary wallet with random id was created. It should have all json content including keys & seed encrypted with json password. Because you are using Debug build, process was cancelled with assert & temporary wallet remains
Should be more clear with https://github.com/nanocurrency/nano-node/pull/1800

**Comment by udikantz** [comment]
Thank you for the answers,
I did not know i was using debug build, are there instruction to build the node for production?

**Comment by SergiySW** [comment]
Add to cmake options
-DCMAKE_BUILD_TYPE=Release

**Comment by SergiySW** [comment]
Bug should be fixed in v19/master with https://github.com/nanocurrency/nano-node/pull/1800. Returning explaining message if new wallet is encrypted with different password
