### ISSUE TITLE
Making universal blocks resistant against accidental burns when miscalculating the balance

### ISSUE THREAD

**Issue by renesq** [nanocurrency/nano-node#1832]
To date, at least three accidental coin burns happened due to an incorrect calculation of the new block balance. In order to fix this issue once and for all, I propose ditching the "_universal_" block, and dividing it into 2 or 3 different _state_ block types, each with their own block header preamble  (currently, all state blocks have the 0x6 preamble). 
Another advantage would be to have meaningful block types again, as some developers apparently are overwhelmed by the inner workings of universal blocks. It may also help eradicating the 'link_as_account' kind of stuff. 

Colin once said:

> Hopefully once we get epochs all out we can make a new “v1 genesis” which doesn’t have any of the old block types. Well see. It’d be nice to clean that all up.

So apparently, there even seems to be a solution on how to implement stuff like this retroactively?  

Determining the block purpose solely based on the 'balance delta' was a bad idea in the first place. So let's at least keep in mind that there is a solution to the problem, even if it would require a bit of effort. I'm aware that the miscalculation is rather an edge case, but at least we can discuss the issue. Obviously, only services and wallets that do their own balance calculations are at risk. As far as I know, some node-internal race conditions have been fixed, or at least the wallet servers have added countermeasures some months back (I remember NWC and Canoe being affected), but the issue still happened afterwards. 

~~I also have a small _hotfix_ in mind: When using the "process" command, add a "is_send" flag check, so the node will halt the block processing in case someone does not want to send anything. ~~

**Comment by SergiySW** [comment]
About hotfix: there is subtype in v18 https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#optional-subtype

**Comment by renesq** [comment]
I see 😅 That leaves us with a discussion about block types in general, which I presume will be deemed too much effort to change at this point.

**Comment by cryptocode** [comment]
> I propose ditching the "universal" block, and dividing it into 2 or 3 different state block types, each with their own block header preamble (currently, all state blocks have the 0x6 preamble).
> Another advantage would be to have meaningful block types again
> ...
> Determining the block purpose solely based on the 'balance delta' was a bad idea in the first place.

The purpose of the protocol-level state block is just that - to record account state. What transition caused the state change, and how to represent it (sent, receive, etc) is an API level discussion IMO. No new block types should be needed. For instance, a send can also be a rep change. The RPCs have been improved, once example noted above.

**Comment by SergiySW** [comment]
Also possible to add some 8 bit subtype field than different headers (and height field & probably some other if change it anyway). But it requires hash calculation change while headers update is somewhat easiers

**Comment by renesq** [comment]
If we want to do all of this on an API level, we should have a clear definition of subtypes. 

Apparently, there are send/receive/open/change/epoch subtypes as defined in the #1704 PR. 
We could even go as far as disallowing a rep change at the same time as sending/receiving, so there is no ambiguity involved? Does the ambiguity even matter?

**Comment by clemahieu** [comment]
I think one thing that would improve this is to change our documentation to state that people should be building block n+1 based on block n, which is entirely possible with state blocks. The problem these burn situations emerged from was when they're calling RPCs to separately pull this information and with a race condition it got out of sync.

The documentation was written when state blocks weren't around so maybe another pass would be the most helpful.

**Comment by renesq** [comment]
So here's the definition according to my knowledge:

subtype Send: if balance is smaller than previous block's balance (may still include a representative change)
subtype Receive: if balance is bigger than previous block's balance (may still include a representative change)
subtype Open: if "previous" is zero 
subtype Change: if balance is the same as previous block's balance
subtype Epoch: if link is epoch link

I'll close this issue now as it is a non-issue by now. Will reopen it if we ever revamp the whole Network

**Comment by cryptocode** [comment]
@renesq Looks about right. Note that Change's link must be zero.
