### ISSUE TITLE
Migrate config.json to reference and override files in TOML format

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#1878]
This ticket is an overview of the plans for upgrading the configuration file from a single config.json to reference and override files in TOML format. The following updates are in scope:

- Creation of a TOML file containing default configuration values for reference (not used by the node)
- Creation of a TOML file for updating with override configuration values
- Node will validate override file when attempting to load and return errors for any improper formatting or out of scope settings/values
- Node will not write to any configuration file during operation
- Addition of CLI commands for dumping reference and currently loaded override configuration files
- Upgrade path for converting existing config.json file to override TOML file

**Comment by jcraigk** [comment]
Was YML considered?  Just curious on thoughts around potential tradeoffs.

**Comment by cryptocode** [comment]
YAML was indeed considered and it was a close race. We use YAML for the protocol spec and are familiar with at least some of the tradeoffs. YAML is a complex spec and parsers have a history of issues with getting the fine points right, and there are some usability issues.

In short, TOML seems more end-user friendly as a config format; editing a simple ini-like format is easier to get right than having to deal with issues like invalid indentation. This is a semantics question as well as syntax. This is especially relevant when you have user-override files - replicating the config indentation is error prone.

We also want to be generous with multiline comments, and I think that works best in a format that doesn't enforce indentation. It's also used by other crypto projects, like Ethereum.

**Comment by zhyatt** [comment]
@cryptocode Keep in mind https://github.com/nanocurrency/nano-node/pull/1733 with the config file changes

**Comment by cryptocode** [comment]
Closed by #2221
