### ISSUE TITLE
Show active network in RPC version

### ISSUE THREAD

**Issue by guilhermelawless** [nanocurrency/nano-node#1884]
Suggestion to show "network": "live/beta/test" in [version](https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#retrieve-node-versions)

**Comment by clemahieu** [comment]
We might reset the beta network genesis hash at some point, maybe we should display the first 4 digits of the genesis hash.

**Comment by guilhermelawless** [comment]
Closed by #2184
