### ISSUE TITLE
RPC call steps for send payment to other account

### ISSUE THREAD

**Issue by tundak** [nanocurrency/nano-node#1925]
I am new with nano and testing RPC calls on nano testnet. what are the steps to send nano to other account ? i hardly found steps i am following reference https://www.nanode.co/docs but in last it says  `"error": "This block cannot follow the previous block"`

Can i have any proper document steps for send payment ? any help or reference appreciates.

**Comment by guilhermelawless** [comment]
When you do RPC `block_create` those docs (they are **outdated**) specify to use the type `send`. Those types are no longer possible after [epoch blocks ](https://medium.com/nanocurrency/an-epoch-blocks-explainer-aa22905b28db) were introduced. Now you must send `state` blocks. Read more on state blocks here: https://github.com/nanocurrency/nano-node/wiki/Universal-Blocks-Specification

In general you be following this page, it is always up-to-date: https://github.com/nanocurrency/nano-node/wiki/RPC-protocol

**Comment by tundak** [comment]
I have followed your above reference and prepare some sequence for payment on testnet:
let me know if i am wrong ?

```
Genesis wallet: 5FA5DA241766F0D45C95A3BD68537D3F812C4FCE6BDA24B7512164B7A5DA4767
source Account :xrb_1qrd4f3kcmmdmp1jgm3toq4sqr5k6x1b9wesrj8efg4zod19hu8iph8f59nw 
destination: xrb_1nebc1rr8zdyhnzujsysdngz8imfsyia4p7sin8qehybgtkasu886hpggww4
```


Step1: Send Block request:

```
{  
  "action": "send",  
  "wallet": "5FA5DA241766F0D45C95A3BD68537D3F812C4FCE6BDA24B7512164B7A5DA4767",  
  "source": "xrb_1qrd4f3kcmmdmp1jgm3toq4sqr5k6x1b9wesrj8efg4zod19hu8iph8f59nw",  
  "destination": "xrb_1nebc1rr8zdyhnzujsysdngz8imfsyia4p7sin8qehybgtkasu886hpggww4",
  "amount": "10000000000000000"  
}

Response:
{
    "block": "D18F2DD283759170345D381A4F4841E098610BBC07370374E76FD40D3DB83A4A"
}
```


Step2: Prepare open block as:

```
Request:
{
    "action":"block_create",
    "type":"open",
    "account":"xrb_1qrd4f3kcmmdmp1jgm3toq4sqr5k6x1b9wesrj8efg4zod19hu8iph8f59nw",
    "representative":"xrb_1qrd4f3kcmmdmp1jgm3toq4sqr5k6x1b9wesrj8efg4zod19hu8iph8f59nw",
    "balance":"10000000000000000",
    "link":"D18F2DD283759170345D381A4F4841E098610BBC07370374E76FD40D3DB83A4A",
    "wallet":"5FA5DA241766F0D45C95A3BD68537D3F812C4FCE6BDA24B7512164B7A5DA4767"
}
Response:
{
    "hash": "38ECEAA0B8E463478F77CC6E0B39992BBAF4CCFCC2C8EACC33303305397B7E61",
    "block": "{\n    \"type\": \"open\",\n    \"source\": \"D18F2DD283759170345D381A4F4841E098610BBC07370374E76FD40D3DB83A4A\",\n    \"representative\": \"xrb_1qrd4f3kcmmdmp1jgm3toq4sqr5k6x1b9wesrj8efg4zod19hu8iph8f59nw\",\n    \"account\": \"xrb_1qrd4f3kcmmdmp1jgm3toq4sqr5k6x1b9wesrj8efg4zod19hu8iph8f59nw\",\n    \"work\": \"6f368c0abd720658\",\n    \"signature\": \"BBAB7665D763D199CF0D6853698561612E4C3210E27F58C2BE14D9DA872CE4A69C52B7BD6C0C1022DB289503C83E454A2E093CE56C283E8945CB415B9E907007\"\n}\n"
}
```


Step3: Receive the block

```
Request:
{  
  "action": "block_create",  
  "type": "receive",
  "wallet":"20F2B302FE32368EC75EB18A0FFDA45C3D87A94E288A8F195E0F686D9F1F285A",
  "account": "xrb_1nebc1rr8zdyhnzujsysdngz8imfsyia4p7sin8qehybgtkasu886hpggww4",   
  "source": "38ECEAA0B8E463478F77CC6E0B39992BBAF4CCFCC2C8EACC33303305397B7E61",   
  "previous": "D18F2DD283759170345D381A4F4841E098610BBC07370374E76FD40D3DB83A4A"
}

Response:
{
    "hash": "0961DCD32D1E17D03287E042FCDACF84978CDAC5572A95873B20B4F438757D53",
    "block": "{\n    \"type\": \"receive\",\n    \"previous\": \"D18F2DD283759170345D381A4F4841E098610BBC07370374E76FD40D3DB83A4A\",\n    \"source\": \"38ECEAA0B8E463478F77CC6E0B39992BBAF4CCFCC2C8EACC33303305397B7E61\",\n    \"work\": \"251af11e19d95eca\",\n    \"signature\": \"97E78087348EE98ED477C8D5F9DC06BD453CDED5E81611096C2497058AF1958C0BD03F545DF32145AE4562226F33D3F3533727DCE136C9DBE0D27A796DE95105\"\n}\n"
}
```


Destination account balance:
```
Request:
{  
  "action": "account_balance",  
  "account": "xrb_1nebc1rr8zdyhnzujsysdngz8imfsyia4p7sin8qehybgtkasu886hpggww4"  
}
Response:
{
    "balance": "0",
    "pending": "20000000000000000"
}
```


Destination account info:
```
{  
  "action": "account_info",  
  "account": "xrb_1nebc1rr8zdyhnzujsysdngz8imfsyia4p7sin8qehybgtkasu886hpggww4"  
}
Response: 
{
    "error": "Account not found"
}
```

Now there are few questions :
1. what is wrong in above process ?
2. why my destination account balance keep showing in pending ?
3. Why account info says account not found but balance shows pending balance ?
4. My source account representative is set itself but destination account not set any representative, is this can be reason for pending balance ?

**Comment by guilhermelawless** [comment]
`block_create` does not process the block, you need to use RPC `process` afterwards. On the other hand, `send` already does everything, so that's why you see the amount pending.

Another, easier way of dealing with this is adding the destination account to a local wallet. Then, the node will see that there is a pending block and generate the receive (in this case open) block.

And once again, if you insist on using `block_create` you should be using `state` blocks. With them you can do open+receive+change in the same block, so you can immediately set your representative in the open block.

**Comment by tundak** [comment]
Thanks for your suggestion, i am able to transfer coins in my local wallet between accounts. steps i did follow :
Step1: [Offline signing (create block) ](https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#offline-signing--create-block) using my source account

Step2: [Process block ](https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#process-block) using my source account

Destination account nothing to do in this but destination account now active and show balance and receive block...

What if my both account on separate node ? what steps i will need to follow to receive balance in that case ? @guilhermelawless

**Comment by guilhermelawless** [comment]
Perform the same steps, offline + process on the receive node.

**Comment by tundak** [comment]
Thanks, i did submit send block on genesis node, but before process any receive block,  log keep saying `[2019-04-29 15:34:57.472448]: 1 blocks have been unconfirmed averaging 92 announcements` i am having just 2 node for now, 1 genesis and other receiver. where i should debug this ?

**Comment by guilhermelawless** [comment]
You're creating another network. If you want to test Nano use the beta network.

**Comment by tundak** [comment]
sure, i will test with nano beta network, hence i was expecting answer for `unconfirmed blocks.`

**Comment by renesq** [comment]
If the node already knows a private key for the receiving account, you normally do NOT have to manually generate an open block or a receive block, the node will do that for you as long as the sent amount exceeds 10^24 raw by default. Also, "receive" and "open" blocks are deprecated. Use state blocks instead. If you don't use the block_create command, the node will take care of all of this.
