### ISSUE TITLE
Order accounts and ledger by balance

### ISSUE THREAD

**Issue by HostFat** [nanocurrency/nano-node#2]
By clicking on "Balance" it would be good if it will order all the accounts by balance (the same on the tab ledger)

![image](https://cloud.githubusercontent.com/assets/644416/14670787/d8cb8440-06ee-11e6-934f-205b64b5b613.png)

**Comment by mikerow** [comment]
You can actually sort it by balance/txs count: https://raiblockscommunity.net/page/frontiers.php

Or for representative weight: https://raiblockscommunity.net/page/representatives.php

These are online-non official tool, but do the job.

**Comment by mikerow** [comment]
The future of the main wallet will be to be only a CLI rai_node. This feature can be closed.
