### ISSUE TITLE
Add optional to confirmation_history rpc for all blocks

### ISSUE THREAD

**Issue by schenkty** [nanocurrency/nano-node#2020]
Based on the conversation with @argakiig on discord beta-net, I understand that confirmation_history does not include every block based on confirmation height or something. I would like an optional on the confirmation_history rpc where if provided it includes the last 2048 of all blocks not the optimized version. 

Thanks,
Ty

**Comment by zhyatt** [comment]
#2049 provides the most reasonable approach for being able to capture all blocks through confirmation_history by allowing a configurable count of blocks to return.
