### ISSUE TITLE
Core Dump issue

### ISSUE THREAD

**Issue by tundak** [nanocurrency/nano-node#2032]
Testing on betanet, build from master with commit number `939c30df155da4d77d9d88f8380dcb6b78a30792` on ubuntu 18.04, boost 1.67.0, while start node and did a tx 

```
Assertion (!error) failed /root/nano-node/nano/node/active_transactions.cpp:361
Aborted (core dumped)
```

**Comment by wezrule** [comment]
Looks like the active difficulty is somehow below the publish threshold. From @argakiig how did you send the tx, did you use the wallet, or `block_create`? Any other details would be useful as well, thanks.

**Comment by tundak** [comment]
I did use RPC for tx, `config.json` having `"max_work_generate_difficulty": "ffffffffc0000000",` it was using `"action":"block_create"` and` "action": "process"` . what else details need to provide ?

**Comment by argakiig** [comment]
when you did block create did you specify a work value? if so what was the hash you used for the generate_difficulty hash?

**Comment by tundak** [comment]
I didn't mentioned work in `block_create`, this auto generate work and return response. same response i did process using `"action": "process"`

for open block i am using previous has of sender account's `block_create` tx.

**Comment by guilhermelawless** [comment]
Maybe a minimum can be added here for sanity https://github.com/nanocurrency/nano-node/blob/7a106b1f145dcc8b75f325b1acb9b675127b050d/nano/node/active_transactions.cpp#L488

Perhaps the lower difficulty can come from line https://github.com/nanocurrency/nano-node/blob/master/nano/node/active_transactions.cpp#L488

**Comment by argakiig** [comment]
Can you provide the rpc you used, and the response? Please edit out any private keys @tundak

**Comment by tundak** [comment]
I need to reproduce it for RPC & response.. hence this returned valid response when i did try..
