### ISSUE TITLE
confirmation_quorum details on node

### ISSUE THREAD

**Issue by tundak** [nanocurrency/nano-node#2065]
I am using RPC call `confirmation_quorum` and getting response. In response there is `peers_stake_total`, I am bit confused 
1. what is this `peers_stake_total` for ? 
2. how `peers_stake_total`  value impact to block confirmation ?
3. how `peers_stake_total`  value define for node ?
4. Is  `peers_stake_total`  same for all nodes across the network ?

**Comment by renesq** [comment]
Peers are the nodes you are directly connected to. Every participant most likely has a different peer list. The `peers_stake_total` is the cumulated representative weight those peers bear. As far as I know, The number is listed "for your interest". What's probably more interesting of a metric though is `online_stake_total` because it's used to calculate the actual `quorum_delta` (the minimum voting tally required to be deemed confirmed) by being multiplied by `online_weight_quorum_percent`/100

**Comment by tundak** [comment]
@renesq thanks for your response, I need some paid consultation on a issue. I hope we can get in touch. Please ping me on `sonu5650@gmail.com` or share me details.

**Comment by tundak** [comment]
related issue with above query: i have joined betanet from local PC node and this keep saying for blockinfo `"confirmed": "false",` but i did join the network from cloud server machine and same blockinfo `"confirmed": "true",`

I am bit confused because of this difference. why local confirmed is `false`.

**Comment by wezrule** [comment]
Blocks are confirmed after an election of the block itself or an election for a block higher up the account chain (which can also happen for receive blocks on another chain). This happens naturally from live transactions or a background confirmation update process. If you explicitly want to confirm a block then call the `block_confirm` RPC command. Not sure what version you are using, but there may be an issue for some nodes with confirm requests in RC3.

**Comment by tundak** [comment]
Not sure, tested on 2 local PC with different IP, both having same issue `"confirmed": "false",` for blockinfo hence 2 cloud server working fine. `"confirmed": "true",`
Is this something related to` "allow_local_peers": "false", // To allow local host peering`  working with RC3.

**Comment by zhyatt** [comment]
@tundak This shouldn't be related to the `allow_local_peers`. I would recommend trying with RC4 or upcoming RC5 on beta and verifying you have enough `peers_stake_total` to confirm blocks. You should then see those unconfirmed blocks get confirmed, and if they aren't currently, they should be resolved after call `block_confirm` as wezrule indicated.

**Comment by zhyatt** [comment]
@tundak Any updates available on this issue?

**Comment by zhyatt** [comment]
Closing due to no response.
