### ISSUE TITLE
Create websocket subscription for active_difficulty changes

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#2080]
Currently the [`active_difficulty`](https://docs.nano.org/commands/rpc-protocol/#active_difficulty) RPC must be polled to monitor changes in work difficulty seen on the network. To assist integrations managing work generation efforts external to the node, add a new websocket subscription for `active_difficulty`.

This requires creation of a new observer set that would monitor and fire notifications with each cycle of difficulty changes (16-36sec depending on network conditions). These notifications should include the same details as found in the [`active_difficulty`](https://docs.nano.org/commands/rpc-protocol/#active_difficulty) RPC - `network_minimum`, `network_current` and `multiplier`.

A single subscription without additional options for this should work.

**Comment by zhyatt** [comment]
@guilhermelawless

**Comment by zhyatt** [comment]
Thanks for offering help on this @chrislinegar.

**Comment by chrislinegar** [comment]
Hi @guilhermelawless, I've submitted a PR with a first pass at this: https://github.com/nanocurrency/nano-node/pull/2091

I couldn't add a reviewer on the PR though, is this something you'd be able to have a look at?

Thanks in advance!

**Comment by zhyatt** [comment]
Solved with #2091 and #2109
