### ISSUE TITLE
RPC: Wallet not found (Version 18.0)

### ISSUE THREAD

**Issue by EminBudak** [nanocurrency/nano-node#2084]
`./nano_node --version
`Version 18.0

I created a nano wallet with cli command 
`./nano_node --wallet_create
`

then I call wallet_list and I show created wallet id.
`./nano_node --wallet_list
`

but when I try to call RPC command wallet_balance_total it gives an error
```
{
  "action": "wallet_balance_total",
  "wallet": "........."
}
```
```
{
  "error": "Wallet not found"
}
```

Then I restarted node but nothing change I have a wallet but RPC command gives an error. "Wallet not found"

**Comment by renesq** [comment]
Restart the daemon after using wallet-altering CLI commands. I strongly recommend RPC commands whenever you are altering a wallet.

**Comment by EminBudak** [comment]
I killed node with this command then I started again but nothing change
`sudo pkill -9 -f nano_node
`

**Comment by renesq** [comment]
Then you probably mistyped the Wallet ID or worked on a different data directory. Keep in mind that Wallet ID is not the same as a seed - it's an arbitrary API key that is defined by the node. Do you get the same error when creating wallets via RPC?

**Comment by EminBudak** [comment]
When I created a wallet with RPC I can get balance with RPC command. 
But when I call CLI command wallet_list I cannot show created wallet id.

I use custom data dir 
`./nano_node --daemon --data_path=/home/admin/.nano`

**Comment by guilhermelawless** [comment]
Are you doing all commands with the `data_path`? Including running the daemon? You could be accessing different wallet databases on CLI and RPC

**Comment by EminBudak** [comment]
hımm I didn't call CLI commands with datapath so it created wallet id in the default folder. I create a wallet with data_path and it fixed. Thank you.
