### ISSUE TITLE
How to build node for windows from source code ?

### ISSUE THREAD

**Issue by kaluram8058** [nanocurrency/nano-node#2098]
I was looking into documentation for building windows node from source code, documentation is not clear and confusing. can someone share me step by step instruction for it ?

**Comment by cryptocode** [comment]
I recommend joining https://discord.gg/dzamDY which has a helpful #development channel for this type of questions. Post your question there with as much detail as you can (compile errors and such) and we'll help you through any issues.

**Comment by cryptocode** [comment]
This was moved to Discord, @guilhermelawless is already on it.
