### ISSUE TITLE
Suggestion: allow docker container to die when broken

### ISSUE THREAD

**Issue by ksemaev** [nanocurrency/nano-node#2123]
Guys, why do we have those hacks in place: https://github.com/nanocurrency/nano-node/blob/master/docker/node/entry.sh#L67-L76 ?

We ususally want the docker container to die, if something went wrong, it's compose/kubernetes/openshift job to restart dead processes (or do anything else with it if needed). 

Was this part done because of some non-resolved application hanging issues?

**Comment by argakiig** [comment]
part of #2160

**Comment by argakiig** [comment]
see not on #2172 for why this was done

**Comment by argakiig** [comment]
closed with #2160
