### ISSUE TITLE
v19 initialization error

### ISSUE THREAD

**Issue by tiagocanto01** [nanocurrency/nano-node#2153]
Whenever I try to open version 19 this error is showing up:

"Exception while running wallet: open: Too many open files"

I tried to delete the entire database and started up again. It worked! But after closing the application and trying to open it again the error returned.

I'm using the macOS release

**Comment by cryptocode** [comment]
For now a workaround is needed as macOS has a very low default file descriptor limit, and v19 uses more of them after the move to TCP. The way to increase the limit depends on specific macOS version, but some people had success with the recipe in https://superuser.com/a/1171028

**Comment by zhyatt** [comment]
@tiagocanto01 Were you able to implement the workaround?

**Comment by zhyatt** [comment]
Closing out due to no response.
