### ISSUE TITLE
Allow option to disable incoming bootstrap requests

### ISSUE THREAD

**Issue by arranHarty123** [nanocurrency/nano-node#2165]
A configuration setting that would allow nodes to disable incoming requests for bootstrapping completely.

This would:
A, reduce the burden on PRs so they can focus on voting.
B, increase the value of the larger number of non PRs to help bootstrap.

By default I would expect allow_incoming_bootstrap to be enabled, but I would expect nodes that hold PRs to disable this.

**Comment by SergiySW** [comment]
https://docs.nano.org/commands/command-line-interface/#-disable_bootstrap_listener ?

**Comment by arranHarty123** [comment]
yeh that looks like it fits the bill. Not sure how easy this is to use with docker? i.e. pass through the command. Would having this as a config entry get around this problem?

**Comment by Srayman** [comment]
Shouldn't setting bootstrap_connections_max to 0 also accomplish the same thing?  Not sure what, if any, impact that has on the node bootstrapping from others, but according to the config.json docs it should prevent inbound connections.  One thing to consider maybe is adjusting this for PR's during heavy load to be more dynamic, allow up to the max under low load, but under heavy load reduce it down to 1-2 or 0 to allow the PR node to focus on voting.

"bootstrap_connections_max": "4", // Allowed incoming bootstrap connections count. Lower value save IOPS & bandwidth. 64 recommended for high-end fast nodes, 0 for HDD home users,

**Comment by arranHarty123** [comment]
As a follow up. Is disabling the listener exactly the same as setting count to 0? I wonder if the former is even more efficient.

**Comment by arranHarty123** [comment]
From chats on Discord, the allow_incoming_bootstrap should be possible to disable for docker users as well one integrated.

**Comment by SergiySW** [comment]
bootstrap_connections_max = 0 can also affect outgoing bootstrap speed. It's not more effective
Passing arguments to docker should be possible after PR https://github.com/nanocurrency/nano-node/pull/2160

**Comment by arranHarty123** [comment]
Thanks for clarifying. I'll close the issue and wait for the PR. It would be good to know if thats going to be in the next release.
