### ISSUE TITLE
mac os build error

### ISSUE THREAD

**Issue by kchals** [nanocurrency/nano-node#2167]
I ran shell script 
"sh util/build_prep/bootstrap_boost.sh -m"

but occured error like this 
./boost/atomic/detail/ops_gcc_x86_dcas.hpp:408:16: error: address argument to atomic builtin cannot be const-qualified ('const volatile boost::atomics::detail::gcc_dcas_x86_64::storage_type *' (aka 'const volatile unsigned __int128 *') invalid)
        return __sync_val_compare_and_swap(&storage, value, value);
               ^                           ~~~~~~~~
1 error generated.

How can i build complete?

**Comment by argakiig** [comment]
@kchals see https://github.com/nanocurrency/nano-node/blob/master/util/build_prep/macosx/prep.sh.in#L42-L44 please try again with flags being `-m -c` and if you desire to keep the archive `-k`
By default boost 1.67 is downloaded and built, but boost 1.69 can be specified as well using `-B 1.69`

**Comment by kchals** [comment]
Thank you for your answer.
I try to build add option 2case, "-m -c", "-m -c -B 1.69" but still not working.
first, "-m -c" option occurs same error. 
second, "-m -c -B 1.69" option occured error too. but log shown just this
...failed updating 1 target...
I couldn't find cause about build error.

Do you have another suggestion?
Do you have another recomman

**Comment by argakiig** [comment]
which version of clang do you have? `clang --version`

**Comment by kchals** [comment]
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

thanks

**Comment by argakiig** [comment]
can you gist the full error output and link it here?

**Comment by zhyatt** [comment]
@kchals Were you able to get your issue resolved?

**Comment by zhyatt** [comment]
Closing out due to no response.
