### ISSUE TITLE
Feature request: avoid cleaning of database

### ISSUE THREAD

**Issue by ksemaev** [nanocurrency/nano-node#2172]
When using docker containers the best recomendation is too make them run just one main process, spliting all logic to several microservices. But here we have this job in cycle: 
https://github.com/nanocurrency/nano-node/blob/master/docker/node/entry.sh#L52-L66

Is it really needed? What will happen if we won't do this cleaning and let DB grow? What is the point of this process?

**Comment by argakiig** [comment]
There was a time where the ledger could bloat rather heavily for no apparent reason. This was a work around to try and handle the ledger bloat and compact it when necessary. There haven't been any recent reports of this issue occurring recently. in #2160 the ledger compaction is addressed on startup if over size, and then will move on to normal operation

**Comment by zhyatt** [comment]
Closing with #2160 merged
