### ISSUE TITLE
Update node ID to use node_ instead of nano_ prefix

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#2181]
To avoid the potential for confusing the node ID value with a Nano address, since they currently have the same format, @BitDesert suggested in https://github.com/nanocurrency/nano-docs/pull/59 that we use `node_` as a prefix instead of `nano_`.

**Comment by zhyatt** [comment]
@SergiySW Is there any reason for us to not use `node_` as the node ID prefix?

**Comment by SergiySW** [comment]
We can make it with replace

**Comment by arranHarty123** [comment]
this caught me out as well

**Comment by zhyatt** [comment]
Resolved in #2191

**Comment by zhyatt** [comment]
Reopening until release
