### ISSUE TITLE
confirmation stats in socket message

### ISSUE THREAD

**Issue by schenkty** [nanocurrency/nano-node#2190]
It would be extremely helpful if confirmation stats such as duration and tally were added to the socket message when a block is confirmed. I have found the socket to be the most reliable option to capture block activity under heavy stress than really anything else. confirmation_history works but will slow down under stress due to the fact that you need to increase the confirmation_history size to capture everything needed. Great work on the socket, would love if it could be expanded to include those values. 

Thanks,
Ty

**Comment by clemahieu** [comment]
Makes sense since we’re trying to deprecate the confirmation_history method since it’s polled. 

We should make the additional data configurable since it’ll increase the web socket bandwidth usage.
