### ISSUE TITLE
Callback response misleading

### ISSUE THREAD

**Issue by arranHarty123** [nanocurrency/nano-node#2192]
[2019-Aug-03 13:49:04.666131]: Callback to <address:port> failed with status: Created

Potentially as 201 returned

**Comment by cryptocode** [comment]
Thanks for the report. To give more context from Discord: this is a mongodb microservice endpoint returning 201, probably along with a Location header entry for the document id. 201 should not be logged as an error.

**Comment by arranHarty123** [comment]
Yep. Looks like its 201 for created (see https://restheart.org/try.html)
