### ISSUE TITLE
Header 'Content-Type': 'application/json' not set in work peer requests

### ISSUE THREAD

**Issue by kilkelly** [nanocurrency/nano-node#2224]
**Description of bug:**
I was writing a script to act as a work peer, using Node.js and Express.js. I read from the docs that a work peer needs to act as a replacement for the `work_generate` rpc command. When I edited `config.json` to point to my work peer script I noticed that while the script was receiving POST requests when work was requested by the node, the JSON body of the request was empty.

After some debugging I worked out it was empty because the POST request didn't have the header `'Content-Type': 'application/json'` set and and as a result Express.js wasn't able to recognise the body content as JSON.

I added a fix in the script to manually add the header and then was able to parse the JSON body as expected.

**How to fix:**
Add a `'Content-Type': 'application/json'` header with each POST request to a work peer.

**Comment by guilhermelawless** [comment]
Thanks @kilkelly !
