### ISSUE TITLE
RPC commands over socket

### ISSUE THREAD

**Issue by schenkty** [nanocurrency/nano-node#2226]
Is there any possibility that the roc commands can be processed through the socket? I understand this was the idea behind the IPC but sockets are more common from an integration standpoint so more developers would be more comfortable with them. The socket has proven itself to be extremely stable under heavy stress where the rpc has consistently had issues under stress. 

- Ty

**Comment by clemahieu** [comment]
We're going to make a protobuf specification for a new set of RPC commands and language bindings can be generated using standard protobuf tools.
