### ISSUE TITLE
Assert during bootstrapping with RocksDB V20.0DB17 debug build

### ISSUE THREAD

**Issue by VenKamikaze** [nanocurrency/nano-node#2325]
Hardware: ARMv8 FireFly RK3399, 2GB RAM, USB3 SanDisk SSD using f2fs filesystem.
Linux Kernel 5.3.0 aarch64

Node V20.0DB17 cmake flags as follows:
cmake -DCI_BUILD=On -G "Unix Makefiles" -DACTIVE_NETWORK=nano_beta_network -DCMAKE_BUILD_TYPE=Debug -DNANO_ROCKSDB=ON

RocksDB is using a shared library as I was not able to get the static version compiled easily due to linking errors.

Config is mostly standard a few changes shown below that might be relevant:
[node]
bootstrap_connections = 4
bootstrap_connections_max = 24
io_threads = 6
[node.rocksdb]
enable = true

While running the node during bootstrapping I hit a couple of assertions, at the same point:

> Assertion (status.ok ()) failed /opt/benano/git/raiblocks/nano/node/rocksdb/rocksdb_txn.cpp:61

See my pastebin for full text for the assertions, plus the output of nano_node_crash txt files and stackdump:
https://pastebin.com/erL54BNK

Here's a pastebin of the log at the time of the crash texts/stackdump files:
https://pastebin.com/BKBr9hsB

Note: I'm not sure if the crash/stackdump was related to the assertion or not, might be separate.

Some more relevant notes:
I've got a script that starts the node and monitors MemAvailable from /proc/meminfo, as using RocksDB especially during spam or bootstrapping would tend to use all available RAM and cause out of memory killer to fire. This happened frequently with DB16. Seems to happen far less with DB17 but still occurred a couple of times during bootstrapping, that's what the 'Lowmem, found xyz' messages are about.

I/O load has been very high with DB17, reaching up to a 45 load average at times (but fluctuating a lot). This is higher than I noticed with DB16. I cannot rule out that I have some kernel driver/hardware issue, although I had no assertions in DB16 on a debug build too.

I mentioned this on discord in #beta-net - wezrule said:

> I wonder if we are writing so much that the memtables fill up and aren't flushed to disk quickly enough

 and mentioned to try a config option:
[node.rocksdb]
num_memtables=3

Once this bootstrap finishes, I will try bootstrapping again with memtables set to 3 to see if the asserts come up again (knowing that I'll probably have more Lowmem kills due to increased RAM usage). I will update this ticket whether the asserts happened again or not.

**Comment by VenKamikaze** [comment]
I didn't finish bootstrapping but instead stopped and restarted with the config change below:
[node.rocksdb]
num_memtables=3

I still hit assertions in rocksdb_txn.cpp:61:

**Comment by VenKamikaze** [comment]
Thanks for the reply. I've been busy lately, and only spending minimal time on this, but I'll try with those settings today. The asserts come up quite frequently so I should know how it goes after a couple of hours.

I was thinking back, and I've recalled that I did switch from Rocks to LMDB during for a (few?) of the "DB" releases. Since I can't recall exactly when I switched, maybe it would be worth me recompiling some earlier tags and re-running to see if I still hit asserts in the earlier releases - possibly the issue came up in DB16 or earlier but I didn't notice. I'll _try_ to find some time for this too.

**Comment by VenKamikaze** [comment]
No asserts so far with those config options, however my script watching LowMem has killed the node 4 times already. I'll leave it a bit longer, and then I'll look at tweaking the options.

**Comment by VenKamikaze** [comment]
I ran it for about 3 hours and had no asserts. I've started tweaking config options (reverting one option to default at a time and running for about 30 min to try to reproduce it), and have also started sync'ing from scratch again. So far no further asserts, which is a bit frustrating.
I am away for the next 5 days or so, so I won't be able to test this further for a while.

**Comment by wezrule** [comment]
Appreciate the feedback, thank you

**Comment by zhyatt** [comment]
@VenKamikaze Any further updates on this or can we close out now?

**Comment by VenKamikaze** [comment]
Haven't had time to look any more into this. Will close the ticket, if I hit this again I'll open another.
