### ISSUE TITLE
Installation Warning on OS X about being from an "unidentified developer"

### ISSUE THREAD

**Issue by pRizz** [nanocurrency/nano-node#235]
This occurs after moving the RaiBlocks program to the Applications folder and double clicking on it.

<img width="532" alt="screen shot 2017-12-16 at 4 36 26 pm" src="https://user-images.githubusercontent.com/3519085/34075003-f5fa7026-e27f-11e7-8113-1a486caf930b.png">

The workaround is to go to System Preferences -> Security & Privacy -> Open Anyways

<img width="780" alt="screen shot 2017-12-16 at 4 36 41 pm" src="https://user-images.githubusercontent.com/3519085/34075006-fa96bbd0-e27f-11e7-989d-6433d08108be.png">

This probably requires an authentic signing key registered with Apple to work and/or maybe it needs to go through their review process.

**Comment by clemahieu** [comment]
I’ll work on getting a signature. As another workaround you can right click the app in Applications and click open and it’ll allow you to manually open it.
