### ISSUE TITLE
replay and valid vote counts do not align with expectations

### ISSUE THREAD

**Issue by Srayman** [nanocurrency/nano-node#2421]
**Description of bug:**
While analyzing votes from the votes websocket I have noticed that votes from the same rep for the same block hash are often duplicated multiple times.  This is expected from the fanout, however it appears as though the vote_valid and vote_replay counts are not exactly accurate from stats->counters.  This also leads to the websocket producing extra votes when it should be skipping replay votes.

**Describe the results you received:**
After running the V20.0 node for about 6 hours it has confirmed 13,815 blocks through active quorum.  It is reporting a total of 16,575,829 votes (confirm_ack in) of which 14,365,862 are "vote_valid" and 2,209,967 are "vote_replay".

**Describe the results you expected:**
With 92 online representatives I would expect a max of 1,270,980 valid votes for 13,815 blocks and the remaining 15,304,849 as replay votes or votes for inactive blocks.  

In addition to the counters being off the websocket performance is poor at high load.  It would be nice to be able to filter out the actual replay or inactive block votes from the real votes that are used for active transactions.  I imagine it would be difficult to differentiate between old blocks that have already been confirmed and cases where the block has not arrived yet and the vote is stored in the vote cache.  Ideally the vote cache examples would be counted as valid once the block arrived but those that are duplicate or late votes after a block has been confirmed are counted as inactive.

**Comment by cryptocode** [comment]
The votes callback is marked experimental and work-in-progress and I don't think you can currently rely on the numbers it produces. https://docs.nano.org/integration-guides/advanced/#votes

Are you seeing websocket performance issues in general or just for votes? In my testing with confirmation callbacks under load, it has been performing very well, so any major slowdown could indicate a regression (it's tcp so the client has to keep up)

**Comment by Srayman** [comment]
Just the vote websocket from what I’ve seen so far with the increased number of messages it puts out compared to confirmations.  It likely could be on the client side.

I don’t think the websocket data is wrong, other than missing votes flagged correctly as replay votes, however that’s the issue mentioned here is the count for replay doesn’t seem right.

I’m not sure what trickle down effect their is besides the websocket data for valid/replay votes.

**Comment by guilhermelawless** [comment]
Identified as a minor bug, affects mostly stats and more votes going through the websocket than intended. Thanks!
