### ISSUE TITLE
Official wallet doesn't support decimals

### ISSUE THREAD

**Issue by frankh** [nanocurrency/nano-node#247]
I've been doing some testing send small amounts of XRB between the web wallet and the desktop wallet.

First i tried sending 0.000001 from web to desktop. It worked fine, except the desktop wallet shows the balance as 0 still and amount on the receive as 0. I thought fine maybe it just rounds down. I tried sending it back, and it sent a transaction sending 0.000000XRB back.

I tried the same process with 0.1 and got the same problem.

In the end i fixed it by going to advanced and changing the scale to xrb instead of Mxrb. Imo out of the box it should display enough decimal places when necessary

**Comment by XHyperY** [comment]
Advanced ->Scale -> Mxrb -> kxrb -> xrb   You can change the scale however you want.

**Comment by tnkmt** [comment]
Why is this? It's a very anti-intuitive.

**Comment by cryptocode** [comment]
@tnkmt Consider it a developer's wallet. A new one for mere mortals is underway - sign up for the beta on nano.co

**Comment by zhyatt** [comment]
Resolved by #1843
