### ISSUE TITLE
ERROR: Database size grew above 20GB

### ISSUE THREAD

**Issue by yanpl** [nanocurrency/nano-node#2483]
my nono node version is v19，now it out of sync blocks
when i view node log, i saw ERROR: Database size grew above 20GB (size = 21486669824)，
Has anyone else encountered this problem？

**Comment by guilhermelawless** [comment]
Please update to the [latest version](https://docs.nano.org/releases/node-releases/) - V20.0, and maybe see the [Docker entrypoint](https://docs.nano.org/running-a-node/docker-management/#docker-entrypoint-support) section for details, i.e. flag `-v SIZE_GB` to control the point at which a vacuum is performed.

Let me know if this fixes the issue for you.

**Comment by guilhermelawless** [comment]
Any updates on this? @yanpl
