### ISSUE TITLE
0 xrb is really <1 xrb : possible long-run currency depletion

### ISSUE THREAD

**Issue by slact** [nanocurrency/nano-node#249]
Accounts with a nonzero balance that is less than 1 xrb, the minimum value visible in the wallet (and on the raiblocks transaction explorer) show as having 0xrb.

Because the total number of XRB is fixed, this can lead to XRB depletion in the long run. As users delete old wallet keys with "0xrb" accounts, their <0xrb (>0raw) balances are forever taken out of circulation.

Some ways to address this:

For a send transaction that leaves the sending account with a balance of <0xrb, send a sum such that the remaining balance == 0xrb == 0raw. (This of course would make the "emptying" send of an account marginally more valuable than a "non-emptying" send)

Another way is to show xrb values past the decimal, or, as a stopgap, "<1" instead of "0".

**Comment by straightwhiteproud** [comment]
the wallet should just have an option to display raw units not just Mxrb kxrb and xrb

**Comment by slact** [comment]
That's a lot of units for people to keep in mind...

**Comment by cryptocode** [comment]
Displaying raw units are now supported.
