### ISSUE TITLE
Peering issue on V21 Beta

### ISSUE THREAD

**Issue by Srayman** [nanocurrency/nano-node#2516]
**Description of bug:**
Through V21 testing I have not seen Sev's node (b.repnode.org) in my peers list nor confirmation_quorum.  I grep'd my logs for his IP and did not find any sign of connections being established.

I ran some blocks and captured votes and I was getting a few votes from his node.  About 85% fewer votes than other PR nodes though.

I ended up adding his node to my preconfigured_peers list and it immediately connected, showed up in peers and confirmation_quorum and sending a few more blocks the votes from Sev's node matched in count to other PR nodes.

You can see the impact it has had on online stake below as it's missing his 19M weight.

{"quorum_delta":"43967934678792573660999999999999958300","online_weight_quorum_percent":"50","online_weight_minimum":"60000000000000000000000000000000000000",**"online_stake_total":"87935869357585147321999999999999916680"**,"peers_stake_total":"105524644557584066319000000024999750583","peers_stake_required":"60000000000000000000000000000000000000"}

The following are the first entries in my log to indicate a connection whereas other nodes had many more entries over the last few weeks.

[2020-Jan-26 20:33:05.902967]: Node ID handshake request sent with node ID node_1gj8s9dwcs1dd9cjggcqc3n86texcfd45ujuy68j9ydp7nwn4s3sty4t6sn3 to [::ffff:X.X.X.X]:54000: query 9B6D1EE446EC98D6FCDB79894FB42280F92108262B07CEEFB30453039916FD34
[2020-Jan-26 20:33:06.162949]: Node ID handshake response sent with node ID node_1gj8s9dwcs1dd9cjggcqc3n86texcfd45ujuy68j9ydp7nwn4s3sty4t6sn3 to [::ffff:X.X.X.X]:54000: query 309715D6EE45447570599C4E2A1B05E9662FE8C3C69E7730CBA49F62B7BA51E8

**Comment by zhyatt** [comment]
@Srayman We haven't been able to reproduce on our side. Have you seen this recently yourself?

**Comment by Srayman** [comment]
No, after restarting a few times after I reported this it started connecting and have not been able to reproduce.

**Comment by zhyatt** [comment]
Ok thanks. Closing this now but feel free to reopen if you run into it again.
