### ISSUE TITLE
Representatives Online RPC sometimes show all offline

### ISSUE THREAD

**Issue by Srayman** [nanocurrency/nano-node#2533]
**Description of bug:**
Occasionally pulling representatives_online shows no results and then it takes time for all online nodes to be populated.  This can produce undesirable results for checking the status of online representatives.

One suggestion would be to not clear the representatives list completely and instead track the last time I representative was checked and a response was received.  If it has been longer than a certain amount of time, then clear the one representative from the list.  This would also help with stability for any other processes that rely on using this list of online representatives.

**Steps to reproduce the issue:**
1. query representatives_online every 1 second continuously and record count
2. display when the count has changed

**Describe the results you received:**
1580663435.0289955 - Count: 100 - Previous Count: 99
1580663470.2241077 - Count: 101 - Previous Count: 100
1580663505.405167 - Count: 102 - Previous Count: 101
**1580663602.9015565 - Count: 103 - Previous Count: 102**
**1580663615.9555566 - Count: 9 - Previous Count: 103**
1580663616.9595563 - Count: 48 - Previous Count: 9
1580663617.9635558 - Count: 61 - Previous Count: 48
1580663618.9695566 - Count: 69 - Previous Count: 61
1580663619.975556 - Count: 72 - Previous Count: 69
1580663620.981556 - Count: 73 - Previous Count: 72
1580663621.9875557 - Count: 74 - Previous Count: 73
1580663622.990556 - Count: 77 - Previous Count: 74
1580663623.9975562 - Count: 89 - Previous Count: 77
1580663625.0035558 - Count: 90 - Previous Count: 89
1580663627.0125558 - Count: 92 - Previous Count: 90
1580663631.0315561 - Count: 93 - Previous Count: 92
1580663632.0365555 - Count: 94 - Previous Count: 93
1580663638.0720704 - Count: 95 - Previous Count: 94
1580663640.0825832 - Count: 96 - Previous Count: 95
1580663652.1447184 - Count: 97 - Previous Count: 96
1580663659.1807168 - Count: 99 - Previous Count: 97
1580663673.260259 - Count: 100 - Previous Count: 99
1580663701.4059355 - Count: 101 - Previous Count: 100
1580663750.66123 - Count: 102 - Previous Count: 101
1580663763.7247431 - Count: 103 - Previous Count: 102
1580663764.7307427 - Count: 104 - Previous Count: 103
1580663777.7983365 - Count: 105 - Previous Count: 104
1580663813.9997993 - Count: 106 - Previous Count: 105
1580663890.397483 - Count: 107 - Previous Count: 106
**1580663897.4359949 - Count: 108 - Previous Count: 107**
**1580663916.547232 - Count: 6 - Previous Count: 108**
1580663917.553233 - Count: 48 - Previous Count: 6
1580663918.5572317 - Count: 58 - Previous Count: 48
1580663919.5617452 - Count: 71 - Previous Count: 58
1580663920.5667465 - Count: 78 - Previous Count: 71
1580663921.5727458 - Count: 81 - Previous Count: 78
1580663922.577746 - Count: 82 - Previous Count: 81
1580663923.5827446 - Count: 84 - Previous Count: 82
1580663925.5057466 - Count: 85 - Previous Count: 84
1580663926.509745 - Count: 86 - Previous Count: 85
1580663928.5197444 - Count: 89 - Previous Count: 86

**Describe the results you expected:**
Variations in count should be minor and not reset completely to 0.  In the example above it took over 2.5 minutes to get back to 103 representatives online and this process runs every 5 minutes making it virtually impossible to get an accurate count of online representatives..

**Comment by guilhermelawless** [comment]
@Srayman are you able to verify the bug is solved in the develop branch?

**Comment by Srayman** [comment]
Ran the same script as earlier on beta and did not see any fluctuations in online reps count so seems to be resolved.  I ran it for 15 minutes and sent some blocks halfway through to see if that had any impact and reps online stayed consistent the entire time.
