### ISSUE TITLE
Error deserializing config: enable_control is not a boolean [V20]

### ISSUE THREAD

**Issue by locolupo** [nanocurrency/nano-node#2678]
I changed the configurations  parameter `enable_control` in `config-rpc.toml` from:

- `#enable_control = false` to
-  `enable_control = true`

Previously, upon starting the nano_node, I had received the following error:

`Error deserializing config: enable_control is not a boolean`

This error only seems to affect version 20. I performed tests on V18 and V19 with the old json configurations. I couldn't reproduce the erroneous behavior in those versions.

i've also tried to pass this parameter via cli like: `--config rpc.enable=true` but could not figure out how to do so.

Ubuntu 18.04.3 LTS
4.15.0-66-generic
plain binary no docker

thanks for your advise.

**Comment by Srayman** [comment]
Check to make sure there aren't any extra characters.  For example if you have a space after "enable_control = true " then it will result in this error.

**Comment by locolupo** [comment]
that's embarrassing, it was a whitespace after the `true`.  thank you
