### ISSUE TITLE
New "pow_difficult_req" message

### ISSUE THREAD

**Issue by Inkeliz** [nanocurrency/nano-node#2726]
I know that Nano was never intended to mitigate hard-fork. But, I think it can be mitigated with a new UDP/TCP message, like `DifficultReq` and `DifficultAck`.

------------------

That new two messages makes possible to an light-node get the current difficult of the network. My suggestion is that the message is:

**DifficultReq:**

- [32 Byte] Nonce
- [1 Byte] Algo (0x01 = Blake2b; For now, only blake2, but others if added more pow algorithms).
- [1 Byte] Block-Type (Optional? If NotABlock for the highest PoW difficult between all block-types)
- [16 byte] Value (Optional? 0x00...00 for the highest PoW difficult between all transactions-values)

**EDIT:** Seems that already have some ideas to set pow-difficulties based on the Block-Type (Send, Receive...) and based on the transaction value (1 RAW, 1 Nano, 1000 Nano). If Block-Type is NotABlock and the transaction is 0, we must consider the worse possible pow-difficult. There are also ideas to replace the current-pow algorithm. So, until the support is dropped (and I think all must be supported forever), the client can request the pow-difficult based on the pow-algorithm that the client supports.

**DifficultAck:**
 
- [32 Byte] Public-Key (representative)
- [32 Byte] Nonce (same as requested)
- [1 Byte] Algo
- [8 Byte] Current Difficult
- [64 Byte] Signature (as similar to `Ed25519(key, message = "difficult_prefix || public-key || nonce || algo || current-difficult")`)

------------

The need of the nonce is to prevent reusage of old messages, since there's no time-stamp on nano network.

------------

That change makes light-nodes little bit more reliable since a new hard-fork for pow-change can be tolerated (with there's no epoch-block or already known epoch-block pattern). Also, if there's any future change to make PoW-Difficult dynamic by the nodes itself, that message can still be usable to get the current difficulties.

-------

The interactive-nonce may follow the same pattern of the #1813.

**Comment by guilhermelawless** [comment]
What about using the new telemetry message for this purpose?

**Comment by Inkeliz** [comment]
> What about using the new telemetry message for this purpose? If the difficulty was added, that is.

Telemetry isn't signed, far I know. Doesn't have nonce. Don't fix anything.

**Comment by zhyatt** [comment]
@Inkeliz The telemetry message should be getting signed per https://github.com/nanocurrency/nano-node/pull/2618 and they do include a timestamp as part of the response which could be used to ensure responses are fresh enough. Although we haven't published final documentation, there is a docs PR up for the telemetry you can browse here: https://github.com/nanocurrency/nano-docs/pull/231/files - this will likely get included in the docs soon. Does this cover your concerns?

**Comment by Inkeliz** [comment]
Kinda. I'm talking about the Nano Protocol, not RPC, so that documentation doesn't cover that. Also, the documentation didn't describe how the signature is generated (and how to verify them), but it's another topic.

---------

Seems that telemetry is an new feature of the protocol-version 18. I'm testing the TelemetryReq to version 17, but none of them reply, I take an look that the source code and doesn't found anything.

--------

There are some concerns:

1. How will the telemetry change in the next releases? If there's a need for new data to be added (or the removal of some data).

   My proposal aims to create a more reliable way to old light wallets broadcast to the network. If we keep changing the TelemetryAck, some old node could not parse that message and defeat all the propose. 

   If that message is supposed to change, we need to create a proper way to make it fully compatible. Which means, for instance, be: [TYPE-OF-INFORMATION][SIZE][INFORMATION-ITSELF] rather than just [INFORMATION-ITSELF]. I think you got the idea, so an old node can always parse the message and look for the "type" and skip to next information based on the size. Another alternative is that we can't remove any data (send empty data instead) and the timestamp and signature will always be the last two information (so the lasts 72 bytes is still the timestamp and signature, for instance). The alternative makes it fully compatible because the position of the data is always the same, so old nodes can parse the message and just ignore the new data.

2. Nodes can disable the telemetry data.

   Not an really big deal. Nodes can disable confirm_ack and frontier_req too, as I do. But, since it's just an information about the pow difficult, doesn't make so much sense.

3. How is the data signed? The key for the signature is the wallet-key (as of the vote;  the "representative-key") or the node-key (the handshake one)?

   If it uses the node-key is useless, we can't know how trusted that node is. The node can inform a high pow-difficult, then we need to go back where we are now. Today, to get the pow-difficult, we need to listen to multiple blocks, waiting for the votes, when trying to guess the difficulty of the PoW, but it's not perfect. Another option is trying to publish the block using many difficult possible or just set a high pow-difficult by default, slow but more future-proof. It's also may not work when pow-difficulty is different for each transaction-value or block type. I might edit the proposal to include at `difficult_req` package the values of `BlockType` and `Value`, so we can survive a bit longer if theses values are meaningful for the PoW.

The change of the nonce for timestamp seems reasonable since we can also cache the data.

-----------

I'm not taking so much into the code, the only description for the `TelemetryAck` is here (https://github.com/nanocurrency/nano-node/pull/2446), which doesn't include any clue about signature and no information about timestamp.

**Comment by wezrule** [comment]
1 - The data is both forwards and backwards compatible. The size is included in the header `extensions` field. New fields will be added at the end of the payload and the old nodes will just read up to the size that they know about. If we end up removing many response fields then it might warrant v2 telemetry message types, but we can go a long way before that happens.
2 - yep nodes can disable it easily with a `--disable_providing_telemetry_metrics` CLI option.
3 - It uses the node-key yes, and it cannot be trusted as you say, the node can reply with what ever value it wants, but isn't that the same with this DifficultAck?

There is no current documentation on the signing, it is being worked on. This function signs the message:
https://github.com/nanocurrency/nano-node/blob/13d05f3f6c1500afcbfd1d90689133fa6117bb87/nano/node/common.cpp#L1306

And this one verifies it:
https://github.com/nanocurrency/nano-node/blob/13d05f3f6c1500afcbfd1d90689133fa6117bb87/nano/node/common.cpp#L1318

Hopefully it helps.

**Comment by Inkeliz** [comment]
@wezrule I'll take a look.

---

I'm not following Nano for a while, so I'm bit outdated of the latest changes or proposals. It seems that the new difficult will be based on the block-type, and also suggestions for based on the tx-amount. If so, what difficulties will the `telemetry` inform? I think the `telemetry` will give the highest-minimum difficult (the pow-difficult of the send-block). Then, in that case, Nano MUST forever take the approach of the "receive-block" has 1/8 of the current pow-difficult. Otherwise, we break the compatibility from version 18+. Then, also, the tx-value can't be used for pow-difficult.

If there's a change of the PoW Algorithm, will a new parameter append? The proposal of @guilhermelawless, seems to add a new "pow-difficult" at "telemetry". Okay. But what happens with we had another pow-algorithm? Then, the `telemetry` will give the "pow-difficult" (of the Blake2) and also another "random-pow-difficult" (for any other algo)? Or, Nano will always hard-fork and breaks compatibility and never runs two algorithms at the same time?!

**Comment by guilhermelawless** [comment]
The existing approach is an epoch block. During the upgrade the node would have to accept both algorithms. I guess you could also accept the old algorithm at a very high difficulty, or similar, to maintain compatibility.

**Comment by guilhermelawless** [comment]
The existing approach is an epoch block. During the upgrade, the node would have to accept both algorithms. I guess you could also accept the old algorithm at a very high difficulty, to maintain compatibility?

**Comment by zhyatt** [comment]
Additional details about telemetry have been updated in the documentation. Hopefully this helps explain in more detail what to expect with V21 and how that might be usable for your solution @Inkeliz - https://docs.nano.org/protocol-design/networking/#node-telemetry

**Comment by Inkeliz** [comment]
I'm closing the issue since it has been add to "telemetry_ack" message.
