### ISSUE TITLE
Pending/Unpocketed vs "Sent -> Delivered -> Received"

### ISSUE THREAD

**Issue by qwahzi** [nanocurrency/nano-node#2812]
I still see a lot of newbie confusion on the topic of "pending" or "unpocketed" transactions, so I'd like to officially propose:

Sent -> Delivered -> Received

To match standard email and physical mail terminology. I think having the Nano Foundation lead the way on this change will help services make the change

**Comment by My1** [comment]
the question tho is where to differentiate between sent and recieved

**Comment by qwahzi** [comment]
Resolved in V23:

- https://github.com/nanocurrency/nano-node/issues/3411
