### ISSUE TITLE
[Feature request] Request old password before wallet password change

### ISSUE THREAD

**Issue by railocius** [nanocurrency/nano-node#282]
I think, it would be good, to request the old password, together with the new password when changing the wallet password.

You can argue, that you can only change the wallet password while it is unlocked, but I still think it is a better security practice! For example, in Windows, even when you are logged in as administrator, you need to enter your old password together with the new password.

For example, you have your ria_wallet running and some friend or co-worker decides to have some fun and set a new the wallet password, because the wallet is unlocked to be useful.

**Comment by rkeene** [comment]
I think this is more significant for the Desktop Wallet and not as significant for the node itself, let's only worry about solving this for the desktop wallet.

**Comment by zhyatt** [comment]
This is captured in the NWC desktop wallet list of issues here: https://github.com/nano-wallet-company/nano-wallet-desktop/issues/48. Closing.
