### ISSUE TITLE
Why nano-node V21.1 has many unchecked blocks

### ISSUE THREAD

**Issue by apufvqsp** [nanocurrency/nano-node#2866]
I have been running nano-node V21.1 in a docker container for more than two weeks. The running command is as follows: 
```
docker run --restart=unless-stopped -d \
  -p 7075:7075/udp \
  -p 7075:7075 \
  -p 127.0.0.1:7076:7076 \
  -v /data/nano:/root \
  --name nano \
  nanocurrency/nano:V21.1
```

config-node.toml configuration is as follows: 
```
[node.websocket]

# WebSocket server bind address.
# type:string,ip
address = "::ffff:0.0.0.0"
# Enable or disable WebSocket server.
# type:bool
enable = true

[rpc]

# Enable or disable RPC.
# type:bool
enable = true
```

config-rpc.toml configuration is as follows: 
```
# Bind address for the RPC server
# type:string,ip
address = "::ffff:0.0.0.0"

# Enable or disable control-level requests
# type:bool
enable_control = false
```

My problem is when I call `curl -H "Content-Type:application/json;charset= utf-8" -X POST --data'{"action": "block_count"}' http://127.0.0.1:7076/`, the returned information is as follows: 
```
{
     "count": "50889000",
     "unchecked": "1127398",
     "cemented": "47630401"
}
```

**Why are there so many unchecked, can anyone help me see how to fix this problem?**

**Comment by guilhermelawless** [comment]
This could be the case if you have a poorly connected node. Are you port forwarding 7075/tcp ?

The results of these commands would help identify that:

```bash
curl -H "Content-Type:application/json;charset= utf-8" -X POST --data '{"action": "confirmation_quorum"}' http://127.0.0.1:7076/

curl -H "Content-Type:application/json;charset= utf-8" -X POST --data '{"action": "peers"}' http://127.0.0.1:7076/ | wc -l
```

**Comment by apufvqsp** [comment]
Yes, now 7056/tcp has port forwarding, does the host where the nano docker container is located must have a public IP?

```
root@aa:~# curl -H "Content-Type:application/json;charset= utf-8" -X POST --data '{"action": "confirmation_quorum"}' http://127.0.0.1:7076/
{
    "quorum_delta": "30000000000000000000000000000000000000",
    "online_weight_quorum_percent": "50",
    "online_weight_minimum": "60000000000000000000000000000000000000",
    "online_stake_total": "60000000000000000000000000000000000000",
    "peers_stake_total": "61163778955385799796336318561595493655",
    "peers_stake_required": "60000000000000000000000000000000000000"
}

root@aa:~# curl -H "Content-Type:application/json;charset= utf-8" -X POST --data '{"action": "peers"}' http://127.0.0.1:7076/ | wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6899  100  6880  100    19   256k    725 --:--:-- --:--:-- --:--:--  258k
156
```

Can the return information of the above two commands show that there is a problem?

**Comment by guilhermelawless** [comment]
It does, the average number of peers is 260 and you only have about 150, meaning you're not well connected.

It should be 7075/tcp not 7056, according to your configuration details above. An alternative is allowing UPnP in the router. A way to test if the port is open is `telnet YOUR_IP 7075` from another computer. Then it looks like you're all set in terms of docker.

Once you see above 200 peers you should be set, restarting the node should help.

**Comment by apufvqsp** [comment]
Okay, I will set a public IP for the host and try again. 

Thank you very much for your patient answers

**Comment by apufvqsp** [comment]
@guilhermelawless ，
I have verified that after setting the public network ip to the docker host, the unchecked blocks are reduced to 0, thanks again
