### ISSUE TITLE
xrb_uint256_to_string  does not null-terminate the address string

### ISSUE THREAD

**Issue by gkastel** [nanocurrency/nano-node#290]
https://github.com/clemahieu/raiblocks/blob/0f06b03a1c42655f3217b1a8f2936320a7b0cf67/rai/lib/interface.cpp#L21

**Comment by clemahieu** [comment]
The idea with this was that someone could put this number in to the middle of a string without having the null character clobber something.

// Convert public/private key bytes 'source' to a 64 byte not-null-terminated hex string 'destination'
void xrb_uint256_to_string (const xrb_uint256 source, char * destination);

**Comment by gkastel** [comment]
ok byt to_address() uses 65 chars

https://github.com/clemahieu/raiblocks/blob/0f06b03a1c42655f3217b1a8f2936320a7b0cf67/rai/lib/interface.cpp#L24

in the test they are both expecting 65 byte null-terminated buffers:
https://github.com/clemahieu/raiblocks/blob/b328640745cf9c0200bcaba67c44832572bb0fa3/rai/core_test/interface.cpp
