### ISSUE TITLE
util/build_prep/bootstrap_boost.sh: 3: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by apasov** [nanocurrency/nano-node#2922]
**Description of bug:**

Get an error when trying to compile from source v21.1 or  v21.2

**Steps to reproduce the issue:**
```bash
git clone --branch V21.2 --recursive https://github.com/nanocurrency/nano-node.git nano_build
cd nano_build
export BOOST_ROOT=`pwd`/../boost_build
sh util/build_prep/bootstrap_boost.sh -m
```
**Describe the results you received:**
```bash
util/build_prep/bootstrap_boost.sh: 3: Syntax error: "(" unexpected
```

**Describe the results you expected:**

No errors

**Environment**:

Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-47-generic x86_64)

**Comment by guilhermelawless** [comment]
Hi @apasov , could you try the following instead?
`bash util/build_prep/bootstrap_boost.sh -m`

**Comment by apasov** [comment]
Hi @guilhermelawless , yes, it worked, thank you. I was able to successfully compile nano_node.

**Comment by guilhermelawless** [comment]
Documentation updated, thanks @apasov @argakiig !
