### ISSUE TITLE
Error "Fork" received when processing an open block

### ISSUE THREAD

**Issue by oggy95** [nanocurrency/nano-node#2931]
**Description of bug:**
Hello. Created an account and forgot to reproduce receiving first transaction (https://docs.nano.org/integration-guides/key-management/#first-receive-transaction). Now I received a few more transactions and cann't accept them to use it. When following guide upper recieving first transaction, I get an error:   `{"error": "Fork"}`

**Steps to reproduce the issue:**
1. Create an account.
2. Send money to new account and don't activate account via guide.
3. Receiving more transactions and trying to activate account.

**Describe the results you received:**
Have an error `{"error": "Fork"}`

**Describe the results you expected:**
Activated account.

**Additional information you deem important (e.g. issue happens only occasionally):**
Maybe error occured because have a trouble, when upgrade the node. Have to recreate docker image to launch after upgrading.

**Environment**:
Ubuntu 18.04.4 LTS
Docker Version: 19.03.6

**logs**

**Comment by guilhermelawless** [comment]
This error means the "previous" field in your block is not the frontier (latest block) of your account (that you get with RPC account_info, per the guide).

**Comment by oggy95** [comment]
@guilhermelawless then i must in "previous" field set "frontier" block from "account_info", not "0" how in guide?

**Comment by guilhermelawless** [comment]
Ah, apologies. In the case of the first receive block it should be "0" as you said. However, there was recently an epoch upgrade which may have opened your previously unopened account (with 0 balance).

To check if this is the case, try RPC account_info with the receiving account, or check it on a block explorer such as https://repnode.org . If the account shows up it means it's created and you should use the frontier as "previous".

**Comment by oggy95** [comment]
Get a block from account_info, it's not "0".
But when trying with new "previous" block, and broadcastring transaction with subtype "open", get an errot:
```
{
    "error": "Invalid previous block for given subtype"
}
```

**Comment by guilhermelawless** [comment]
Since the account is now open, your block is a "receive", not "open". Make sure to also check the "balance" of `account_info` return, in case it's not zero you will need to adjust the balance of the block you're creating.

**Comment by oggy95** [comment]
Yes, this works, I've got first transaction.
But other transactions still in pending. How to enable automatically receiving pending transactions?

**Comment by guilhermelawless** [comment]
Since you are following that guide, it means you're doing external management, i.e., your key is not stored in the node wallet.

With this approach the only way to do it automatically would be to receive notification of confirmations via the [websocket](https://docs.nano.org/integration-guides/websockets/), creating the receive block and processing.

For already existing pending transactions, use RPC `pending` to get the pending blocks, with `"sorting":"true"` to start with the highest amounts first.

**Comment by guilhermelawless** [comment]
Closing as this has been resolved and conversation moved to a different topic, but please feel free to come by the discord server at https://chat.nano.org or open a thread in the forum at https://forum.nano.org with any other questions about how to best use the node.
