### ISSUE TITLE
clang/boost 1.73 compile error on case-insensitive file systems

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/nano-node#2985]
Here's a cute problem when I compile the node with the latest clang version/boost 1.73 on macOS.

So `boost/config/select_stdlib_config.hpp` contains this:

```
#if defined(__cplusplus) && defined(__has_include)
#  if __has_include(<version>)
#    include <version>
#  else
#    include <cstddef>
#  endif
#elif defined(__cplusplus)
#  include <cstddef>
#else
#  include <stddef.h>
#endif
```

where `include <version>` picks up... `miniupnp/miniupnpc/VERSION` 🙄 🤣  This happens because APFS is case-insensitive.

Renaming that file to VERSION_ or whatever "fixes" the issue, but surely there must be a better way.

**Comment by clemahieu** [comment]
I worked around this by deleting that VERSION file, it doesn't appear to be needed.

Since someone else is running in to this we'll get a fix.

**Comment by cryptocode** [comment]
This problem should go away soon: https://github.com/miniupnp/miniupnp/issues/540 😀 
Might require a minor update to the cmake script when upgrading.

**Comment by clemahieu** [comment]
Fixed with https://github.com/nanocurrency/nano-node/pull/3541
