### ISSUE TITLE
I want to customize the nano cryptocurrency

### ISSUE THREAD

**Issue by dinarpay** [nanocurrency/nano-node#2989]
Can the source code be used for the nano cryptocurrency
And edit the name and currency symbol
And Total supply
And changing the prefix of the wallet address, to another prefix of my choice
I love nano very much
But I want a stable currency that works in my country to facilitate digital payments services, in a very safe and fast way

**Comment by LeonChain** [comment]
Hi Dinarpay
I would like to chat with you.

**Comment by zhyatt** [comment]
@dinarpay This issue is outside the scope supported here.
