### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by RobbertC5** [nanocurrency/nano-node#300]
The example that's given for the validate account number checksum action is an invalid account, but the documentation says it's a valid one.
([https://github.com/clemahieu/raiblocks/wiki/RPC-protocol#validate-account-number-checksum](https://github.com/clemahieu/raiblocks/wiki/RPC-protocol#validate-account-number-checksum))

**Comment by argakiig** [comment]
fixed example with valid account+checksum
xrb_1111111111111111111111111111111111111111111111111117353trpda
