### ISSUE TITLE
Experimental Pruning Test Cases

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3008]
See [#2881](https://github.com/nanocurrency/nano-node/pull/2881) for links to various pruning PRs. Initial testing was conducted in earlier DBs with success, but the previous large PR was split and expanded on recently. This feature remains experimental and not enabled for voting nodes.

## Configuration

- Pruning can be enabled with nano node launch flag `--enable_pruning` (continuous) and with CLI command `--debug_prune` (once).
- Pruning settings can be configured within `config-node.toml`. Default pruning period for beta testing is aggressive: 5 minutes.

```
[node.experimental]
# Time limit for blocks age after pruning.
# type:seconds
max_pruning_age = 300

# Limit for full blocks in chain after pruning.
# type:uint64
max_pruning_depth = 0
```

- Pruning is currently incompatible with voting. If voting is enabled in config, pruned node fails to start.
- You can check pruning status in RPC [block_count](https://docs.nano.org/commands/rpc-protocol/#block_count) containing new entries: full & pruned blocks count.

### EP1: Bootstrapping while pruned
Configure a node for continuous pruning and run a bootstrap from scratch.

- Observe block/cemented counts to ensure node is able to fully sync.
- Observe disk space usage and pruned blocks count to ensure pruning properly took place per the configuration.

- [x] a. LMDB backend
- [x] b. RocksDB backend

<hr>

### EP2: Regular operation of pruned nodes under sustained, heavy traffic
Configure a node for continuous pruning and keep online during heavy traffic (high BPS but below saturation point) for a sustained period of 10 mins or longer.

- Observe block/cemented counts to ensure node is able to maintain sync or close to sync depending on node specs.
- Observe disk space usage and pruned blocks count to ensure pruning is properly maintained throughout the sustained network activity period per the configuration.

- [x] a. LMDB backend
- [x] b. RocksDB backend

**Comment by zhyatt** [comment]
From Discord user: Ricki 

> I've pruned the live network database using lmdb and dev build 8. 
> Here are my results:
> Initial:             41,252,151,296 bytes
> Vacuumed:   23,088,758,784 bytes
> Pruned:          25,211,154,432 bytes
> Vacuumed:   10,924,501,376 bytes
> Btw database upgrade took almost 45 minutes

**Comment by zhyatt** [comment]
Both EP1b and EP2b were tested via TerraForm deployment of 2vCPU/2GB instances with DB8, bootstrapping and available during heavy network traffic events. No pruning related issues found. Moving out to DB10 for additional LMDB testing once that is more widely available (no forced RocksDB).

**Comment by RickiNano** [comment]
Experimental Pruning Test Cases #3008 EP1a report:
Hardware used: I7-8700, 32GB, 1TB SSD, Gigabit internet
Bootstrapped from scratch using LMDB and default pruning configuration
Total time elapsed: ~4 days
Progress was followed several times a day using the "block_count" rpc call.
Final status:
{ "count": "11910236",    "unchecked": "0",    "cemented": "11910236",    "full": "1551519",    "pruned": "10358717" }
At this point in time the ledger had 1551518 Frontier blocks.
Pruned blocks = Total blocks - frontier blocks
10358718 = 11910236 - 1551518
Size of ledger:		7.206.920.192 bytes
Size after vacuum:	3.614.453.760 bytes
No errors observed in log.

**Comment by zhyatt** [comment]
Thanks for your help with EP1 @RickiNano - that is a successful result, although a bit slow as you mentioned in Discord. We may be doing some load testing soon so interested in how that performs, but we are unlikely to change pruning behavior in this release unless any crashes are discovered, in order to focus on other areas before release.
