### ISSUE TITLE
Boost.Coroutine sanitizer issues

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/nano-node#3021]
Boost.Coroutine doesn't work well with sanitizers. The library is deprecated and will likely never get ASAN support: https://github.com/boostorg/coroutine/issues/30#issuecomment-325583085

Boost.Coroutine has a workaround for Valgrind, but not ASAN:
https://www.boost.org/doc/libs/1_74_0/libs/coroutine/doc/html/coroutine/stack/valgrind.html

Boost.Coroutine2 has workarounds for Valgrind and gcc/clang sanitizers:
https://www.boost.org/doc/libs/1_74_0/libs/coroutine2/doc/html/coroutine2/stack/valgrind.html
https://www.boost.org/doc/libs/1_74_0/libs/coroutine2/doc/html/coroutine2/stack/sanitizers.html

This requires building Boost from source with the flags mentioned in the links above. As far as I can tell, Coroutine2 doesn't work with ASIO yet. @wezrule mentioned support for C++20 coroutines in Boost 1.74 as a possible option in the future.

**Comment by clemahieu** [comment]
I did a bit of digging on ASIO+coroutine2 and while I found some people who have made patches in this direction https://github.com/boostorg/asio/pull/52 https://github.com/boostorg/asio/pull/55 but they were never accepted.

It sounds like there are 2 reasons why they're not patching asio in this way:
- C++20 coroutine language support
- The C++ networking TS which has a different execution model compared to ASIO.

It's unfortunate, after some playing around the coroutine format is a much more natural way to do our networking code and probably has some performance benefits by not constructing so many callbacks.

Did you run into some specific issues with ASAN and boost.coroutine? I ran into some false-positive memory errors and it made some things more difficult to debug at times.

Anything currently in develop that's problematic?

**Comment by cryptocode** [comment]
Makes sense. It looks like a proper coroutine/asio combo is in a bit of limbo right now. I definitely agree it would be helpful in removing some ASIO pyramids of doom.

> Did you run into some specific issues with ASAN and boost.coroutine?

The problem was that ASAN kicked in immediately at the new network.cpp code using coroutines for the steady timers, so I had to revert those while testing my PR under ASAN (as the asan workaround does not work for coroutine, only coroutine2; blacklisting user code doesn't seem to help either as it's the stack switching occuring in boost that's confusing sanitizers)
