### ISSUE TITLE
Suggestion: checkpoints or something for bootstrap

### ISSUE THREAD

**Issue by My1** [nanocurrency/nano-node#3073]
apparently a Nano Node's bootstrapping process is not very fond of being interrupted, be it a system restart or a crash or basically anything. and honestly especially when you are especially in the middle of verification and a crash happens, this is a very frustrating thing since it can easily take yet another day for even just the downloads happening again.

so I would propose that the node can make checkpoints or something during the bootstrap process for example every million blocks that are downloaded and/or verified and/or cemented, so in case anything happens, only an internal recheck against that checkpoint is needed and instead of at worst days of effort being dropped it's maybe just a few minutes or an hour depending on the specific timing.

also it would in general make making a node more beginner friendly, which likely would be nice for it as a whole so more people can use nano nodes, compare to bitcoin where with umbrel even an in my opinion severly technologically challenged personis able to do it without any issues.

**Comment by qwahzi** [comment]
Resolved by ascending bootstrap in V25
