### ISSUE TITLE
Node crash while Bootstrapping (in the middle of verification)

### ISSUE THREAD

**Issue by My1** [nanocurrency/nano-node#3074]
**Description of bug:**

Basically I am trying to run a node, with Version 21.2 and in the late bootstrapping process I have had a crash.

The node already has downloaded all the blocks, specifically 21:00 UTC yesterday, and it crashed about 14:30 UTC today at about 18,5 Million Blocks checked, and 12,3 Million cemented in.

I am honestly not sure how or even IF I can reproduce it and certainly may take a while, it's basically been a whole day since that attempt that crashed started, so even if it were reproducible it certainly will take a while.

**Environment**:

OS: Ubuntu Server 20.04.1
Linux vsrv 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Node Version 21.2
<summary>Docker Version Output</summary>
<details>

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

**Server Info**

https://php-friends.de/vserver-ssd/vserver-winterspecial-2020-ssd-mini
Xeon E5-2630 v4 (4 dedicated cores including nested virtualization)
6GB RAM
150GB of Raid 10 SSD Space
1Gbit/s Network

**logs, dumps and backtrace**
(cleaned of all the RPC calls from the monitor and me trying to get progress information all the time)

[nanode crash.zip](https://github.com/nanocurrency/nano-node/files/5743635/nanode.crash.zip)

no idea how I get the actual crash report considering the nano is in a docker and has been bootstrapping for 5 hours already.

**Comment by zhyatt** [comment]
@My1 I believe you were able to discuss and get help in Discord but if not, please let us know.
