### ISSUE TITLE
releases sha256 files formatted incorrectly

### ISSUE THREAD

**Issue by androm3da** [nanocurrency/nano-node#3083]
The signatures produced for `nano-node-V21.2-Linux.deb` and `nano-node-V21.2-Linux.tar.bz2` cannot be verified normally.  They should include the name of the file.  The source tarball is produced correctly.

If I manually edit the file I can get it to pass the signature.

```
$ cat nano-node-V21.2-Linux.deb.sha256
babd8b76575e7d1407030d658f6c5f0e7f6cd9084fd3fc3e7e8646062268d54e

$  cat nano-21.2.tar.gz.sha256 
e1b9841de8c4d41875ccb744df46426137a7046b98846057093f796304633514  nano-21.2.tar.gz

$ sha256sum --check nano-node-V21.2-Linux.deb.sha256 
sha256sum: nano-node-V21.2-Linux.deb.sha256: no properly formatted SHA256 checksum lines found

$ sha256sum --check nano-21.2.tar.gz.sha256
nano-21.2.tar.gz: OK

```

**Comment by argakiig** [comment]
Thanks, pretty sure this was an oversight on my end, will update the scripts accordingly,
