### ISSUE TITLE
node repeated shutdown after 3s

### ISSUE THREAD

**Issue by regfaker** [nanocurrency/nano-node#3087]
**Description of bug:**

My node is constantly terminating after cca 3s of run without obvious cause. Not in log, not in crash report.
I have noticed node termination issues week ago but before it worked at last for longer time, now I'm in this state where the node barely do something.

**Steps to reproduce the issue:**
1. Just run node as usually
2. After 3s execution stops and docker is restarting it (status Restarting (139))

I've tried to docker stop,rm and run it again but with same result.
Last change I've made to node was that I switched to non root docker user according to https://docs.nano.org/running-a-node/docker-management/#docker-user-support if this could affect this.
For now I will stop my node until I will have some more time to look deeper or if this issue will bring some hints.

**Environment**:

- OS: Debian GNU/Linux 10 (buster)
- Kernel: Linux vps 5.9.12 #1-vpsAdminOS SMP Thu Dec 3 18:02:20 UTC 2020 x86_64 GNU/Linux
- Node version: v21.2(-release-assert-patch-lmdb-0.9.25-40nkeys because of [this](https://github.com/nanocurrency/nano-node/issues/3075))
- docker version: 20.10.2

**logs**
[log_2021-01-23_18-15-47.3817.log](https://github.com/nanocurrency/nano-node/files/5860784/log_2021-01-23_18-15-47.3817.log)
```
log_to_cerr = true
EXECUTING: nano_node --daemon --config node.logging.log_to_cerr=true

Starting up Nano node...
[2021-Jan-23 18:17:06.920636]: Starting up Nano node...
[2021-Jan-23 18:17:09.760705]: Wallet unlocked
[2021-Jan-23 18:17:09.761068]: Node starting, version: V21.2_release_assert_patch
[2021-Jan-23 18:17:09.761123]: Build information: 0ce4b42 "GNU C++ version " "5.4.0 20160609" "BOOST 107000" BUILT "Jan  5 2021"
[2021-Jan-23 18:17:09.761176]: Database backend: LMDB 0.9.25
[2021-Jan-23 18:17:09.761229]: Active network: live
[2021-Jan-23 18:17:09.761320]: Work pool running 40 threads 
[2021-Jan-23 18:17:09.761369]: 0 work peers configured
[2021-Jan-23 18:17:09.761439]: Outbound Voting Bandwidth limited to 10485760 bytes per second, burst ratio 3
[2021-Jan-23 18:17:09.761761]: Voting is enabled, more system resources will be used
[2021-Jan-23 18:17:09.761842]: Node ID: node_31mty7izcxh1zf7ewpfxugfhp47uzn7w4goqj7m8q6bufrsuaeq8w67iucgz
[2021-Jan-23 18:17:09.761999]: Dropping unchecked blocks
```

I'm attaching also all of my previous logs to trace possible point in time (or blocks) where this started
[logs.zip](https://github.com/nanocurrency/nano-node/files/5860793/logs.zip)
Last one quite normal (althought ended after 1h17m) is `log_2021-01-22_06-40-36.797.log`

`nano_node_crash_report.txt` is just:
```

Using relative addresses:
```

Thanks for any help

**Comment by schenkty** [comment]
Can you check if your RPC is accessible to the internet? The default port is 7076. Open RPC ports make the node vulnerable to stop commands.

**Comment by regfaker** [comment]
RPC port is ported as `-p 127.0.0.1:7076:7076` so it shouldn't be accessible from outside host. I have disabled control too (`enable_control = false`).
I would also assume that if node stop is triggered by rpc it will be in log.

**Comment by regfaker** [comment]
I'm now elaborating with docker/vps setup/checks

**Comment by qwahzi** [comment]
Fwiw, all RPC logs seem to disappear ~Jan 14th (I'm assuming you were probably still issuing some kind of RPC commands between the 14th and now?), and I saw enable_control on for non-local addresses as late as January 9th:

`[2021-Jan-09 12:47:20.127537]: WARNING: control-level RPCs are enabled on non-local address ::ffff:0.0.0.0, potentially allowing wallet access outside local computer
`

**Comment by Srayman** [comment]
> [2021-Jan-09 12:47:20.127537]: WARNING: control-level RPCs are enabled on non-local address ::ffff:0.0.0.0, potentially allowing wallet access outside local computer

That's the standard setup for docker, it uses ::ffff:0.0.0.0 to allow access to the host outside of the container.  Then the docker run command is responsible for limiting access to the container (eg -p 127.0.0.1:7076:7076) that regfakar mentioned.

My guess is a corrupt database, I had a similar case recently with a bad memory stick it would crash shortly after starting the node.

I would try moving/renaming data.ldb in the ~/Nano directory and see if it starts up correctly.  It will start bootstrapping which can take a while depending on resources, so could use a ledger snapshot if you need something quicker/sooner.

**Comment by regfaker** [comment]
Thanks, that helped. It is running now. Strange thing is that my "damaged" data.ldb file was 28G big while snapshot has 23G so some 5G extra data was generated. I have backup of it if you are interested.
Could there be some log aid which would tell "corrupted ledger"?

Another thing which I noticed in discord chat https://discord.com/channels/370266023905198083/370266023905198085/803633698545205258 - if it was meant to be me - I don't think it was the case:
restarts happened for days before, and I'm not hosted at DO (as said that IPs was from there).

**Comment by Srayman** [comment]
That's great it's running again.  The snapshot ledger has some extra data cleared out and it has been "vacuumed" which helps reclaim space that LMDB takes up as it runs.

After running for a while you'll likely see the data.ldb file around 30-35GB.

**Comment by regfaker** [comment]
hm, not for long. I'm back in the same state again. I've captured [this](https://github.com/nanocurrency/nano-node/issues/3075#issuecomment-768176574) failed assertion before so probably it can be all about LMDB problems. I'm looking forward to v22.

**Comment by zhyatt** [comment]
@regfaker Closing due to issue being stale but let us know if you continue to run into crashes.
