### ISSUE TITLE
Error Generating Block

### ISSUE THREAD

**Issue by rathodudayy** [nanocurrency/nano-node#3112]
I am using php to request nano node, but if I try send command, it works but I need to run that command 4-5 times to create a send transaction. 

```
$ch = curl_init('my ip address');
	$data = array(	
					"action" => "send", 
					"wallet" => "7E9DCE1ED0967B6AFF2A8287924C10CDFC06AE9D0E50C174C2E52A97AA94DA32", 
					"source" => $ARGS['adr_source'],
					"destination" => $ARGS['adr_destination'], 
					"amount" => $ARGS['amt'], 
					"id" =>  "unique_id"
	 			 );
  	$r = $this->postCurl($ch, $data);
```

Sometimes it works on the first attempt and sometimes it takes more than 5 calls, I am not sure why this is happening.

**Comment by Srayman** [comment]
What is your curl timeout set too?  Are you using CPU work/PoW generation on the node itself?

If you do many send's back to back it will need to generate PoW first, which can take some time, especially on a CPU without a GPU.  If you wait long enough it will pre-cache the PoW so the next send is fast.

Have you tried generating PoW first and then adding the "work" to the send command to rule out any work generation problems?

**Comment by rathodudayy** [comment]
> What is your curl timeout set too? Are you using CPU work/PoW generation on the node itself?
> 
> If you do many sends back to back it will need to generate PoW first, which can take some time, especially on a CPU without a GPU. If you wait long enough it will pre-cache the PoW so the next send is fast.
> 
> Have you tried generating PoW first and then adding the "work" to the send command to rule out any work generation problems?

Yes I am using CPU currently in the testing and development phase, so as you suggested because my CPU will be slower than GPU, my node is getting more request than it can handle so it's responding with "error generating block"

Can you link any page where there is a reference to how to do this procedure in an efficient way? I would appreciate that help, thank you.

**Comment by Srayman** [comment]
Not 100% sure on the internal code sequence that could cause it to fail but in the RPC docs here https://docs.nano.org/commands/rpc-protocol/#send

It mentions the following.

> Proof of Work is precomputed for one transaction in the background when you are using the node wallet to track accounts. If it has been a while since your last transaction it will send instantly, the next one will need to wait for Proof of Work to be generated.
> If the request times out, then the send may or may not have gone through. If you want to the ability to retry a failed send, all send calls must specify the id parameter as follows

CPU PoW for sending can take up to a minute or longer to generate if it is not pre-cached.

**Comment by rathodudayy** [comment]
Ok thank you for your help, I am going to try to execute send after 5 mins of the interval to see if this is the reason, and if it's because of PoW, I will use WebSockets to get notifications of PoW generation and execute the next transaction after that.



```
{
  "action": "subscribe",
  "topic": "work"
}
```

**Comment by zhyatt** [comment]
@rathodudayy Closing due to issue being stale.
