### ISSUE TITLE
Consider adding command line parameter which defines config root

### ISSUE THREAD

**Issue by howinator** [nanocurrency/nano-node#3113]
**Description of bug:**

Not a bug - this is a feature request for node operators. I would like to store the node, rpc, etc. config files in a different directory root than where the ledger is stored. Currently `--data_path` specifies where the process should both look for config files and the ledger. When mounting volumes to a node in a production system, this isn't desirable because I have a different volume for my ledger  than where I store my config.

This could either take the form of `--config_path` which defines a config root (`/etc/nano`) or you could have separate command line arguments for each config file, but I bet `--config_path` is sufficient for almost all use cases.

**Steps to reproduce the issue:**
N/A

**Describe the results you received:**
N/A

**Describe the results you expected:**
N/A

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A
**Environment**:
N/A

**logs**
N/A

**Comment by zhyatt** [comment]
@howinator If still interested in this, can you submit using the feature request form? https://github.com/nanocurrency/nano-node/issues/new?assignees=&labels=&template=feature-request.yml
