### ISSUE TITLE
Consider adding option to write log output to stdout/stderr

### ISSUE THREAD

**Issue by howinator** [nanocurrency/nano-node#3114]
**Description of bug:**
An extremely common pattern for cloud-native deployments, e.g., kubernetes, is to log to stdout/stderr which allows the orchestration engine to capture logs for aggregation across the cluster. When deploying to kubernetes, dealing with actual log files adds a not-insignificant amount of work for capturing logs. It would be really nice if there was an option to write log output to stdout/stderr.

**Steps to reproduce the issue:**
N/A

**Describe the results you received:**
N/A

**Describe the results you expected:**
N/A

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Environment**:
N/A

**logs**
I wish.

**Comment by howinator** [comment]
Actually I'm going to post this one to the forum first to make sure I didn't miss something. I discussed it on Discord, but I'm not convinced this doesn't already exist.

**Comment by argakiig** [comment]
This can be done via cli `--config node.logging.log_to_cerr=true` or in the config itself
```
[node.logging]
log_to_cerr = true
```

**Comment by argakiig** [comment]
These are also enabled in the entry.sh of docker image nanocurrency/nano, I don't remember the tag we added that though. Also when using the official dockerhub image or building from source, the `-l` shorthands to the cli log_to_cerr=true
