### ISSUE TITLE
Time Lock Send

### ISSUE THREAD

**Issue by ghost** [nanocurrency/nano-node#3153]
Would it be possible to add a time-lock send?

It used to be that nano didn't store or use timestamps. Since the roadmap is adding timestamps in votes, I figured I would ask about time lock send transactions.

The three use cases would be:
1) nano to (other coin that does not support smart contracts) atomic swaps.
2) first send to a new address.
3) unintentional send.

The simplest idea I had would be that the time-lock send transaction would automatically disappear after 24h unless a receive block was created. Since most time locks are for minutes, and never for days, I think a 24h time lock send would cover most use cases.

**Comment by clemahieu** [comment]
The vote timestamps aren't related to the block origination time and there are significant hurdles to using timestamps in the way you describe. It's better to vet this idea through the #protocol channel on discord before opening an issue here.
