### ISSUE TITLE
Updating block work results in weird behaviour.

### ISSUE THREAD

**Issue by playnano** [nanocurrency/nano-node#3162]
**Description of bug:**

Once a block is processed by the node/network, it's possible to update its work if the block hasn't been confirmed yet. Until the recent spam this was something that wasn't really necessary or even easy to do, due to the network confirming everything so fast. But now that there is this congestion, and going into the future where spam prevention measures will be in place, this is something that services might have to do with some frequency, especially while the network is saturated.

However, right now, updating a block's work results in two kinds of error responses from the node:
1st - When the work update succeeds, the node responds with an error: "Old block", which leads into confusion because even though the request was successful, we got an error message.
2nd - When updating a receive block, if using `"subtype": "receive"` on the RPC `process` command, the node responds with another error: "Invalid block balance for given subtype". Making this same request without specifying the subtype "works properly" - the block is updated and the node responds with the "1st" error message above.

**Steps to reproduce the issue:**

Here's a series of RPC calls to reproduce the issue.

One should be able to reproduce this with any unconfirmed receive block hash.
I'll be using `9D123CA45183C9AD6804043446BB6B9386555A8BD37D12771B738B2F3745C55D`.

Starting with `block_info` prior to the block work update.

```
curl -g -d '{ "action": "block_info", "json_block": "true", "hash": "9D123CA45183C9AD6804043446BB6B9386555A8BD37D12771B738B2F3745C55D" }' '127.0.0.1:7076'

{
    "block_account": "nano_1tnimzbdf3dkx9rrifco4h976yyotrwx6beu5xjj11rgoesaapnodbhyxgek",
    "amount": "360000000000000000000000000",
    "balance": "109118000000000000000000000000",
    "height": "2923",
    "local_timestamp": "1615646579",
    "confirmed": "false",
    "contents": {
        "type": "state",
        "account": "nano_1tnimzbdf3dkx9rrifco4h976yyotrwx6beu5xjj11rgoesaapnodbhyxgek",
        "previous": "3F247E7944E3E41667F024471972373930F09AEC4EA84A26578A0CEBA8E8BB4B",
        "representative": "nano_1pnanopr6myj87qfbae3mmf1yrniy1na34wqan7cqrfswy3fuwozgefuet8z",
        "balance": "109118000000000000000000000000",
        "link": "E70DFBD0A862C6B2336E35F50C33F78F8D01D554AAC1E432F5A40CEFC1BCFD69",
        "link_as_account": "nano_3srfzhacirp8paspwfho3iszh5wf19cobcp3wishdb1exz1uszdbkerrd9cc",
        "signature": "9F6E88C8C2452A62EC858B017E2E873CE7CA5FDD0E7DE375BA833F178EBF535096C09E6F864622DA97B3DF441145AD25A3527A02EF82BA144C510A48BAE91502",
        "work": "5f37dcef64c95076"
    },
    "subtype": "receive"
}
```

Validating the work for reference.

```
curl -g -d '{ "action": "work_validate", "hash": "3F247E7944E3E41667F024471972373930F09AEC4EA84A26578A0CEBA8E8BB4B", "work": "5f37dcef64c95076" }' '127.0.0.1:7076'

{
    "valid_all": "0",
    "valid_receive": "1",
    "difficulty": "ffffff7446ec711b",
    "multiplier": "0.057256161080212"
}
```

Then I generated a new work: `66c9ad8c9121f11c` which I'll also validate for reference.

```
curl -g -d '{ "action": "work_validate", "hash": "3F247E7944E3E41667F024471972373930F09AEC4EA84A26578A0CEBA8E8BB4B", "work": "66c9ad8c9121f11c" }' '127.0.0.1:7076'

{
    "valid_all": "1",
    "valid_receive": "1",
    "difficulty": "fffffffda8cb9312",
    "multiplier": "3.417863214664478"
}
```

Lastly, let's `process` the block, now with the updated work.

```
curl -g -d '{ "action": "process", "subtype": "receive", "json_block": "true", "block": {
  "type": "state",
  "account": "nano_1tnimzbdf3dkx9rrifco4h976yyotrwx6beu5xjj11rgoesaapnodbhyxgek",
  "previous": "3F247E7944E3E41667F024471972373930F09AEC4EA84A26578A0CEBA8E8BB4B",
  "representative": "nano_1pnanopr6myj87qfbae3mmf1yrniy1na34wqan7cqrfswy3fuwozgefuet8z",
  "balance": "109118000000000000000000000000",
  "link": "E70DFBD0A862C6B2336E35F50C33F78F8D01D554AAC1E432F5A40CEFC1BCFD69",
  "link_as_account": "nano_3srfzhacirp8paspwfho3iszh5wf19cobcp3wishdb1exz1uszdbkerrd9cc",
  "signature": "9F6E88C8C2452A62EC858B017E2E873CE7CA5FDD0E7DE375BA833F178EBF535096C09E6F864622DA97B3DF441145AD25A3527A02EF82BA144C510A48BAE91502",
  "work": "66c9ad8c9121f11c"
} }' '127.0.0.1:7076'

{
    "error": "Invalid block balance for given subtype"
}
```

And here's the **2nd** error message like described above. Now lets `process` without the `subtype`:

```
curl -g -d '{ "action": "process", "subtype": "receive", "json_block": "true", "block": {
  "type": "state",
  "account": "nano_1tnimzbdf3dkx9rrifco4h976yyotrwx6beu5xjj11rgoesaapnodbhyxgek",
  "previous": "3F247E7944E3E41667F024471972373930F09AEC4EA84A26578A0CEBA8E8BB4B",
  "representative": "nano_1pnanopr6myj87qfbae3mmf1yrniy1na34wqan7cqrfswy3fuwozgefuet8z",
  "balance": "109118000000000000000000000000",
  "link": "E70DFBD0A862C6B2336E35F50C33F78F8D01D554AAC1E432F5A40CEFC1BCFD69",
  "link_as_account": "nano_3srfzhacirp8paspwfho3iszh5wf19cobcp3wishdb1exz1uszdbkerrd9cc",
  "signature": "9F6E88C8C2452A62EC858B017E2E873CE7CA5FDD0E7DE375BA833F178EBF535096C09E6F864622DA97B3DF441145AD25A3527A02EF82BA144C510A48BAE91502",
  "work": "66c9ad8c9121f11c"
} }' '127.0.0.1:7076'

{
    "error": "Old block"
}
```

And here's the **1st** error message.

**Describe the results you expected:**

In both cases, I expected a successful response, saying that the block work was updated.

**Additional information you deem important (e.g. issue happens only occasionally):**

Since making the above commands, I've updated the block work once again. It should now be `bc5132566bc01c87`.

**Environment**:

Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 4.15.0-135-generic
Architecture: x86-64
Node version: 21.3
(not using docker)

**Comment by mistakia** [comment]
Despite the error, the block is updated. I've been able to free some confirmations this way. You can check to see if it worked by pulling the block info and seeing if the new PoW is returned.

**Comment by playnano** [comment]
I know that the block is updated, I said that on "1st". I just think that the node should respond with a success message on both cases and not an error message.

That said, not sure if you read my other issue #3163, but I've not been able to manually confirm any block by increasing its work. Where you able to do that?

**Comment by mistakia** [comment]
Ah yea I missed that 😅 and agree with your main point.

I have been able to manually confirm blocks by increasing the work, though its not consistent and it's tricky. There appears to be a number of factors at play that prevent effectively pushing confirmations forward manually. Confirmation heights for a given account are different across the network. A few bugs/issues pertaining to cached votes and restarting expired elections are seemingly making it difficult to use this method to effectively trigger new elections across the network and force checks on quorum. 

#3165, #3164 may address the problem
