### ISSUE TITLE
Remove publishing to Docker tag `latest`

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3182]
To follow general best practices for Docker tagging, the `latest` tag for production images should no longer update when a new version is published: https://hub.docker.com/r/nanocurrency/nano/tags. This `latest` tag will be deleted from the Docker hub in the near future. However, the `latest` tag will be left available for the beta network tags to facilitate more passive contributions: https://hub.docker.com/r/nanocurrency/nano-beta/tags.

**Comment by My1** [comment]
> To follow general best practices for Docker tagging, the `latest` tag for production images should no longer update when a new version is published

not sure if I understand properly, what's the point of having a "latest" version if it doesnt get the latest version all the time?

**Comment by zhyatt** [comment]
> > To follow general best practices for Docker tagging, the `latest` tag for production images should no longer update when a new version is published
> 
> not sure if I understand properly, what's the point of having a "latest" version if it doesnt get the latest version all the time?

There is no point in having the tag available if it isn't updated, so perhaps it should be made more clear that the tag will be deleted from the Docker hub at some point to avoid confusion around its usefulness (for production at least, will remain on the beta side). Updated comment to reflect this.

**Comment by My1** [comment]
> There is no point in having the tag available if it isn't updated

and why not update it like normal?

**Comment by zhyatt** [comment]
> > There is no point in having the tag available if it isn't updated
> 
> and why not update it like normal?

Having a `latest` tag for production releases makes it too easy to have unattended upgrades happen on the network. These unattended upgrades have some drawbacks, so avoiding these types of dynamic tags the following scenarios are improved:

- Help avoid a network attack vector where someone attempts to gain access to the Docker publishing to maliciously manipulate the node code and automatically impact nodes on these types of upgrades
- Avoids a portion of the network going down simultaneously if an upgrade requires down time (database upgrade, etc.)
- Helps promote more active involvement by node operators - if they commit to running a node on the network they should also be committing to following updates, testing their integrations and upgrading accordingly

**Comment by My1** [comment]
okay I see makes sense.
