### ISSUE TITLE
qt_system does not work, fix it or remove it

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#3189]
The executable "qt_system" is outdated and does not work.
It should be either removed or fixed.

```
$ ./qt_system 
Assertion (nodes.size () - 1 <= node->network_params.node.max_peers_per_ip || node->flags.disable_max_peers_per_ip) failed
std::shared_ptr<nano::node> nano::system::add_node(const nano::node_config&, nano::node_flags, nano::transport::transport_type)
/fast/nano-workspace/nano-node/nano/node/testing.cpp:29

 0# 0x000055A44B1736E0 in ./qt_system
 1# 0x000055A44B173C30 in ./qt_system
 2# 0x000055A44AD58416 in ./qt_system
 3# 0x000055A44AD58E67 in ./qt_system
 4# 0x000055A44AB5BA7E in ./qt_system
 5# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 6# 0x000055A44AB5B6AE in ./qt_system

Aborted (core dumped)
```

**Comment by argakiig** [comment]
what happens with this test if you add the flag to disable_max_peers_per_ip?

**Comment by zhyatt** [comment]
@dsiganos @argakiig Is this still an open issue?

**Comment by dsiganos** [comment]
We do not build qt_system anymore so this ticket can be considered done.
however, we could clean up a bit better, so I will leave this ticket to track the complete clean up of qt_system.

**Comment by dsiganos** [comment]
To cleanup:
* remove qt_system folder and entry.cpp
* remove qt_system from .gitignore file
* remove qt_system from coverage/CMakeLists.txt
