### ISSUE TITLE
Remove frontiers confirmation start only after reaching cemented > hardcoded

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3239]
This requires #3238 for best performance.

**Comment by SparK-Cruz** [comment]
Is this a pre-condition for #3238 ?

**Comment by zhyatt** [comment]
> Is this a pre-condition for #3238 ?

They are a related so it would be best to have them both in. Will add that to the description.

**Comment by zhyatt** [comment]
Closed by #3246
