### ISSUE TITLE
Deprecate RPC active_difficulty instead of removing it

### ISSUE THREAD

**Issue by Joohansson** [nanocurrency/nano-node#3266]
The https://docs.nano.org/commands/rpc-protocol/?h=active#active_difficulty was removed in v22DB15 which results in a parsing error for services that rely on this feature.

It might make more sense to instead more softly phase it out by reporting default values, by deprecating it. That way services won't crash when calling it and since the difficulty doesn't matter anyway it should not cause any problems to use the default difficulty.

https://github.com/nanocurrency/nano-node/pull/3260

**Comment by PapauloGamerOfc** [comment]
Why is this issue still opened if the PR was already merged?
