### ISSUE TITLE
Cementing of blocks stalling preventing node from ever catching up

### ISSUE THREAD

**Issue by MajorChump** [nanocurrency/nano-node#3293]
### Summary

I've been investigating why my node's cementing has stayed in the same range for weeks. I originally thought it was due to 21.3 but my node is now running v22.

Using the logs I can restart the node and it runs really well, everything starts cementing and then it stops. See the log attached.

Cementing stops around 07:43:06 - At this time a number of things happen. We get the following logs

[2021-May-16 07:43:06.205778]: Beginning pending block search
[2021-May-16 07:43:06.233897]: Processed 100574 elections (1 were already confirmed) in 49 milliseconds
[2021-May-16 07:43:07.073221]: Processed 245 votes in 324 milliseconds (rate of 756 votes per second)
[2021-May-16 07:43:08.851152]: Processed 1101 votes in 1777 milliseconds (rate of 619 votes per second)
[2021-May-16 07:43:22.219405]: UPnP No IGD devices found

After this no further blocks cement. I'm going to continue digging as that UPnP looks like an error?

If I restart the node cementing starts again until it hits a similar situation
[node.txt](https://github.com/nanocurrency/nano-node/files/6488848/node.txt)
.  

### Node version

V22.0

### Build details

V22.0 Docker container. 

{
    "rpc_version": "1",
    "store_version": "21",
    "protocol_version": "18",
    "node_vendor": "Nano V22.0",
    "store_vendor": "LMDB 0.9.25",
    "network": "live",
    "network_identifier": "991CF190094C00F0B68E2E5F75F6BEE95A2E0BD93CEAA4A6734DB9F19B728948",
    "build_info": "ef09e55 \"GNU C++ version \" \"7.5.0\" \"BOOST 107000\" BUILT \"May 14 2021\""
}

### OS and version

Ubuntu 20.04.2 LTS

### Steps to reproduce the behavior

As above, issue occurs not long after the node starts, cementing breaks at that point.

### Expected behavior

Anywhere from 0 to 30+ elections should be confirmed each second.

### Actual behavior

Initially 0 to 30+ elections are confirmed each second. Until it stops and then no elections are confirmed from then on.

### Supporting files

Logs attached
[node.txt](https://github.com/nanocurrency/nano-node/files/6488857/node.txt)

**Comment by MajorChump** [comment]
I've fixed the UPNP errors showing in the logs by setting the external address and port in config. The issue still happens. It seems to happen at the same point.

See new log attached. The issue occurs at this line

[2021-May-16 08:46:18.468610]: Beginning pending block search

[node2.txt](https://github.com/nanocurrency/nano-node/files/6488922/node2.txt)

**Comment by My1** [comment]
this may be in part due to the current quorum issue with the upgrade, but not sure.

**Comment by MajorChump** [comment]
Been monitoring the situation throughout the day. Couple of thoughts what might be causing the quorum issues. 

My peers_stake_total has reached 92m from 74m and my confirmations have increased 10x - 20x. This shouldn't matter though because the online_stake_total has been pretty steady at 103m. The votes should be the same if the gossip votes are working correctly but they must not be arriving for some reason.

The beta network was different though. Looking in the beta-testing channel I can see the output of confirmation_quorum for the beta network.

The online_stake_total == peers_stake_total meaning the gossip voting wasn't in affect.

**Comment by DarrenAlex** [comment]
I'm having the same issue. Unchecked blocks pile up and the rate at which cemented blocks are generated slow down.

**Comment by qwahzi** [comment]
@m-king Given the UPnP mentions in your logs, perhaps you're affected by this UPnP issue?

https://github.com/nanocurrency/nano-node/issues/3295

**Comment by MajorChump** [comment]
> @m-king Given the UPnP mentions in your logs, perhaps you're affected by this UPnP issue?
> 
> #3295

I don't get the UPNP errors anymore. After setting the external_address and external_port to my config file. Once these are added it skips all the UPNP code.

**Comment by qwahzi** [comment]
This seems to have been resolved by ascending bootstrap in V25. Let me know if you're still having issues and we can reopen the issue.
