### ISSUE TITLE
Dockerfiles: upgrade from Ubuntu 18.04 to 21.04

### ISSUE THREAD

**Issue by donutloop** [nanocurrency/nano-node#3299]
### Summary

Please consider upgrading the docker ubuntu version to the newest version for all docker files based on ubuntu.

Ref: https://hub.docker.com/_/ubuntu?tab=description&page=1&ordering=last_updated

Files:

* https://github.com/nanocurrency/nano-node/blob/develop/docker/node/Dockerfile#L20 
* https://github.com/nanocurrency/nano-node/blob/develop/docker/ci/Dockerfile-base#L1
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/tests.yml#L25
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/tests.yml#L38
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/test_network_artifacts.yml#L69
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/test_network_artifacts.yml#L69
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/rocksdb_tests.yml#L27
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/rocksdb_tests.yml#L40
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/analyzers.yml#L7
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/analyzers.yml#L23
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/beta_artifacts.yml#L44
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/beta_artifacts.yml#L69
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/develop.yml#L9
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/release_tests.yml#L27
* https://github.com/nanocurrency/nano-node/blob/develop/.github/workflows/release_tests.yml#L40

### What problem would be solved by this feature?

Ubuntu still carries out updates and fixes for the newest version.

### Are there any previous requests for this feature?

Unknown

### Do you have a suggested solution?

Change base image of all Dockerfiles

### If this feature is approved, would you be willing to submit a pull request with the solution?

I am willing to collaborate

**Comment by argakiig** [comment]
Ubuntu 18.04 is end of lifed April 2023 and so still gets regular updates. I would be interested in working with you to make the transition happen, although I suspect an 18.04 base will remain at least for the unit tests as that provides a level of certainty we haven't prematurely ended support for Ubuntu 18.04 early

**Comment by donutloop** [comment]
Ubuntu release cycle consists of multiple phases

![ubuntu](https://user-images.githubusercontent.com/9432921/119243040-9b80d480-bb63-11eb-9160-193f42f858f9.png)


Ubuntu 18.04 status

* Hardware and maintenance updates (ended)
* Maintenance updates (still running)
* Extended Security Maintenance (ESM) (still running)

Ref: https://ubuntu.com/about/release-cycle

**Comment by argakiig** [comment]
![image](https://user-images.githubusercontent.com/6511720/119308674-33dd8e80-bc22-11eb-8621-ee110e4afc0d.png)
Ref: https://wiki.ubuntu.com/Releases

Acutally upon further looking it does look like I misspoke regarding EOL on 18.04 which occurs 2028 not 2023 as originally stated.
I would still gladly work with you on on PR's submitted as I know we would also need to update some of the static caches we use in the docker images for at least boost

**Comment by qwahzi** [comment]
Resolved by https://github.com/nanocurrency/nano-node/pull/4177
