### ISSUE TITLE
Counting of voting representatives is wrong (no check for duplicates)

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#3339]
### Summary

The function rep wallets::rep_check() did not check for duplicates when adding a voting representative and the count of voting representatives could therefore be much bigger than the reality.

### Node version

V22.1

### Build details

Manual build.

### OS and version

Ubuntu 20.04

### Steps to reproduce the behavior

1. Run test case node.rep_self_vote it fails about once in a 1000 iterations.

### Expected behavior

check_rep should not count duplicate entries.

### Actual behavior

It counts duplicates.

**Comment by zhyatt** [comment]
Closed by #3340
