### ISSUE TITLE
The voting representatives counter is read without mutex protection

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#3342]
### Summary

The counter of class wallet_representatives is not always read with the proper mutex protection.
nano::wallets::compute_reps is called at regular intervals and resets the counter and therefore it is important to read the counter with some protection.

It is possible that the an account that the node mistakes an account that has voting representatives as an account with no voting representatives.

Alternatively, it could be made atomic and the nano::wallets::compute_reps  could be made to update the counter atomically.

### Node version

V22.1

### Build details

Manual build

### OS and version

Ubuntu 20.04

### Steps to reproduce the behavior

.

### Expected behavior

.

### Actual behavior

.

**Comment by zhyatt** [comment]
@dsiganos Is this the issue discussed today which may #2533 may be related to?

**Comment by dsiganos** [comment]
@zhyatt yes, that's the one.

**Comment by thsfs** [comment]
I couldn't spot a problem on this code, despite some segments seeming to be complex with two or three mutexes.
