### ISSUE TITLE
Replacing `pending` with `receivable`/`ready to receive`

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3411]
Update node references, RPC calls, etc. to use `receivable` to indicate that an incoming send block on an account is ready to have the corresponding receive block published for it (after which the newly added balance can be sent by the receiving account). Previously the less clear term `pending` was used.

Any updates to the QT wallet UI referencing the same should use the term `ready to receive` for end users.

Audit of locations requiring change TBD.

See https://www.reddit.com/r/nanocurrency/comments/ov3fro/term_pending_to_be_replaced_with_ready_to_receive/ for broader ecosystem request to make this change.

**Comment by shryder** [comment]
These are the references I found in the QT wallet:
https://github.com/nanocurrency/nano-node/blob/develop/nano/qt/qt.cpp#L118
https://github.com/nanocurrency/nano-node/blob/develop/nano/qt/qt.cpp#L275
https://github.com/nanocurrency/nano-node/blob/develop/nano/qt/qt.cpp#L780
https://github.com/nanocurrency/nano-node/blob/develop/nano/qt/qt.cpp#L1911
https://github.com/nanocurrency/nano-node/blob/develop/nano/qt/qt.cpp#L2356
https://github.com/nanocurrency/nano-node/blob/develop/nano/qt/qt.cpp#L2521

These are the references I found in the RPC handler (will be changed in 2.0 only as these would all be breaking changes):
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L529
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L613
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L695
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L898
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L1209
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L1270
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L2642
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L2661
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L2713
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L4317
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L4347
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L4579
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L4621
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L5203
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/json_handler.cpp#L5204

References I found that are written to logs:
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/wallet.cpp#L1172
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/wallet.cpp#L1188
https://github.com/nanocurrency/nano-node/blob/develop/nano/node/wallet.cpp#L1208

I only looked in `nano/node` and `nano/qt` for now.

**Comment by dsiganos** [comment]
Looks good.

**Comment by zhyatt** [comment]
Great, thanks @shryder ! This is a good start. Are you able to open up an RPC with the Qt wallet and logs changes?

As for the RPC changes, we could add an alias `receivable` to the `pending` RPC so either can be used, and mark `pending` as deprecated. I believe there are other alias' in the RPC calls as an example. We could also return the same values in a new `receivable` field on all the responses, leaving pending in place for backwards compatibility. Thoughts on making this change now to set the precedent @clemahieu, @dsiganos or others?

**Comment by dsiganos** [comment]
Having both pending and receivable return the same value and having pending marked as deprecated  sounds like a reasonable way forward to me. A lot of scripts will break if we suddenly remove pending.

**Comment by shryder** [comment]
@zhyatt yeah I can do that once I find a bit of time. I like the RPC change idea.

**Comment by shryder** [comment]
All above PRs are ready to be reviewed, let me know if there is something I should change
