### ISSUE TITLE
Run a node from source code

### ISSUE THREAD

**Issue by thedecentralized** [nanocurrency/nano-node#3423]
### Summary

Hey, how's it going?

I was wondering how I can run a node from source code (without docker), how can I do this?

Detail: I've been to all Nano's links, including this "https://docs.nano.org/integration-guides/build-options/"

### Node version

V22.1

### Build details

*

### OS and version

*

### Steps to reproduce the behavior

1.
2.
3.
...

### Expected behavior

*

### Actual behavior

*

### Possible solution

*

### Supporting files

*

**Comment by zhyatt** [comment]
Please see https://docs.nano.org/integration-guides/build-options/ for details on how to build the node from source. Are you planning a new integration with nano? We're always interested to hear about community projects.

**Comment by thedecentralized** [comment]
> Please see https://docs.nano.org/integration-guides/build-options/ for details on how to build the node from source. Are you planning a new integration with nano? We're always interested to hear about community projects.

I've tried it but it looks like this: //

I'm trying to "fork" but I can't even run node from the source code

![unknown](https://user-images.githubusercontent.com/83592440/129414724-18aab9fd-a705-4e57-9f93-17484408d4cd.png)
![unknown (1)](https://user-images.githubusercontent.com/83592440/129414723-4e1fade1-7629-4109-948d-1dec2be05bde.png)
![unknown (2)](https://user-images.githubusercontent.com/83592440/129414727-b5ced0ab-424f-4f5d-add6-879db21f5548.png)

**Comment by zhyatt** [comment]
It looks like you may have started the node ok, but perhaps you need to use `[::1]:7076` on your machine to connect to RPC.

Also, I see you have been trying to get help from Discord to make a fork of nano and launch your own project: https://discord.com/channels/370266023905198083/459677604669030400/875781135471378442. We don't provide support for these types of efforts so I will be closing this issue out, although you may continue to use the documentation and open source code as you see fit obviously.

**Comment by thedecentralized** [comment]
alright, thanks for the support :)
