### ISSUE TITLE
Add block confirmation status to blocks returned by `account_history`.

### ISSUE THREAD

**Issue by otonashixav** [nanocurrency/nano-node#3424]
### Summary

Currently, to get the confirmation status of blocks returned by `account_history`, `account_info` must be requested at the same time in order to infer block confirmation status based on confirmation height. It would be nice if `account_history` included confirmation status for each block. 

### What problem would be solved by this feature?

I'm writing a wallet which stores blocks locally. This feature would halve the number of calls required to sync accounts with a node.

### Are there any previous requests for this feature?

Not as far as I can tell. 

### Do you have a suggested solution?

Add an optional `confirmed` field to blocks in the response given by `account_history`. Looking at the rpc implementation, the confirmation height could be obtained in the same way it is for `account_info` then a `confirmed` field could be added. 

### If this feature is approved, would you be willing to submit a pull request with the solution?

I would not

**Comment by shryder** [comment]
I can work on this
