### ISSUE TITLE
`wallet_list` and `wallet_create` CLI broken on develop

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3447]
Both the `wallet_list` and `wallet_create` CLI commands are not working on the current develop branch as of commit 4e2ffe9993030e170b0f53ae579ac272f15402f1.

**Comment by dsiganos** [comment]
The problem is that this check fails:
`if (!ledger.block_or_pruned_exists (config.network_params.ledger.genesis->hash ()))`
https://github.com/nanocurrency/nano-node/blob/4e2ffe9993030e170b0f53ae579ac272f15402f1/nano/node/node.cpp#L357

**Comment by zhyatt** [comment]
Fixed by #3468
