### ISSUE TITLE
Add .to_string () debug method to each message type

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/nano-node#3451]

**Comment by keerifox** [comment]
was this solved by #3583?

**Comment by dsiganos** [comment]
No, PR #3583 didn't finish the job. It only started it. It only added `to_string()` to the class `nano::message_header`.

We also need `to_string()` methods for all the classes that extend `nano::message`, which are:
* nano::keepalive
* nano::telemetry_req
* nano::telemetry_ack
* nano::frontier_req
* nano::confirm_req
* nano::confirm_ack
* nano::node_id_handshake
* nano::bulk_push
* nano::bulk_pull
* nano::bulk_pull_account
* nano::publish

**Comment by dsiganos** [comment]
The message protocol is documented here:
https://github.com/nanocurrency/protocol/blob/main/reference/protocol.ksy

**Comment by dsiganos** [comment]
I suggest you start with the packet `nano::keepalive`. It is a simple message.
It contains a message header (which already has a to_string method) and an array of 8 ip addresses and ports.
The to_string method for keepalive just to print the message header plus the 8 IP addresses in a pretty and consise way.

**Comment by dsiganos** [comment]
A nice class to start with is `nano::keepalive`.

Here is how the output could look like (this is how xnolib prints it):
```
NetID: C, VerMaxUsingMin: 18/18/18, MsgType: 2(keepalive), Extensions: 0000
:::7075
:::0
::ffff:202.61.248.149:7075
::ffff:188.214.129.103:7075
::ffff:35.79.219.205:7075
::ffff:167.71.245.153:7075
::ffff:5.161.76.119:7075
::ffff:104.248.235.189:7075
```

**Comment by not-Ian** [comment]
working on this now, going to start with keepalive and verify it looks good, then move onto other classes
