### ISSUE TITLE
Document the new CLI commands initialize and debug_block_dump

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#3466]
Document the new CLI commands initialize and debug_block_dump.

**Comment by zhyatt** [comment]
@dsiganos Is this for documenting these in the code for https://github.com/nanocurrency/nano-node/pull/3465? I added a ticket for updating docs.nano.org here too: https://github.com/nanocurrency/nano-docs/issues/575

**Comment by dsiganos** [comment]
Yes, feel free to close this if you think it is redundant.

**Comment by zhyatt** [comment]
We typically mark PRs in this repository that need documentation updates with the `documentation` label and then open up an issue in the docs repo for the changes (or submitting a PR directly is fine) that references the original issue so you can see in the PR here the status of docs changes. Then near release we use the `documentation` label to double check things and verify they have either an open or completed issue/PR to cover them.
