### ISSUE TITLE
./nano_wallet --config rpc.enable=true crashes on linux

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#3494]
`./nano_wallet --config rpc.enable=true` crashes on linux (ubuntu 20.04)

On develop branch commit 1eefcaf70da5dd9b1f8e05f31ffd17478c827b2c

**Comment by KaffinPX** [comment]
It should closed i think.

**Comment by theohax** [comment]
> It should closed i think.

Right, got fixed by https://github.com/nanocurrency/nano-node/pull/3546. Closing this.
