### ISSUE TITLE
add a "threshold" and "head" parameter to the "delegators" rpc call

### ISSUE THREAD

**Issue by ghost** [nanocurrency/nano-node#3537]
### Summary

RPC call:
https://docs.nano.org/commands/rpc-protocol/#delegators

the delegators call doesn't have a threshold, so if there's many delegators, the node runs out of ram when processing the call.

the accounts_pending call has a "threshold", so I'd like delegators to behave like accounts_pending, and omit any delegator below a given threshold.

### What problem would be solved by this feature?

the node runs out of ram when processing the call if there are a lot of low weight delegators.

### Are there any previous requests for this feature?

no

### Do you have a suggested solution?

no

### If this feature is approved, would you be willing to submit a pull request with the solution?

I am willing to collaborate

**Comment by shryder** [comment]
It's going to be available on v23: https://github.com/nanocurrency/nano-node/pull/3333
