### ISSUE TITLE
Cementing during bootstrap on test network with V23.0RC1 is slow

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#3578]
It takes hours to bootstrap on the test network with V23RC1.
It is not clear if this is a regression because bootstrapping on the test network had been broken since August after switching on final votes.

I attach a detailed log of the bootstrap.

**Comment by dsiganos** [comment]
Link for log file:
https://dsiganos.nyc3.digitaloceanspaces.com/node-issues-3578.log.gz

**Comment by qwahzi** [comment]
Fwiw, I don't think it's a regression vs V22 or even earlier V23 beta builds. I tested bootstrapping in V23DB2 (and previous beta versions), and had the same slow bootstrap times I've been seeing on mainnet. It eventually finishes, it's just slow. Here's one example (V23DB2):

https://discord.com/channels/370266023905198083/769209197333053511/895648425264168970

V22 live bootstrapping issues:

https://github.com/nanocurrency/nano-node/issues/3294

**Comment by jamescoxon** [comment]
Seeing similar on a beta node I've been boot strapping for the last few days, currently I've cemented 20million blocks, the last 10million blocks have taken 80hrs  - running V23RC1.
<img width="1034" alt="screenshot8" src="https://user-images.githubusercontent.com/175479/144395607-4a55edf7-bff0-442f-82b3-2d56f2dfd44a.png">

One thing I've seen is that a node restart results in a brief episode of rapid cementing but doesn't last long before it settles back to the original slow rate.

**Comment by qwahzi** [comment]
Resolved by ascended bootstrap in V25.
