### ISSUE TITLE
Unit test `confirmation_height.election_winner_details_clearing` intermittently failing

### ISSUE THREAD

**Issue by theohax** [nanocurrency/nano-node#3608]
Disabled in https://github.com/nanocurrency/nano-node/pull/3607

CI run in which it failed: [here](https://github.com/nanocurrency/nano-node/runs/4513429321?check_suite_focus=true#step:5:3401)

**Comment by qwahzi** [comment]
@dsiganos - Here is another that appears to be resolved by linked PRs, and can be closed:

https://github.com/nanocurrency/nano-node/pull/3741

https://github.com/nanocurrency/nano-node/pull/3679#issuecomment-1022213638
