### ISSUE TITLE
Unit test `network.send_node_id_handshake` intermittently failing

### ISSUE THREAD

**Issue by theohax** [nanocurrency/nano-node#3612]
Disabled in https://github.com/nanocurrency/nano-node/pull/3611

CI run in which it failed: [here](https://github.com/nanocurrency/nano-node/runs/4525973902?check_suite_focus=true#step:6:922)

**Comment by thsfs** [comment]
Closing this together with UDP support removal (https://github.com/nanocurrency/nano-node/issues/3846).
