### ISSUE TITLE
RPC: `account_info` returns wrong data in `representative_block`

### ISSUE THREAD

**Issue by justdmitry** [nanocurrency/nano-node#3668]
### Summary

RPC call `account_info` returns `representative_block` where block ID of last representative change is expected. But it returns same value as in `frontier` field.

### Node version

Nano V22.1

### Build details

Docker

### OS and version

Ubuntu 20.04

### Steps to reproduce the behavior

Run `curl -d '{"action":"account_info", "account":"nano_1just1zdsnke856mu5pmed1qdkzk6adh3d13iiqr3so66sr8pbcnh15bdjda"}' [::1]:7076`

Returned response:
```
{
    "frontier": "EA154802D321F1BDA44C361B00301DD04D375D3B2622E09A326A3B8109B62F76",
    "open_block": "51737DB38EE2B556FD5DC90C8CA4D6E9798784F8A24390DD741DB7F9BD45D08D",
    "representative_block": "EA154802D321F1BDA44C361B00301DD04D375D3B2622E09A326A3B8109B62F76",
    "balance": "4303629517094011030912161691",
    "modified_timestamp": "1598499180",
    "block_count": "13",
    "account_version": "2",
    "confirmation_height": "13",
    "confirmation_height_frontier": "EA154802D321F1BDA44C361B00301DD04D375D3B2622E09A326A3B8109B62F76"
}
```

### Expected behavior

`representative_block` must contain `D63B690BB29C205E44AF1671426A28C0F2731361FA73ACD171B4EF3900AAF0FF` (block where representative was actually set).

### Actual behavior

`representative_block` equal to `frontier` (`EA154802D321F1BDA44C361B00301DD04D375D3B2622E09A326A3B8109B62F76`) - 11 blocks later.

**Comment by clemahieu** [comment]
It's not incorrect for the representative_block field to be the frontier.

**Comment by justdmitry** [comment]
Yes, when frontier was "change" block.
But currently it always equal to frontier. In my sample frontier is epoch, while repchange happened 10 block before.

**Comment by clemahieu** [comment]
This field is set to the last block in which a representative was set which is every block for state/epoch blocks.

**Comment by justdmitry** [comment]
Isn't original idea of this field is to have "link" to block where ***user*** changed his rep, not to block where node/protocol last "not changed" it? So client who want to know when/where account updated to actual rep can do this with one call, instead of traversing unlimited `account_history` searching for block with subtype=change?

Currently, this field is duplicate and useless.

**Comment by clemahieu** [comment]
Similar. It's not there for user convenience, it's used in ledger processing specifically rollback for legacy blocks for the reason you mentioned.

That does make it not useful post state blocks but it's not incorrect. We could de-duplicate it and only store when it's actually changed but that's not the current intent.

**Comment by clemahieu** [comment]
Technically we should be moving representative in to sideband and handle it similar to how we do with account/balance fields. Then we could eliminate this field from the account_info table.

Unfortunately that requires a rewrite of the block table which isn't the easiest but doable.
