### ISSUE TITLE
bootstrap_boost.sh -> Boost has moved downloads to JFrog Artifactory

### ISSUE THREAD

**Issue by humble-nano** [nanocurrency/nano-node#3695]
Hi,

the sourceforge links are still working but who knows when they will shut it down or newer versions are only released via jfrog.io. If the files on sorceforge are getting deleted the builds will break.

https://github.com/nanocurrency/nano-node/blob/f308f403b4da00021939919ea5b9f7ab16e88246/util/build_prep/bootstrap_boost.sh#L88

i can prepare a PR if you like.

```
Boost has moved downloads to JFrog Artifactory

April 29th, 2021 18:00 GMT

The service that Boost uses to serve up its releases, Bintray.com is being retired by JFrog on the 1st of May. Fortunately for Boost, they have a new service, called JFrog.Arifactory, which we have transitioned to.

For the users of Boost, the only difference is that there is a new URL to download releases and snapshots.

Instead of: https://dl.bintray.com/boostorg/release/ you should use https://boostorg.jfrog.io/artifactory/main/release/ to retrieve boost releases.

Note: The pre-1.64 Boost releases are still available via Sourceforge.

Thank you to JFrog for all your past and current support.
```
https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html

**Comment by dsiganos** [comment]
Nano should have its own archive repository where all the dependencies it needs are kept safely.
Our build processes should be directly looking for resources outside of our domain of control.

**Comment by zhyatt** [comment]
@humble-nano Thanks for highlighting. We will look into options further for archiving on our end per @dsiganos comments, but is there any indication that Sourceforge has plans to drop support for Boost releases? The recommendation here is to not use bintray.com which we already don't. Just trying to make sure we understand the situation clearly.

**Comment by humble-nano** [comment]
@zhyatt wild guess from my side, Boost used Sourceforge for a long time and moved to bintray (now artifactory by jfrog). they wanted to deprecate Sourceforge but can't because they know that they have a high download rate from travis and so on and they don't want to break users automation. 

Now they maintain artifactory and Sourceforge but i don't think they will do it for long.

you can look into maintaining your own artifactory online, it's free for open source projects and you could use it as cheap linux repositories for the .deb and .rpm packages. 

btw.  Sourceforge is slow, that was the reason for me to check the boost website for a mirror.

**Comment by dsiganos** [comment]
@humble-nano We do not have the capacity to look into this now.
Is this something you could help us with, maybe?

Ideally, we want to have a server/service/something, where all our third party dependencies are stored, in way that we own and manage.

**Comment by humble-nano** [comment]
yeah this is exactly what an artifact resolver is for (like artifactory) i could help you to set one up, we could start with exactly this boost dependency and slowly mirgate all external libaries to this resolver. 

i will look into the JFrog Artifactory first, i used bintray myself a few years ago. If i have the ok. I probably need your email addresses to add more owner to the project, just ping me via discord (krux0r#9338).

**Comment by humble-nano** [comment]
```https://nanocurrency.jfrog.io/artifactory/boost/1.70.0/source/boost_1_70_0.tar.bz2```

that was  easy :)

https://nanocurrency.jfrog.io/ui/native/boost/

**Comment by dsiganos** [comment]
Hi @humble-nano, it looks like you created a nanocurrency domain inside jfrog.
That is nice but it is not fixing the problem of depending on third party service.
Nanocurrency would still have to depend on jfrog to stay in business and continue to offer its services.
Nanocurrency should have its own archive service that it controls.
I wonder if just another git repo be good enough, although that's not what git was designed to be.

**Comment by humble-nano** [comment]
ok i see @dsiganos, that was not clear to me before. i mean, you can use artifactory "as a service" or host it by yourself. but you could also just use your own webserver and rsync the content of the boost folder to your server and activate directory listening in the webserver config, as you are using a sinple wget for the boost source for example.

it depends on to what degree you want to be independent, i mean you could also just have a local copy of everything and if jfrog is dead you can just spin up a differnt server. it is the same what you would do if github is closing tomorrow.

maybe you could think about **what** you want and then let's see **how** to implement it and maybe i can help with a few things, maybe not.

**Comment by dsiganos** [comment]
We want to not have to depend on a third party to store artifacts that are important for us.

Github is not a good example to compare because everything that is on github can be reconstructed even if github disappears tomorrow. The same cannot be said with the same confidence for old archives that are hosted on a third party and we depend on.

The reality is that this issue is a low priority for us at the moment and we do not seem to have a clear path forward, so let's park it for now.

**Comment by humble-nano** [comment]
"everything that is on github can be reconstructed even if github disappears tomorrow"

that was exacly my point. you could do the same with e.g boost 
https://github.com/boostorg/boost/releases/tag/boost-1.70.0

"The reality is that this issue is a low priority for us at the moment and we do not seem to have a clear path forward, so let's park it for now."

ok let's park this decision but what about sourceforge? it's slow and not an official repository and you rely on that,right now. it's worse that relying on an official repository of the libary.

**Comment by dsiganos** [comment]
No, it is not the same as guthub. With github, we have the history of everything going back.
