### ISSUE TITLE
account_filter not working on account_history

### ISSUE THREAD

**Issue by ArTombado** [nanocurrency/nano-node#3712]
### Summary

I have a bot in telegram that show how much 2miners is buying everyday, i was using https://www.bitrequest.app:8020/ to receive the history of payments. 
But something went wrong with the bot, after some investigation i discovered that the response was returning wrong information. 
Then i tried the same request with https://proxy.powernode.cc/proxy and i received the same wrong response(both powernode and bitrequest node are in V23). 
When i tried the request with https://vault.nanocrawler.cc/api/node-api (which is in V22) i received the expected response.

### Node version

V23

### Build details

No info

### OS and version

No info

### Steps to reproduce the behavior

1. make this request in a V23 node:
```
{
  "action": "account_history",
  "account": "nano_14uzbiw1euwicrt3gzwnpyufpa8td1uw8wbhyyrz5e5pnqitjfk1tb8xwgg4",
  "count": "1",
  "account_filter": ["nano_3cpz7oh9qr5b7obbcb5867omqf8esix4sdd5w6mh8kkknamjgbnwrimxsaaf", "nano_3jwrszth46rk1mu7rmb4rhm54us8yg1gw3ipodftqtikf5yqdyr7471nsg1k"]
}
```

### Expected behavior

The node should return 
```
{
   "account":"nano_14uzbiw1euwicrt3gzwnpyufpa8td1uw8wbhyyrz5e5pnqitjfk1tb8xwgg4",
   "history":[
      {
         "type":"receive",
         "account":"nano_3cpz7oh9qr5b7obbcb5867omqf8esix4sdd5w6mh8kkknamjgbnwrimxsaaf",
         "amount":"62711432000000000000000000000000000",
         "local_timestamp":"1644061519",
         "height":"1067132",
         "hash":"4819E7639366307F3DF0F79FBECAC84F96C6DB09BDE9EF3709BBEA46C70AA020",
         "timestamp":"1644061520102"
      }
   ],
   "previous":"7736934314943CA7A22F7A561AA9ABA374019AFCC8177A2C852670DBEAEAEF84"
}
```

(returned successfully with https://vault.nanocrawler.cc/api/node-api)

### Actual behavior

The node return
```
{
   "account":"nano_14uzbiw1euwicrt3gzwnpyufpa8td1uw8wbhyyrz5e5pnqitjfk1tb8xwgg4",
   "history":[
      {
         "type":"send",
         "account":"nano_3aocwfocb6jpjef4x43z77wm7zebnu7n7dzqiuyebrkz3cuobsjy7q7zourm", //this account is not in account_filter
         "amount":"4269657600000000000000000000000",
         "local_timestamp":"1644063962",
         "height":"1078273",
         "hash":"15AA482D6E291D1134355E5B0CF0B4F0686E8A90BD62E34BC808EC7FB0CE9C5C",
         "confirmed":"true"
      }
   ],
   "previous":"0EF242D668C26187A26938CCFCC6DAAFC6E102539DBC04E84F5DDB26BC9583E6"
}
```
(both powernode and bitrequest node returned this response)

**Comment by shryder** [comment]
I believe this is related to the proxy that those nodes use, not the RPC itself:

https://github.com/Joohansson/NanoRPCProxy/blob/819daa75146876b50360c010a0c3e5cb5327a8d5/src/proxy.ts#L830

**Comment by ArTombado** [comment]
> I believe this is related to the proxy that those nodes use, not the RPC itself:
> 
> https://github.com/Joohansson/NanoRPCProxy/blob/819daa75146876b50360c010a0c3e5cb5327a8d5/src/proxy.ts#L830

Oh, i didn't know about this, thanks for the fast response! I will close the issue then.
