### ISSUE TITLE
unchecked.multiple_get failed in CI

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#3737]
[ RUN      ] unchecked.multiple_get
/workspace/nano/core_test/block_store.cpp:468: Failure
Expected equality of these values:
  unchecked1_blocks.size ()
    Which is: 0
  3
[  FAILED  ] unchecked.multiple_get (499 ms)

https://github.com/nanocurrency/nano-node/runs/5168846382?check_suite_focus=true#step:6:316

Linux test with ROCKSDB

**Comment by dsiganos** [comment]
I wonder if this unit test is making assumptions about ROCKSDB.
For example ROCKSDB, does not return accurate count values.

**Comment by dsiganos** [comment]
I can make this fail on my computer like this:
```
TEST_USE_ROCKSDB=1 ./core_test --gtest_filter=unchecked.multiple_get --gtest_repeat=1000 --gtest_break_on_failure
```

**Comment by dsiganos** [comment]
Thoughts:
* is it safe to call unchecked.count() when using ROCKSDB?
* is there a background process that will remove the blocks from the unchecked table?
* the blocks are constructed using probably some kind of pattern but I a not what that pattern is and what its purpose is
* why is the test adding a block into the unchecked table with itself as a dependency?
  `unchecked.put (block1->hash (), block1); `

**Comment by qwahzi** [comment]
It seems like you've already documented it well above, but just in case other people are reading this, I believe this issue is the same (or at least related) issue noted in the V22 known issues list (unchecked count can be 10,000+ while you're actually still synced according to cemented):

> Known issue with RocksDB: RPC unchecked_keys not working properly

> Issue: The RPC unchecked_keys is returning 0 for all calls when used with the RocksDB backend. This known issue will be resolved in a future release. 

> Solution: Until the issue is resolved any integrations using this command should remain on the existing LMDB backend

https://docs.nano.org/releases/release-v22-0/
