### ISSUE TITLE
Crypto.com not update their token name, transaction stuck

### ISSUE THREAD

**Issue by sublingualwart** [nanocurrency/nano-node#3743]
### Summary

Hello. I've sent some nanos from my natrium wallet to crypto.com since they have the token and a wallet available. 
But after checking on explorer, saw the transaction got stuck. 
The wallet they created: 
nano_33hooxxs6fyhobm6zpw1ampwktd7h4pf9wtnjdtfj95z34ngxkd3my9ph87o
and after talking to them, realized they didn't upgrade their listings for the new name, so the wallet is not getting anything. 

### What problem would be solved by this feature?

Theres any way I can have the transaction back to my natrium or its stuck there forever? 

### Are there any previous requests for this feature?

Not find anything. 

### Do you have a suggested solution?

I've tried, but i'm a lone wolf. Reaching their team and talking about upgrading the token name on the platform could solve problems to lots of other nano users too! OR any kind of backpath to wallets that are not supposed to get old nanos anymore. And making sure they will keep the wallets address intact. too, not sure if any of this would help, but I'm thinking not only on my problem but on other people who may have it too. 

### If this feature is approved, would you be willing to submit a pull request with the solution?

I am willing to collaborate

**Comment by clemahieu** [comment]
This space is only for node related issues.
