### ISSUE TITLE
Nano's CLI --help should display options in alphabetic order

### ISSUE THREAD

**Issue by ealtamir** [nanocurrency/nano-node#3748]
### Summary

Explained in the title

### What problem would be solved by this feature?

The current order has poor usability making it harder to find what one is looking for. 

### Are there any previous requests for this feature?

I believe not.

### Do you have a suggested solution?

Sort the options in alphabetic order.

### If this feature is approved, would you be willing to submit a pull request with the solution?

I would not

**Comment by Justin-Randall** [comment]
I can get a PR together for this. This is a nice touch for programs with lots of options (as nano_node does, for example).
