### ISSUE TITLE
Change the confirmation_height_clear option to require the account argument

### ISSUE THREAD

**Issue by thsfs** [nanocurrency/nano-node#3831]
For safety, the confirmation_height_clear should be changed to require an account argument. This argument should have either an account number or `"all"`, to specify the confirmation height of all accounts will be cleaned;

**Comment by qwahzi** [comment]
This one looks like it was also completed already. Tagging @dsiganos for review

**Comment by dsiganos** [comment]
Resolved by https://github.com/nanocurrency/nano-node/pull/3836
