### ISSUE TITLE
RFC: New GUI implementation

### ISSUE THREAD

**Issue by rainbyte** [nanocurrency/nano-node#384]
I have been writing an unofficial new GUI implementation for RaiBlocks wallet using Qt Quick, code is published [here](https://github.com/rainbyte/raiblocks/tree/qml_gui).

Recently I uploaded it, after decent level of supported features was reached (reddit post [here](https://www.reddit.com/r/RaiBlocks/comments/7moghd/implementing_new_gui/)).

Some parts remain missing, but I'm adding them and rebasing from official repo.

If this could be reviewed and merged, maybe it could improve user experience.

These are some issues which could be solved with new implementation: #78 #254 #132 #1 #383 

Thanks in advance for reading this!

**Comment by soliury** [comment]
good job

**Comment by cryptocode** [comment]
@rainbyte Cool. The work I'm going to do on QR code support should be self contained enough to work in your case as well.

**Comment by dannyvankooten** [comment]
I'm not a Raiblocks maintainer or contributor but I really like how this looks. Great work @rainbyte! 

I reckon the devs would like a pull request for this with details on what exactly is still missing? That will make it a lot more likely for this to get merged, I think.

**Comment by rainbyte** [comment]
Only the functionality inside "advanced" and "import" submenus is missing, but old submenus are shown in a separate window as workaround.

I mean, I have ported piece by piece keeping the missing parts intact in a 2nd window, always available.

This was the only way, because QtWidgets cannot be used inside Qml ApplicationWindow.

**Comment by rainbyte** [comment]
@cryptocode I tried to integrate [this](https://github.com/nayuki/QR-Code-generator) qr lib, but I had no luck with it yet. Great to know you are working on that :D

**Comment by cryptocode** [comment]
@rainbyte yeah, I have a working prototype

**Comment by rainbyte** [comment]
@cryptocode , I have found [this](https://github.com/Acce0ss/qqr.js) qrcode library and to my surprise it worked!

Maybe not for the long term, but it is useful to fill the gap while you finish your version.

Also, [this](https://github.com/neocotic/qrious) is a rewrite of the library above, but not yet available for Qml.

**Comment by pocesar** [comment]
I was going to do it using electron, but you beat me to it hahaha, looks much better

**Comment by donutloop** [comment]
That looks pretty good!

**Comment by Syd** [comment]
I thought about doing the same, but wondered if work had already begun to port it to quick for the mobile client?

**Comment by rainbyte** [comment]
@Syd , I think this is a good start for android port. Maybe qmake .pro should be added too, because it is not easy to generate android build with cmake right now.
