### ISSUE TITLE
Improve polymorphism in `rep_crawler::cleanup_reps()`

### ISSUE THREAD

**Issue by simpago** [nanocurrency/nano-node#3946]
### Broken Polymorphism
The method `rep_crawler::cleanup_reps()` is responsible for removing representatives that have inactive channels.
The problem is that a `channel` cannot be asked whether it is closed, so rep_crawler checks for the concrete type of the channel and asks for example `tcp_channels` whether that channel still exists. Checking the concrete type of the channel breaks polymorphism!

Here is the relevant code snippet:
```
void nano::rep_crawler::cleanup_reps ()
{
	std::vector<std::shared_ptr<nano::transport::channel>> channels;
	{
		// Check known rep channels
		nano::lock_guard<nano::mutex> lock (probable_reps_mutex);
		auto iterator (probable_reps.get<tag_last_request> ().begin ());
		while (iterator != probable_reps.get<tag_last_request> ().end ())
		{
			if (iterator->channel->get_tcp_endpoint ().address () != boost::asio::ip::address_v6::any ())
			{
				channels.push_back (iterator->channel);
				++iterator;
			}
			else
			{
				// Remove reps with closed channels
				iterator = probable_reps.get<tag_last_request> ().erase (iterator);
			}
		}
	}
	// Remove reps with inactive channels
	for (auto const & i : channels)
	{
		bool equal (false);
		if (i->get_type () == nano::transport::transport_type::tcp)
		{
			auto find_channel (node.network.tcp_channels.find_channel (i->get_tcp_endpoint ()));
			if (find_channel != nullptr && *find_channel == *static_cast<nano::transport::channel_tcp *> (i.get ()))
			{
				equal = true;
			}
		}
		else if (i->get_type () == nano::transport::transport_type::udp)
		{
			auto find_channel (node.network.udp_channels.channel (i->get_endpoint ()));
			if (find_channel != nullptr && *find_channel == *static_cast<nano::transport::channel_udp *> (i.get ()))
			{
				equal = true;
			}
		}
		else if (i->get_type () == nano::transport::transport_type::fake)
		{
			equal = true;
		}
		if (!equal)
		{
			nano::lock_guard<nano::mutex> lock (probable_reps_mutex);
			probable_reps.get<tag_channel_ref> ().erase (*i);
		}
	}
}
```

### Possible Solution
A possible fix for this design issue could be the following:
`tcp_channels` currently removes inactive channels in its `purge (...)` method. It however does _not_ change the state of the channel.

A better design would be, if `tcp_channels::purge()` would actually close the channel and if there was a `channel::is_closed()` method. `rep_crawler` could then just ask the channel whether it is closed and it would not need to know the channel type. The resulting `cleanup_reps()` method could look like this:

```
void nano::rep_crawler::cleanup_reps ()
{
		// Check known rep channels
		nano::lock_guard<nano::mutex> lock (probable_reps_mutex);
		auto iterator (probable_reps.get<tag_last_request> ().begin ());
		while (iterator != probable_reps.get<tag_last_request> ().end ())
		{
			if (iterator->channel->is_closed ())
			{
				// Remove reps with closed channels
				iterator = probable_reps.get<tag_last_request> ().erase (iterator);
			}
		}
}
```

**Comment by brandon-bb** [comment]
Currently working on this. From my current understanding, the deterministic features of a dead channel would be that the socket is closed and the channel no longer holds a reference to the node. A possible solution could be that we use a shared_ptr for the node as opposed to a raw reference, allowing us to manage the lifetime of it.

**Comment by dsiganos** [comment]
Not relevant anymore after the rep_crawler overhaul and recent networking improvements.
