### ISSUE TITLE
Instructions for setting up a Windows 11 machine and Visual Studio 2022 capable of building nano node s/w.

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#4033]
It would be nice to have instructions for setting up a windows 11 machine with software needed to build the nano software.

**Comment by dsiganos** [comment]
@RickiNano will work on this.

**Comment by dsiganos** [comment]
Precursor task to #4032

**Comment by RickiNano** [comment]
I've just finished setting up the Nano solution on Windows 11 (64 bit enterprise) and Visual studio 2022 (17.1.6). I have also compiled the executables successfully
I followed my original guide all the way, except that in Cmake I picked Visual Studio 17 2022 instead of VS2019
