### ISSUE TITLE
Convert boost::filesystem references to std::filesystem

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/nano-node#4057]
std::filesystem is supported as of C++17, replace usages of boost::filesystem with std::filesystem.

**Comment by meyediri** [comment]
I would like to take this one

**Comment by RickiNano** [comment]
@qwahzi 
This issue can be closed now
There is also a very old PR #4183 that can also be closed

**Comment by qwahzi** [comment]
Awesome, thank you Ricki!
