### ISSUE TITLE
Compiling load_test on windows fails

### ISSUE THREAD

**Issue by RickiNano** [nanocurrency/nano-node#4061]
### Summary

Using Visual studio 2019 to compile the current develop branch with the test projects included will fail with the following three error messages:
`Error	LNK2019	unresolved external symbol jump_fcontext referenced in function "public: void * __cdecl boost::coroutines::detail::coroutine_context::jump(class boost::coroutines::detail::coroutine_context &,void *)" (?jump@coroutine_context@detail@coroutines@boost@@QEAAPEAXAEAV1234@PEAX@Z)	load_test	C:\Users\***\Documents\NanoBinaries\nano\load_test\boost_coroutine.lib(coroutine_context.obj)	1	
Error	LNK2019	unresolved external symbol make_fcontext referenced in function "public: __cdecl boost::coroutines::detail::coroutine_context::coroutine_context(void (__cdecl*)(struct boost::context::detail::transfer_t),struct boost::coroutines::detail::preallocated const &)" (??0coroutine_context@detail@coroutines@boost@@QEAA@P6AXUtransfer_t@1context@3@@ZAEBUpreallocated@123@@Z)	load_test	C:\Users\***\Documents\NanoBinaries\nano\load_test\boost_coroutine.lib(coroutine_context.obj)	1	
Error	LNK1120	2 unresolved externals	load_test	C:\Users\***\Documents\NanoBinaries\Release\load_test.exe	1	`

The error seems to have appeared after the Boost link targets were changed in this commit:
https://github.com/nanocurrency/nano-node/commit/d8fa4b7bebee9a371af949854f30e97801cfe0c7

### Node version

v25db7

### Build details

Build using these instructions:
https://github.com/nanocurrency/nano-node/files/10362594/Nano_windows_install.pdf
This has worked fine before

### OS and version

Windows 10

### Steps to reproduce the behavior

1. Pull develop branch
2. Run cmake and include test project
3. open in VS2019 and compile

### Expected behavior

No compile errors

### Actual behavior

Three errors are outputted

### Possible solution

It seems like it has something to do with boost coroutine. 
Apparently the order that it is included matters: https://stackoverflow.com/a/17883184

**Comment by clemahieu** [comment]
Is this cross compiling from Windows on an Apple silicon chip to x64?

I've seen a similar issue but looking at load_test it seems like the only project with the issue. We added some boost coroutine functions in load test but they've been superseded by C++20 now.

In the mean time we should rewrite the boost::spawn and boost::yield_context code and replace it with standard callback code as is in the node elsewhere. This will remove the dependency on boost context entirely.

**Comment by RickiNano** [comment]
It's not cross compiled. It's compiled on an Intel I7 8700K.

**Comment by RickiNano** [comment]
This issue has been resolved in current develop branch. Most likely because of this PR:
https://github.com/nanocurrency/nano-node/pull/4140
