### ISSUE TITLE
accounts_balances returns error on unopened blocks

### ISSUE THREAD

**Issue by fossephate** [nanocurrency/nano-node#4064]
### Summary

Seemingly starting in v24, on multiple nodes, querying an unopened block with `accounts_balances` returns:
`"error": "Account not found"`
The same block queried with `account_balance` returns as expected

### Node version

v24RC2

### Build details

N/A

### OS and version

Windows, Linux

### Steps to reproduce the behavior

1. Send a block to a new, unopened address
2. Call `accounts_balances` on the address

### Expected behavior

https://docs.nano.org/commands/rpc-protocol/#accounts_balances

### Actual behavior

```
{
    "balances": {
        "nano_37rc7hmpbhaxiiuycptn9shusdiefzwbmh6qj4mcfzex98idmqd4rtm9pkum": {
            "error": "Account not found"
        }
    }
}
```

### Possible solution

This appears to be a bug related to changes introduced in v24, as the issue doesn't appear to be present in v23.3 nodes

### Supporting files

Example account / RPC calls:

```
{
  "action": "account_balance",
  "account": "nano_37rc7hmpbhaxiiuycptn9shusdiefzwbmh6qj4mcfzex98idmqd4rtm9pkum"
}
```

```
{
  "action": "accounts_balances",
  "accounts": ["nano_37rc7hmpbhaxiiuycptn9shusdiefzwbmh6qj4mcfzex98idmqd4rtm9pkum"]
}
```

**Comment by RickiNano** [comment]
It is most likely this commit that caused the problem:
https://github.com/nanocurrency/nano-node/commit/580c3c1af562cd72bc50afbe9637bbab60dd9894

**Comment by qwahzi** [comment]
Fix merged and planned for V25:

https://github.com/nanocurrency/nano-node/pull/4075
