### ISSUE TITLE
Re-write nano::election::vote in a more readable way

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#4108]
Re-write the method `nano::election::vote` in a cleaner more readable style using guard if statements with early exits to avoid the deeply nested if blocks. Also, convert the expression 
`last_vote_l.timestamp < timestamp_a || (last_vote_l.timestamp == timestamp_a && last_vote_l.hash < block_hash_a)`
to be more easily readable by using multiple if statements.

**Comment by JerzyStanislawski** [comment]
I'll take a look at this.
