### ISSUE TITLE
Threshold param in account_history

### ISSUE THREAD

**Issue by VrtclDev** [nanocurrency/nano-node#4170]
### Summary

i'd love to have the "threshold" parameter in the rpc call "account_history", it seems pretty useful

### What problem would be solved by this feature?

Yep, like for example if you're getting account history, you wouldnt have to filter results client-sided, this can also help with bandwidth if you're fetching in high amounts, which is the reason why im requesting the feature

### Are there any previous requests for this feature?

im not sure

### Do you have a suggested solution?

Im also not sure what to type here

### If this feature is approved, would you be willing to submit a pull request with the solution?

I would not

**Comment by thsfs** [comment]
This is already implemented. You can use the field `count` as a threshold. Also, you can use the field `offset` to skip the first N results.

You can find more info here: https://docs.nano.org/commands/rpc-protocol/#account_history
