### ISSUE TITLE
server-side filtering

### ISSUE THREAD

**Issue by VrtclDev** [nanocurrency/nano-node#4171]
### Summary

If i call "block_info" only to get the subtype, i dont need to get the amount sent, the block sender, and the signature
I'd love to see a feature that allows you filter the results like so

{action:"block_info", block:"AB37E2...", "filter_for":["subtype"]}

### What problem would be solved by this feature?

Many apps built for nano make rpc calls only to use a small amount of the data given by the RPC
This can increase bandwidth usage for both the client-side and the server-side, implementing filtering can be less wasteful, and technically, it would be more "eco-friendly"

### Are there any previous requests for this feature?

Not sure

### Do you have a suggested solution?

nope, but i'd assume it would be pretty easy to implement

### If this feature is approved, would you be willing to submit a pull request with the solution?

I am willing to collaborate

**Comment by clemahieu** [comment]
Adding node-side filtering increases complexity and all of our RPC plans are to decrease complexity.
