### ISSUE TITLE
I have a compilation error (threading.hpp)

### ISSUE THREAD

**Issue by MyEcoria** [nanocurrency/nano-node#4224]
### Summary

I wanted to compile the V25 version of the node for testing and I have an error that I tried to correct without success

### Node version

V25

### Build details

Built with all documentation recommendations

### OS and version

In github codespace

### Steps to reproduce the behavior

1.
2.
3.
...

### Expected behavior

It's a problem in the build

### Actual behavior

There is an error at 31% of the compilation

### Supporting files

In file included from /workspaces/nano_build/nano/lib/plat/linux/thread_role.cpp:1:
/workspaces/nano_build/nano/lib/threading.hpp:73:7: error: ‘latch’ in namespace ‘std’ does not name a type
   73 |  std::latch thread_names_latch;
      |       ^~~~~
make[3]: *** [nano/lib/CMakeFiles/nano_lib.dir/build.make:104: nano/lib/CMakeFiles/nano_lib.dir/plat/linux/thread_role.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:2878: nano/lib/CMakeFiles/nano_lib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2994: nano/nano_node/CMakeFiles/nano_node.dir/rule] Error 2
make: *** [Makefile:774: nano_node] Error 2

**Comment by thsfs** [comment]
@MyEcoria , std::latch is a C++20 feature. What is the compiler you are using and its version?

**Comment by MyEcoria** [comment]
For node compilation, I used these commands:
`cmake -G "Unix Makefiles" .`
`make nano_node`

All software is up to date, and I built the node 2-3 weeks ago and it worked but now it doesn't

![nano_node_error](https://user-images.githubusercontent.com/103332030/236385740-e9d44835-ecb1-4898-b3a5-07731ec9908d.png)

**Comment by pwojcikdev** [comment]
Looks like GitHub Codespaces by default spins up Ubuntu 20.04 instance, make sure to change that to 22.04.

**Comment by MyEcoria** [comment]
Ok thank you 🙃

**Comment by sac1978** [comment]
Just going to add I had this issue on a Ubuntu 20.04 VM and solved it by installing G++11 following these instructions https://lindevs.com/install-g-on-ubuntu/
