### ISSUE TITLE
Improve assert statements of unit tests

### ISSUE THREAD

**Issue by dsiganos** [nanocurrency/nano-node#4364]
We have many assert statements in unit test that are checking for equality like this:

ASSERT_TRUE(a == b)
or
ASSERT_TIMELY(5s, a == b)

They should be converted to:
ASSERT_EQ(a, b)
and
ASSERT_TIMELY_EQ(5s, a, b)

**Comment by RickiNano** [comment]
I'd like to take this one

**Comment by dsiganos** [comment]
Great, it's yours!

**Comment by RickiNano** [comment]
@dsiganos 
Do you want a line like this:
`ASSERT_TRUE (node.weight (key1.pub) == amount && node.weight (key2.pub) == amount && node.weight (key3.pub) == amount);`
To be changed into 3 ASSERT_EQ (one for each of the ANDed parts), or should I just leave them?

**Comment by dsiganos** [comment]
Splitting that one makes sense.

**Comment by RickiNano** [comment]
Hey @dsiganos 
I've created a PR for this. I made a small program that automated the process.
If you have more similar changes that you want me to do, I can easily modify the program

**Comment by dsiganos** [comment]
You could also convert (they are less valuable but still good to do):
* ASSERT_TRUE (a > b) -> ASSERT_GT(a, b)
* ASSERT_TRUE (a >= b) -> ASSERT_GE(a, b)
* ASSERT_TRUE (a < b) -> ASSERT_LT(a, b)
* ASSERT_TRUE (a <= b) -> ASSERT_LE(a, b)
Create 4 different commits for each type so that the review is easier to do.
