### ISSUE TITLE
API should provide message signing and signature verification

### ISSUE THREAD

**Issue by brenzi** [nanocurrency/nano-node#447]
In order to allow secondary use cases on top of rai, I'd need message signing/verification functionality for my addresses, similar to web3.eth.sign in ethereum

**Comment by androm3da** [comment]
This is a good idea, thanks.

**Comment by zhyatt** [comment]
After implementation of https://github.com/nanocurrency/nano-node/pull/1241 and further discussions we are keeping the limits of signing through the node at just the block and hash to minimize maintenance and risk of supporting signing of arbitrary data. Other signing algorithms can be used and 2nd layer options created to satisfy any use cases.
