### ISSUE TITLE
False positive Antivirus warnings (Windows)

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/nano-node#45]
https://www.virustotal.com/en/file/eec78b3ddbbcce2d78e1a876f1e4d4e87d9d7af16beebb297aeecc43103f4dd4/analysis/1485585242/
Most likely caused by NSIS installer.
Possible solution: additional zip archive Windows binaries without installer

**Comment by SergiySW** [comment]
Likely can be solved with signing windows installer (same as NanoWalletCompany)

**Comment by argakiig** [comment]
https://www.virustotal.com/#/file/6309905da8d763bb3c5e6363963f85add782ec238459e78ade23f2e6b8677b8e/detection latest release does not trigger any alerts, This may be due to an update to NSIS, we are still working on getting code signing to not set off smart screen alerts for windows
