### ISSUE TITLE
Users must store their own account chains

### ISSUE THREAD

**Issue by dylan1951** [nanocurrency/nano-node#4673]
### Summary

Nodes aren't paid to do their job. Therefore we should offload as much work from them as possible.

#### Changes
- Users/wallets must store their own account chains.
- Nodes only store Merkle roots.

#### Benefits:
- Spam is solved.
- Nano becomes a privacy coin.
- Lessened node operating costs.
- Increased scalability and security.

### What problem would be solved by this feature?

Ledger bloat is a significant issue facing nano. If the nano main network were to scale up to 2200 CPS a spammer could bloat the ledger by up to 1TB in a single month. This would be devastating for nano especially due to the lack of inherent financial reward for nodes, potentially leading to extreme centralisation.

Proof-of-work offers no defence against this kind of attack. By my rough calculations a single one of these https://bitcoinmerch.com/products/obelisk-sc1-immersion could do the proof-of-work to produce 2200 blocks per second.

The current defence strategy is to limit the throughput of the network by throttling bandwidth. During a spam attack, prioritisation mechanisms allow for “legitimate” transactions to still be confirmed while keeping the throughput low. This bounds the ledger bloat to an amount that would not be devastating to the network and is therefore not worth the cost for spammers to saturate.

This strategy is not ideal. In order for nano to scale with adoption it requires node operators to manually adjust the networks throughput such that it remains proportional to the “real-world usage”. If this rate were too high the ledger bloat could be devastating. If it were too low the network wouldn’t handle the “real” demand and so would be unusable and deemed a complete failure.

There is no clear definition of “real-world usage” or “real” demand, neither is there any way to quantify the proportion of transactions that match this criteria. It is accepted that “spam” transactions are not “real” demand and thus nano shouldn’t scale to meet this demand. On the face of it this seems fair. But what about some genuine use case that requires a high rate of automated low payment transactions? Nano would not scale to meet this demand. So either nano has already failed to scale, or these transactions are also not considered worthy/legitimate. Where do you draw the line and how?

In my view this distinction between “real-world usage” and “spam” is flawed at a fundamental level. I think any time the network reaches saturation and stops confirming blocks (even if they are considered spam) nano has failed to scale to meet the demand. Who is anyone to judge whether the demand is “real” enough?

Even if spam wasn’t a problem, to scale and remain secure we have to assume that decreasing storage costs and the incentive to run nodes increases adequately with adoption or an increase in “real” demand. I have concerns with this assumption as well.

### Are there any previous requests for this feature?

.

## Solution

A solution to this problem is for nodes to not store the ledger. This is entirely possible. Bitcoin SPV nodes validate transactions and blocks without storing the ledger by utilising Merkle trees. We can employ a similar solution for nano.

- Blocks are grouped into packages.
- Nodes store only the Merkle root of each package.
- Users must store their own account chain and accompany any new block with their frontier block along with the Merkle proof of the frontier.

Therefore, the rate of data growth is unaffected by the transaction rate. Therefore, spam does not cause permanent damage anymore. The cost of spam is only the bandwidth used by the nodes to confirm the block. Unlike ledger bloat, this is a one time cost to the network and can be completely reflected in a proof-of-work. The proof-of-work for a block can be made greater than the total cost to the network that block will ever cause, while being easy enough for any device to do.

This completely solves the ledger bloat problem and allows the network to focus on scaling up the CPS capacity as high as possible, showing the world that nano is truely scalable. The much greater CPS capacity combined with existing prioritisation methods will mean that even if spammers can still saturate the network it will have negligible effect and will cost them more. This means there is no longer any incentive to spam. This completely solves the problem of spam. 

Another benefit of this approach is that it could become not worth it for *any* node to store the full ledger. This would naturally make nano a privacy coin. Spam would actually help to ensure privacy.

## Details

  Every time period T, nodes package up all the confirmed, unpackaged blocks. Packaging involves calculating the Merkle tree of all the blocks inside the package, storing a package label and then deleting the blocks. The package label consists of the Merkle root, and the hash of the previous package label.

Packages do not affect consensus or confirmation.

There is no limit on the size of a package, it could have thousands of spam blocks. But this isn’t a problem because we don’t store them. This results in a linear growth of the ledger with time, unaffected by adoption and spam.

But then if we don’t store the blocks who does? The wallets do. Wallets store not only private keys but also each accounts’ frontier block and its Merkle proof. When a user publishes a block it includes this data which the node can use to determine if the frontier has been confirmed by the network.

When I said that the growth rate is constant technically I lied. Nodes need to store 1 bit for each receive and change block, and 2 bits for each send block. These bits are used to indicate whether a block is currently the frontier block for that account, and the secondary bit for send blocks is used to indicate whether the amount has been received by a corresponding receive block. Therefore these bits may change as new blocks get confirmed.

![20240707_224400](https://github.com/nanocurrency/nano-node/assets/58990501/fbd9acbc-f4ad-4225-b5f2-c19bce996386)

## Caveat

Although nodes can verify during the bootstrapping process that their package labels are unmodified and valid, they can no longer independently verify that all the transactions in those packages were valid. This is going to be controversial but it is my opinion that with ORV the consensus of the network **is** the valid ledger. Once a block has been confirmed the validity becomes irrelevant. You have to trust the network.

If people disagree with this I want to mention that it is possible to create an easily verifiable proof of the validity of the ledger without seeing it using a zk-SNARK cryptographic primitive. This would require a non-negligible amount of compute. Could this replace the current proof-of-work?

### If this feature is approved, would you be willing to submit a pull request with the solution?

I am willing to collaborate

**Comment by clemahieu** [comment]
Don't make a Github issue that changes every structural part of the protocol.

**Comment by dylan1951** [comment]
> Don't make a Github issue that changes every structural part of the protocol.

Is there a new process for suggesting ideas such as this? The issue template suggests using forum which is down.
