### ISSUE TITLE
nano_node should allow to write the process id to a pid file

### ISSUE THREAD

**Issue by milahu** [nanocurrency/nano-node#4682]
### Summary

expected:

```
nano_node --daemon --pid_file /tmp/nano_node.pid
```

`nano_node` should delete the pidfile on exit

### What problem would be solved by this feature?

a pidfile makes it easier to manage the daemon

for example [basicswap](https://github.com/basicswap/basicswap) expects the node daemon to create a PID file

### Are there any previous requests for this feature?

no

### Do you have a suggested solution?

yes

### If this feature is approved, would you be willing to submit a pull request with the solution?

I would not

**Comment by clemahieu** [comment]
Added in https://github.com/nanocurrency/nano-node/pull/4685
