### ISSUE TITLE
RPC "chain" inconsistent return type 

### ISSUE THREAD

**Issue by jondwillis** [nanocurrency/nano-node#499]
**Description of bug:**

When issuing a "chain" RPC call, the type of the returned "blocks" property is defined as an array of strings in the RPC documentation. When providing a valid block hash, this holds true. However, if you supply an invalid block hash (e.g. the one listed in the documentation example), the block result is an empty string. 

I think it should either return an empty array, or return an error.

**Steps to reproduce the issue:**
1. `curl -v -d '{ "action": "chain", "count": 1, "block": "000D1BAEC8EC208142C99059B393051BAC8380F9B5A2E6B2489A277D81789F3F"  }' [::1]:7076`

**Describe the results you received:**

 `{ "blocks": "" } `

**Describe the results you expected:**

 `{ "blocks": [] } `

or 

 `{ "error": "Invalid block hash" } `

**Additional information you deem important (e.g. issue happens only occasionally):**

This is especially problematic for strongly typed languages when they are deserializing.

**Environment**:

**logs**

**Comment by PlasmaPower** [comment]
This is a known issue caused by boost. It's basically impossible to fix without overhauling JSON [de]serialization. There might already be a GitHub issue for it, let me check.

**Comment by rotilho** [comment]
Are there any plan to fix this issue?

I'm waiting for it to continue development of https://github.com/rotilho/jnano-client 

This is a serious issue for whom is developing something on top of the RPC interface :(

**Comment by SergiySW** [comment]
Related to https://github.com/nanocurrency/nano-node/pull/526

**Comment by cryptocode** [comment]
All JSON library issues is now tracked with https://github.com/nanocurrency/nano-node/issues/1871
