### ISSUE TITLE
make data_path editable from GUI wallet

### ISSUE THREAD

**Issue by ThunderFD** [nanocurrency/nano-node#652]
I couldn't find any way to change the path to the data folder (AppData/Local/Raiblocks) inside the current GUI wallet v10.0.1.

this was added to the node as a launch parameter in the past already, here: #79 
`--data_path PATH`

less tech savy people could change their data path if there was a way to do so in the settings of the GUI wallet, maybe something for the upcoming GUI wallet

**Comment by thehen101** [comment]
I've added a workaround to the wiki: https://github.com/nanocurrency/raiblocks/wiki/RaiBlocks-folder

**Comment by zhyatt** [comment]
After review we will be closing this ticket out due to issues with config file being in the path and alternative options to change data_path on node launch.

**Comment by crcarlo** [comment]
I don't get why this issue has been closed.

In V18.0 I can't still find a way to give `nano_wallet.exe` the `--data_path` option nor the possibilty to change the setting in the GUI. Furthermore it has been removed from the V19.0 milestone.

Did you choose not to support this setting in the wallet GUI?

**Comment by zhyatt** [comment]
@crcarlo We have decided not to implement this in the GUI as this is a development/test wallet and there are options to do this on launch using the `--data_path` option (after moving the files to the new location).
