### ISSUE TITLE
Refresh the accounts list after importing seed

### ISSUE THREAD

**Issue by HostFat** [nanocurrency/nano-node#70]
The node should check accounts with rai in them after importing the seed.
Maybe it should check until 30 accounts in row are empty.
It should also make an automatic full check again after leaving the synchronisation state IF after an importing seed.

**Comment by SergiySW** [comment]
We check for known accounts. But not doing check after sync end
`It should also make an automatic full check again after leaving the synchronisation state IF after an importing seed.`

**Comment by zhyatt** [comment]
Resolved in #1589
