### ISSUE TITLE
RPC/CLI inconsistency with wallet_change_seed

### ISSUE THREAD

**Issue by cgerikj** [nanocurrency/nano-node#793]
The parameters for this command is different for RPC and CLI.

For RPC it's wallet & seed (correct):
https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol#wallet-change-seed

For CLI it's wallet & key ("key" incorrect?):
https://github.com/nanocurrency/raiblocks/wiki/Command-line-interface#--wallet_change_seed---walletwallet---keykey

**Comment by SergiySW** [comment]
Resolved with https://github.com/nanocurrency/nano-node/pull/1772
