### ISSUE TITLE
Windows: CLI doesn't return info to command line

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/nano-node#84]

**Comment by rkeene** [comment]
Is this still a problem ?  Do we still care about it ?

**Comment by SergiySW** [comment]
Assigned @argakiig as well as he has Windows build environment

**Comment by SergiySW** [comment]
It seems we need solution similar to https://gitlab.com/inkscape/inkscape/blob/master/src/winconsole.cpp

**Comment by SergiySW** [comment]
Or we can just document
`nano_wallet.exe --wallet_list 2>&1 | find /v ""`

**Comment by SergiySW** [comment]
Fixed by https://github.com/nanocurrency/nano-node/pull/1653
