### ISSUE TITLE
"link_as_account" in receive state blocks points to wrong account

### ISSUE THREAD

**Issue by Nanoraii** [nanocurrency/nano-node#895]
As I have pointed out here already:

https://www.reddit.com/r/nanocurrency/comments/8mq20s/nanodeco_doesnt_show_source_account_for_receiving/

there is something odd with receive blocks. For example this transaction is from binance representative:
https://www.nanode.co/block/B7240C1CC009DCB27ED251003BE519176B9C914C98A1CD09D021DD3ADADE187B (xrb_3jwrszth46rk1mu7rmb4rhm54us8yg1gw3ipodftqtikf5yqdyr7471nsg1k) 
however the state block points to this account:
xrb_1ec184mzjop3jc3qzdwh793g1abjmu36q36qeh4g8qpbu7fimr8bm1zqs57o which isn't opened yet. 
The "link" field on the other hand shows the correct transaction hash. This happens on both nanode.co and in the latest nanowallet V13. 
Can it be that the transaction hash is interpreted as public key from the node and then the wrong account address is derived from there?

**Comment by PlasmaPower** [comment]
Link as account is just a different representation of the link field. It isn't an existing account for receive state blocks, just as the link field isn't an existing block hash for send state blocks.

To query the source of a receive state block, use `blocks_info` on the link field.

**Comment by Nanoraii** [comment]
I see. Thanks for the answer. This is quite misleading though. At least it shouldn't be in the block explorer then.

**Comment by labmir** [comment]
`Link as account is just a different representation of the link field. ` What is the use of that?

**Comment by forresthopkinsa** [comment]
Agreed, it's a misleading field
