### ISSUE TITLE
Update the main menu of wiki standstill (Small change but helping saving time a lot)

### ISSUE THREAD

**Issue by cseblog** [nanocurrency/nano-node#897]
**Description of bug:**
Update the main menu of wiki standstill on the right side. It will help much a person like me when searching and read documents for developing.  

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

**logs**

**Comment by zhyatt** [comment]
@cseblog Closing out due to lack of response.  If you wish to reopen please provide more clarity around the request.
